/home/mplagge/development/tnt_benchmark/assist.c File Reference
#include `assist.h`
*
#include <math.h>
*
Functions
tw_stime getNextEventTime (tw_lp *lp)
Gets the next small-tick event time.
tw_stime getCurrentBigTick (tw_stime now)
Given a tw_stime, returns the current big tick.
tw_stime getNextBigTick (tw_stime now)
Given a tw_stime, returns the next big-tick that will happen.
Function Documentation
tw_stime getCurrentBigTick (tw_stime now)
Given a tw_stime, returns the current big tick.
If the time is in-between big ticks, this rounds down to the last big tick. There is a bit of a fuzz for times close to the next big tick so if the current time is within BIG_TICK_ERR of the next big tick, that will be returned instead. Sane parameters would probably be around .000001.
Todo
Todo : Implement & determin if ε needs to be added to the return value.
Todo
Todo need to see if this will kill performance:
Definition at line 30 of file assist.c.
References CORE_SIZE.
Referenced by getNextBigTick(), and linearLeak().
                                        {
    tw_stime ctick = now / CORE_SIZE;
    long double vtr = 0;
    long long rem = modfl(ctick, &vtr);
    //Rem is current tick, vtr is offset.
    return rem;
}
tw_stime getNextBigTick (tw_stime now)
Given a tw_stime, returns the next big-tick that will happen.
Parameters
now Right now!
Returns
Next big tick time.
Definition at line 41 of file assist.c.
References CORE_SIZE, and getCurrentBigTick().
Referenced by neuronFire(), and sendHeartbeat().
                                      {
    long long curr = CORE_SIZE * getCurrentBigTick(now) + 1;
    return curr - now;
        //Need to figure this out - not accurate until this is done:
}
tw_stime getNextEventTime (tw_lp * lp)
Gets the next small-tick event time.
Gets the next event time, based on a random function.
Definition at line 14 of file assist.c.
Referenced by axonReceiveMessage(), and synapseReceiveMessage().
                                    {
    tw_stime r =tw_rand_unif(lp->rng) / 10;
    return r;
}