/home/mplagge/development/tnt_benchmark/models/neuron.h File Reference
#include <stdio.h>
*
#include `../assist.h`
*
#include `../mapping.h`
*
#include `ross.h`
*
#include <stdbool.h>
*
Data Structures
union resetRate
ResetRate This is a support union for neuron reset rates.
struct neuronState
This struct maintains the state of an individual neuron.The neuron struct contains the parameters needed to maintain state in the neuron, along with references to output commands (dendrites).
Typedefs
typedef void(* leakFunDel) (void *neuronState, tw_stime now)
typedef void(* reverseLeakDel) (void *neuron, tw_stime now)
typedef void(* resetFunDel) (void *neuronState)
ResetFunDel - This is a function that handles different reset rate calculations.
typedef void(* reverseResetDel) (void *neuronState)
This is a function that reverses the reset command.
Enumerations
enum neuronFireMode { NFM = 0
 }
typedef NeuronFireMode Just in case there are multiple fire modes, this enum exists to differentiate them.
Functions
void noLeak (void *neuron, tw_stime now)
noLeak - A non leaking neuron function.
void linearLeak (void *neuron, tw_stime now)
A linear leak function - uses monotonic up and down leaks.
void monotonicUpLeak (void *neuron, tw_stime now)
void monotonicDownLeak (void *neuron, tw_stime now)
void divergentLeak (void *neuron, tw_stime now)
void convergentLeak (void *neuron, tw_stime now)
void revNoLeak (void *neuron, tw_stime now)
Reverse leak function for use when neurons have no defined leak function.
void revLinearLeak (void *neuron, tw_stime now)
Reverse leak function neurons that have a linear leak function assigned.
void resetNormal (void *neuronState)
Resets neuron voltage to $R$ after firing.
void resetLinear (void *neuronState)
Resets neuron voltage based on linear function.
void resetNone (void *neuronState)
No reset function - does not reset membrane potential after firing.
void reverseResetLinear (void *neuronState)
void reverseResetZero (void *neuronState)
void reverseResetNone (void *neuronState)
void neuronReverseFinal (neuronState *s, tw_bf *CV, Msg_Data *m, tw_lp *lp)
neuronReverseFinal final neuron reversal function.
void neuronReceiveMessage (neuronState *st, tw_stime time, Msg_Data *m, tw_lp *lp)
handles incomming synapse messages.
void neuronFire (neuronState *st, tw_stime time, tw_lp *lp)
neuronFire manages a firing event.
void integrateSynapse (_idT synapseID, neuronState *st, tw_lp *lp)
function that adds a synapse's value to the current neuron's membrane potential.
void sendHeartbeat (neuronState *st, tw_lp *lp, tw_stime time)
Function that sends a heartbeat message to this neuron.
bool neuronShouldFire (neuronState *st, tw_lp *lp)
Checks to see if a neuron should fire.
void neuronPostIntegrate (neuronState *st, tw_stime time, tw_lp *lp, bool willFire)
Function that runs after integration & firing, for reset function and threshold bounce calls.
void stochasticIntegrate (_weightT weight, neuronState *st, tw_lp *lp)
Neuron stochastic integration function - for use with stochastic leaks and synapse messages.
void neronReverseSate (neuronState *s, tw_bf *CV, Msg_Data *M, tw_lp *lp)
Typedef Documentation
typedef void(* leakFunDel) (void *neuronState, tw_stime now)
Definition at line 33 of file neuron.h.
typedef void(* resetFunDel) (void *neuronState)
ResetFunDel - This is a function that handles different reset rate calculations.
It takes the state of the neuron, and applies various reset functions to the neuron's voltage. Some reset functions described by true north include a zeroing function (standard integrate and fire), a linear drop function, and a non-reduction function. Also functions for leaks below.
Definition at line 94 of file neuron.h.
typedef void(* reverseLeakDel) (void *neuron, tw_stime now)
Definition at line 59 of file neuron.h.
reverseResetDel
This is a function that reverses the reset command.
Run first, since the reset function is run last.
Definition at line 125 of file neuron.h.
Enumeration Type Documentation
enum neuronFireMode
typedef NeuronFireMode Just in case there are multiple fire modes, this enum exists to differentiate them.
Enumerator
NFM
Definition at line 23 of file neuron.h.
                                {
  NFM = 0 // normal fire mode (if voltage > threshold, fire);
    } neuronFireMode;
Function Documentation
void convergentLeak (void * neuron, tw_stime now)
void divergentLeak (void * neuron, tw_stime now)
void integrateSynapse (_idT synapseID, neuronState * st, tw_lp * lp)
function that adds a synapse's value to the current neuron's membrane potential.
Parameters
synapseID localID of the synapse sending the message.
Definition at line 199 of file neuron.c.
References _voltT, neuronState::membranePot, stochasticIntegrate(), neuronState::synapticWeightProb, and neuronState::synapticWeightProbSelect.
Referenced by neuronReceiveMessage().
                                                                 {
    if(st->synapticWeightProbSelect[synapseID] == true) {
        stochasticIntegrate(st->synapticWeightProb[synapseID], st, lp)
      ;
    } else { //det. mode integrate:
        _voltT adjustedWeight = st->synapticWeightProb[synapseID];
        st->membranePot += adjustedWeight;
    }
}
void linearLeak (void * neuron, tw_stime now)
A linear leak function - uses monotonic up and down leaks.
Parameters
neuron The current neuron state.
now The current simulation time.
LinearLeak is the standard linear leak function from the paper. Using the leakRate parameter inside the neuron state , this follows a simple linear function, reducing the membrane potential by a fixed rate per tick.
See also
NeuronModel
Definition at line 28 of file neuron.c.
References getCurrentBigTick(), and neuronState::lastLeakTime.
                                            {
    neuronState *s = (neuronState *)neuron;
    tw_stime bigTick = getCurrentBigTick(now);
    tw_stime delta = bigTick - s->lastLeakTime;
        //s->membranePot -= s->leakRate * delta;
    s->lastLeakTime = now;
}
void monotonicDownLeak (void * neuron, tw_stime now)
void monotonicUpLeak (void * neuron, tw_stime now)
void neronReverseSate (neuronState * s, tw_bf * CV, Msg_Data * M, tw_lp * lp)
Definition at line 232 of file neuron.c.
References Msg_Data::eventType, neuronState::fireCount, neuronState::firedLast, neuronState::lastActiveTime, neuronState::lastLeakTime, neuronState::membranePot, neuronState::receivedSynapseMsgs, neuronState::savedLastActiveTime, neuronState::savedLastLeakTime, neuronState::savedMembranePot, neuronState::SOPSCount, and SYNAPSE_OUT.
                                                                         {
        //reverse function.
    if(M->eventType == SYNAPSE_OUT)
        s->receivedSynapseMsgs --;
    else
        s->SOPSCount --;
    if(s->firedLast == true){
        s->fireCount --;
    }
    s->membranePot = s->savedMembranePot;
    s->lastActiveTime = s->savedLastActiveTime;
    s->lastLeakTime = s->savedLastLeakTime;
}
void neuronFire (neuronState * st, tw_stime time, tw_lp * lp)
neuronFire manages a firing event.
Firing events occur when a synchro message is received, so these calculations are done on big-ticks only.
Definition at line 167 of file neuron.c.
References neuronState::dendriteGlobalDest, Msg_Data::eventType, neuronState::firedLast, getNextBigTick(), Msg_Data::localID, neuronState::myLocalID, and NEURON_OUT.
Referenced by neuronReceiveMessage().
                                                          {
    tw_stime nextHeartbeat = getNextBigTick(time);
    tw_event *newEvent = tw_event_new(st->dendriteGlobalDest, nextHeartbeat, lp);
    Msg_Data *data = (Msg_Data *) tw_event_data(newEvent);
    data->eventType = NEURON_OUT;
    data->localID = st->myLocalID;
    tw_event_send(newEvent);
    st->firedLast = true;
}
void neuronPostIntegrate (neuronState * st, tw_stime time, tw_lp * lp, bool willFire)
Function that runs after integration & firing, for reset function and threshold bounce calls.
Parameters
st state
time event time
lp lp
didFire did the neuron fire during this big tick?
Todo
Todo There is potentially an issue here - does the TrueNorth architecture draw a new pseudorandom number during the threshold, fire, reset functions, or does it resuse them? It looks like re-use, so that's what I'm doing here.
Definition at line 214 of file neuron.c.
References _randT, _threshT, _voltT, neuronState::doReset, neuronState::drawnRandomNumber, DT, neuronState::membranePot, neuronState::negativeThreshold, neuronState::negThresReset, neuronState::resetMode, and neuronState::resetVoltage.
Referenced by neuronReceiveMessage().
                                                                                  {
    if(willFire){ // neuron will/did fire:
        st->doReset(st);
    } else if (st->membranePot < -1 * (st->negativeThreshold * st->
      negThresReset + (st->negativeThreshold + st->
      drawnRandomNumber))){
            //sanity variables for the formulaic reset/bounce instead of calling functions:
        _threshT B = st->negativeThreshold;
        int K = st->negThresReset;
        int G = st->resetMode;
        _randT n = st->drawnRandomNumber;
        _voltT R = st->resetVoltage;
        _voltT V = st->membranePot;
        st->membranePot = (-(B*K) + (-(DT(G)) * R +
                                     DT(G-1) * (V + (B + n)) +
                                     DT(G-2) * V) * (1-K));
    }
}
void neuronReceiveMessage (neuronState * st, tw_stime time, Msg_Data * m, tw_lp * lp)
handles incomming synapse messages.
In this model, the neurons send messages to axons during `big tick` intervals. This is done through an event sent upon receipt of the first synapse message of the current big-tick.
Parameters
st current neuron state
time time event was received
m event message data
lp lp.
neruonReceiveMessage runs when an event is received by a neuron. The events are handled in the following fashion:
If the event is a synapse, the neuron integrates the weight of the synapse into its membrane potential.
The count of big-tick synapse messages recived is incremented.
If the count changes from zero to one, the function creates and queues a heartbeat event for the next big-tick.
If the event is a heartbeat, the neuron will leak, potentially fire, and reset.
Big-Tick events are sent at time $ð’¯_{bigTick} - Îµ$, so that the the event will arrive at the next bit-tick time.
Definition at line 103 of file neuron.c.
References neuronState::doLeak, neuronState::drawnRandomNumber, Msg_Data::eventType, neuronState::fireCount, neuronState::firedLast, integrateSynapse(), neuronState::lastActiveTime, neuronState::lastLeakTime, Msg_Data::localID, neuronState::membranePot, NEURON_HEARTBEAT, neuronFire(), neuronPostIntegrate(), neuronShouldFire(), neuronState::rcvdMsgCount, neuronState::receivedSynapseMsgs, Msg_Data::rndCallCount, neuronState::savedLastActiveTime, neuronState::savedLastLeakTime, neuronState::savedMembranePot, sendHeartbeat(), neuronState::SOPSCount, SYNAPSE_OUT, and neuronState::thresholdPRNMask.
          {
    bool willFire = false;
    st->firedLast = false;
        //save the previous state of the neuron:
    st->savedLastLeakTime = st->lastLeakTime;
    st->savedLastActiveTime = st->lastActiveTime;
    st->savedMembranePot = st->membranePot;
        //random fn call state management.
    unsigned long startCount = lp->rng->count;
    switch (m->eventType) {
  case SYNAPSE_OUT:
            integrateSynapse(m->localID, st, lp);
                //next, we will check if a heartbeat message should be sent
            if(st->receivedSynapseMsgs == 0) {
                sendHeartbeat(st, lp, time);
            }
            st->receivedSynapseMsgs ++;
            break;
        case NEURON_HEARTBEAT:
            st->receivedSynapseMsgs = 0;
                //set up drawn random number for the heartbeat.
            if(st->thresholdPRNMask != 0)
                st->drawnRandomNumber = tw_rand_integer(lp->rng, 0, st->
      thresholdPRNMask);
                //Currently operates - leak->fire->(reset)
            st->doLeak(st, time);
            willFire = neuronShouldFire(st,lp);
            if(willFire){
                neuronFire(st, time, lp);
                st->fireCount ++;
            }
            neuronPostIntegrate(st, time, lp, willFire);
            //stats collection
            st->SOPSCount ++;
            st->lastActiveTime = tw_now(lp);
            break;
  default:
                //Error condition - non-valid input.
            break;
    }
        //store the random calls in the message:
    m->rndCallCount = lp->rng->count - startCount;
    st->rcvdMsgCount ++;
}
void neuronReverseFinal (neuronState * s, tw_bf * CV, Msg_Data * m, tw_lp * lp)
neuronReverseFinal final neuron reversal function.
Used to roll back any calls made by the neuron. Decrements receivedSynapseMsgs Reset funs have already been run at this point
See also
reverseLeakDel() and
reverseResetDel()
Parameters
s the neuron state
CV transported bitfield
m the rollback message
lp the lp
bool neuronShouldFire (neuronState * st, tw_lp * lp)
Checks to see if a neuron should fire.
Todo
Todo check to see if this is needed, since it looks like just a simple if statement is in order.
Parameters
st neuron state
Returns
true if the neuron is ready to fire.
Definition at line 161 of file neuron.c.
References neuronState::drawnRandomNumber, neuronState::membranePot, and neuronState::threshold.
Referenced by neuronReceiveMessage().
                                                 {
        //check negative threshold values:
    return st->membranePot >= st->threshold + st->
      drawnRandomNumber;
}
void noLeak (void * neuron, tw_stime now)
noLeak - A non leaking neuron function.
Parameters
neuron The current neuron state.
now The current simulation time.
Definition at line 16 of file neuron.c.
                                        {
  // do nothing!!
}
void resetLinear (void * neuronState)
Resets neuron voltage based on linear function.
Parameters
neuronState neuronState
Linear reset mode - ignores $R$, and sets the membrane potential to the difference between the threshold and the potential.
Definition at line 66 of file neuron.c.
                                    {
    struct NeuronModel *s = (struct NeuronModel *)neuronState;
    s->membranePot = s->membranePot - s->threshold;
}
void resetNone (void * neuronState)
No reset function - does not reset membrane potential after firing.
Parameters
neuronState current neuron state.
void resetNormal (void * neuronState)
Resets neuron voltage to $R$ after firing.
a normal reset mode function.
Parameters
neuronState current neuron state
Definition at line 56 of file neuron.c.
                                    {
    struct NeuronModel *s = (struct NeuronModel *)neuronState;
    s->membranePot = s->resetVoltage; // set current voltage to \f$R\f$.
}
void reverseResetLinear (void * neuronState)
Definition at line 71 of file neuron.c.
References _voltT.
                                          {
    struct NeuronModel *s = (struct NeuronModel *)neuronState;
    _voltT resetParam = (_voltT) &resetParam;
    s->membranePot = s->membranePot + resetParam;
}
void reverseResetNone (void * neuronState)
void reverseResetZero (void * neuronState)
Todo
Todo : Check that this is the proper way to handle reset zero function
Definition at line 79 of file neuron.c.
                                        {
}
void revLinearLeak (void * neuron, tw_stime now)
Reverse leak function neurons that have a linear leak function assigned.
Parameters
neuron current neuron state
now tw_stime representing current time of simulation.
Definition at line 37 of file neuron.c.
References neuronState::lastLeakTime.
                                              {
    neuronState *s = (neuronState *)neuron;
    tw_stime delta = s->lastLeakTime - now;
        //s->membranePot += s->leakRate * delta;
    s->lastLeakTime = now;
}
void revNoLeak (void * neuron, tw_stime now)
Reverse leak function for use when neurons have no defined leak function.
Parameters
neuron current neuron state
now tw_stime representing current time of simulation.
Definition at line 19 of file neuron.c.
                                           {
  // do nothing!!
}
void sendHeartbeat (neuronState * st, tw_lp * lp, tw_stime time)
Function that sends a heartbeat message to this neuron.
Parameters
lp <#lp description#>
time <#time description#>
Definition at line 179 of file neuron.c.
References Msg_Data::eventType, getNextBigTick(), Msg_Data::localID, neuronState::myLocalID, and NEURON_HEARTBEAT.
Referenced by neuronReceiveMessage().
                                                             {
        //heartbeat message gen:
    tw_stime nextHeartbeat = getNextBigTick(time);
    tw_event *newEvent = tw_event_new(lp->gid, nextHeartbeat, lp);
    Msg_Data *data = (Msg_Data *) tw_event_data(newEvent);
    data->eventType = NEURON_HEARTBEAT;
    data->localID = st->myLocalID;
    tw_event_send(newEvent);
}
void stochasticIntegrate (_weightT weight, neuronState * st, tw_lp * lp)
Neuron stochastic integration function - for use with stochastic leaks and synapse messages.
Parameters
weight weight of selected leak or synapse
st the neuron state
lp lp for range functions.
Definition at line 191 of file neuron.c.
References BINCOMP, neuronState::drawnRandomNumber, neuronState::membranePot, and SGN.
Referenced by integrateSynapse().
                                                                     {
    long drawnRandom = st->drawnRandomNumber;
    if (BINCOMP(weight, drawnRandom)){
        st->membranePot += SGN(weight);
    }
}