libs/sqlite3.h File Reference
#include <stdarg.h>
*
Data Structures
struct sqlite3_file
struct sqlite3_io_methods
struct sqlite3_vfs
struct sqlite3_mem_methods
struct sqlite3_module
struct sqlite3_index_info
struct sqlite3_index_info::sqlite3_index_constraint
struct sqlite3_index_info::sqlite3_index_orderby
struct sqlite3_index_info::sqlite3_index_constraint_usage
struct sqlite3_vtab
struct sqlite3_vtab_cursor
struct sqlite3_mutex_methods
struct sqlite3_pcache_page
struct sqlite3_pcache_methods2
struct sqlite3_pcache_methods
struct sqlite3_rtree_geometry
struct sqlite3_rtree_query_info
Macros
#define SQLITE_EXTERN extern
#define SQLITE_API
#define SQLITE_CDECL
#define SQLITE_STDCALL
#define SQLITE_DEPRECATED
#define SQLITE_EXPERIMENTAL
#define SQLITE_VERSION `3.8.10`
#define SQLITE_VERSION_NUMBER 3008010
#define SQLITE_SOURCE_ID `2015-04-23 13:37:05 b5e43602833249aa4b73337bf85b7f308450dab6`
#define SQLITE_OK 0 /* Successful result */
#define SQLITE_ERROR 1 /* SQL error or missing database */
#define SQLITE_INTERNAL 2 /* Internal logic error in SQLite */
#define SQLITE_PERM 3 /* Access permission denied */
#define SQLITE_ABORT 4 /* Callback routine requested an abort */
#define SQLITE_BUSY 5 /* The database file is locked */
#define SQLITE_LOCKED 6 /* A table in the database is locked */
#define SQLITE_NOMEM 7 /* A malloc() failed */
#define SQLITE_READONLY 8 /* Attempt to write a readonly database */
#define SQLITE_INTERRUPT 9 /* Operation terminated by sqlite3_interrupt()*/
#define SQLITE_IOERR 10 /* Some kind of disk I/O error occurred */
#define SQLITE_CORRUPT 11 /* The database disk image is malformed */
#define SQLITE_NOTFOUND 12 /* Unknown opcode in sqlite3_file_control() */
#define SQLITE_FULL 13 /* Insertion failed because database is full */
#define SQLITE_CANTOPEN 14 /* Unable to open the database file */
#define SQLITE_PROTOCOL 15 /* Database lock protocol error */
#define SQLITE_EMPTY 16 /* Database is empty */
#define SQLITE_SCHEMA 17 /* The database schema changed */
#define SQLITE_TOOBIG 18 /* String or BLOB exceeds size limit */
#define SQLITE_CONSTRAINT 19 /* Abort due to constraint violation */
#define SQLITE_MISMATCH 20 /* Data type mismatch */
#define SQLITE_MISUSE 21 /* Library used incorrectly */
#define SQLITE_NOLFS 22 /* Uses OS features not supported on host */
#define SQLITE_AUTH 23 /* Authorization denied */
#define SQLITE_FORMAT 24 /* Auxiliary database format error */
#define SQLITE_RANGE 25 /* 2nd parameter to sqlite3_bind out of range */
#define SQLITE_NOTADB 26 /* File opened that is not a database file */
#define SQLITE_NOTICE 27 /* Notifications from sqlite3_log() */
#define SQLITE_WARNING 28 /* Warnings from sqlite3_log() */
#define SQLITE_ROW 100 /* sqlite3_step() has another row ready */
#define SQLITE_DONE 101 /* sqlite3_step() has finished executing */
#define SQLITE_IOERR_READ (SQLITE_IOERR | (1<<8))
#define SQLITE_IOERR_SHORT_READ (SQLITE_IOERR | (2<<8))
#define SQLITE_IOERR_WRITE (SQLITE_IOERR | (3<<8))
#define SQLITE_IOERR_FSYNC (SQLITE_IOERR | (4<<8))
#define SQLITE_IOERR_DIR_FSYNC (SQLITE_IOERR | (5<<8))
#define SQLITE_IOERR_TRUNCATE (SQLITE_IOERR | (6<<8))
#define SQLITE_IOERR_FSTAT (SQLITE_IOERR | (7<<8))
#define SQLITE_IOERR_UNLOCK (SQLITE_IOERR | (8<<8))
#define SQLITE_IOERR_RDLOCK (SQLITE_IOERR | (9<<8))
#define SQLITE_IOERR_DELETE (SQLITE_IOERR | (10<<8))
#define SQLITE_IOERR_BLOCKED (SQLITE_IOERR | (11<<8))
#define SQLITE_IOERR_NOMEM (SQLITE_IOERR | (12<<8))
#define SQLITE_IOERR_ACCESS (SQLITE_IOERR | (13<<8))
#define SQLITE_IOERR_CHECKRESERVEDLOCK (SQLITE_IOERR | (14<<8))
#define SQLITE_IOERR_LOCK (SQLITE_IOERR | (15<<8))
#define SQLITE_IOERR_CLOSE (SQLITE_IOERR | (16<<8))
#define SQLITE_IOERR_DIR_CLOSE (SQLITE_IOERR | (17<<8))
#define SQLITE_IOERR_SHMOPEN (SQLITE_IOERR | (18<<8))
#define SQLITE_IOERR_SHMSIZE (SQLITE_IOERR | (19<<8))
#define SQLITE_IOERR_SHMLOCK (SQLITE_IOERR | (20<<8))
#define SQLITE_IOERR_SHMMAP (SQLITE_IOERR | (21<<8))
#define SQLITE_IOERR_SEEK (SQLITE_IOERR | (22<<8))
#define SQLITE_IOERR_DELETE_NOENT (SQLITE_IOERR | (23<<8))
#define SQLITE_IOERR_MMAP (SQLITE_IOERR | (24<<8))
#define SQLITE_IOERR_GETTEMPPATH (SQLITE_IOERR | (25<<8))
#define SQLITE_IOERR_CONVPATH (SQLITE_IOERR | (26<<8))
#define SQLITE_LOCKED_SHAREDCACHE (SQLITE_LOCKED | (1<<8))
#define SQLITE_BUSY_RECOVERY (SQLITE_BUSY | (1<<8))
#define SQLITE_BUSY_SNAPSHOT (SQLITE_BUSY | (2<<8))
#define SQLITE_CANTOPEN_NOTEMPDIR (SQLITE_CANTOPEN | (1<<8))
#define SQLITE_CANTOPEN_ISDIR (SQLITE_CANTOPEN | (2<<8))
#define SQLITE_CANTOPEN_FULLPATH (SQLITE_CANTOPEN | (3<<8))
#define SQLITE_CANTOPEN_CONVPATH (SQLITE_CANTOPEN | (4<<8))
#define SQLITE_CORRUPT_VTAB (SQLITE_CORRUPT | (1<<8))
#define SQLITE_READONLY_RECOVERY (SQLITE_READONLY | (1<<8))
#define SQLITE_READONLY_CANTLOCK (SQLITE_READONLY | (2<<8))
#define SQLITE_READONLY_ROLLBACK (SQLITE_READONLY | (3<<8))
#define SQLITE_READONLY_DBMOVED (SQLITE_READONLY | (4<<8))
#define SQLITE_ABORT_ROLLBACK (SQLITE_ABORT | (2<<8))
#define SQLITE_CONSTRAINT_CHECK (SQLITE_CONSTRAINT | (1<<8))
#define SQLITE_CONSTRAINT_COMMITHOOK (SQLITE_CONSTRAINT | (2<<8))
#define SQLITE_CONSTRAINT_FOREIGNKEY (SQLITE_CONSTRAINT | (3<<8))
#define SQLITE_CONSTRAINT_FUNCTION (SQLITE_CONSTRAINT | (4<<8))
#define SQLITE_CONSTRAINT_NOTNULL (SQLITE_CONSTRAINT | (5<<8))
#define SQLITE_CONSTRAINT_PRIMARYKEY (SQLITE_CONSTRAINT | (6<<8))
#define SQLITE_CONSTRAINT_TRIGGER (SQLITE_CONSTRAINT | (7<<8))
#define SQLITE_CONSTRAINT_UNIQUE (SQLITE_CONSTRAINT | (8<<8))
#define SQLITE_CONSTRAINT_VTAB (SQLITE_CONSTRAINT | (9<<8))
#define SQLITE_CONSTRAINT_ROWID (SQLITE_CONSTRAINT |(10<<8))
#define SQLITE_NOTICE_RECOVER_WAL (SQLITE_NOTICE | (1<<8))
#define SQLITE_NOTICE_RECOVER_ROLLBACK (SQLITE_NOTICE | (2<<8))
#define SQLITE_WARNING_AUTOINDEX (SQLITE_WARNING | (1<<8))
#define SQLITE_AUTH_USER (SQLITE_AUTH | (1<<8))
#define SQLITE_OPEN_READONLY 0x00000001 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_READWRITE 0x00000002 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_CREATE 0x00000004 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_DELETEONCLOSE 0x00000008 /* VFS only */
#define SQLITE_OPEN_EXCLUSIVE 0x00000010 /* VFS only */
#define SQLITE_OPEN_AUTOPROXY 0x00000020 /* VFS only */
#define SQLITE_OPEN_URI 0x00000040 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_MEMORY 0x00000080 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_MAIN_DB 0x00000100 /* VFS only */
#define SQLITE_OPEN_TEMP_DB 0x00000200 /* VFS only */
#define SQLITE_OPEN_TRANSIENT_DB 0x00000400 /* VFS only */
#define SQLITE_OPEN_MAIN_JOURNAL 0x00000800 /* VFS only */
#define SQLITE_OPEN_TEMP_JOURNAL 0x00001000 /* VFS only */
#define SQLITE_OPEN_SUBJOURNAL 0x00002000 /* VFS only */
#define SQLITE_OPEN_MASTER_JOURNAL 0x00004000 /* VFS only */
#define SQLITE_OPEN_NOMUTEX 0x00008000 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_FULLMUTEX 0x00010000 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_SHAREDCACHE 0x00020000 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_PRIVATECACHE 0x00040000 /* Ok for sqlite3_open_v2() */
#define SQLITE_OPEN_WAL 0x00080000 /* VFS only */
#define SQLITE_IOCAP_ATOMIC 0x00000001
#define SQLITE_IOCAP_ATOMIC512 0x00000002
#define SQLITE_IOCAP_ATOMIC1K 0x00000004
#define SQLITE_IOCAP_ATOMIC2K 0x00000008
#define SQLITE_IOCAP_ATOMIC4K 0x00000010
#define SQLITE_IOCAP_ATOMIC8K 0x00000020
#define SQLITE_IOCAP_ATOMIC16K 0x00000040
#define SQLITE_IOCAP_ATOMIC32K 0x00000080
#define SQLITE_IOCAP_ATOMIC64K 0x00000100
#define SQLITE_IOCAP_SAFE_APPEND 0x00000200
#define SQLITE_IOCAP_SEQUENTIAL 0x00000400
#define SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN 0x00000800
#define SQLITE_IOCAP_POWERSAFE_OVERWRITE 0x00001000
#define SQLITE_IOCAP_IMMUTABLE 0x00002000
#define SQLITE_LOCK_NONE 0
#define SQLITE_LOCK_SHARED 1
#define SQLITE_LOCK_RESERVED 2
#define SQLITE_LOCK_PENDING 3
#define SQLITE_LOCK_EXCLUSIVE 4
#define SQLITE_SYNC_NORMAL 0x00002
#define SQLITE_SYNC_FULL 0x00003
#define SQLITE_SYNC_DATAONLY 0x00010
#define SQLITE_FCNTL_LOCKSTATE 1
#define SQLITE_FCNTL_GET_LOCKPROXYFILE 2
#define SQLITE_FCNTL_SET_LOCKPROXYFILE 3
#define SQLITE_FCNTL_LAST_ERRNO 4
#define SQLITE_FCNTL_SIZE_HINT 5
#define SQLITE_FCNTL_CHUNK_SIZE 6
#define SQLITE_FCNTL_FILE_POINTER 7
#define SQLITE_FCNTL_SYNC_OMITTED 8
#define SQLITE_FCNTL_WIN32_AV_RETRY 9
#define SQLITE_FCNTL_PERSIST_WAL 10
#define SQLITE_FCNTL_OVERWRITE 11
#define SQLITE_FCNTL_VFSNAME 12
#define SQLITE_FCNTL_POWERSAFE_OVERWRITE 13
#define SQLITE_FCNTL_PRAGMA 14
#define SQLITE_FCNTL_BUSYHANDLER 15
#define SQLITE_FCNTL_TEMPFILENAME 16
#define SQLITE_FCNTL_MMAP_SIZE 18
#define SQLITE_FCNTL_TRACE 19
#define SQLITE_FCNTL_HAS_MOVED 20
#define SQLITE_FCNTL_SYNC 21
#define SQLITE_FCNTL_COMMIT_PHASETWO 22
#define SQLITE_FCNTL_WIN32_SET_HANDLE 23
#define SQLITE_FCNTL_WAL_BLOCK 24
#define SQLITE_GET_LOCKPROXYFILE SQLITE_FCNTL_GET_LOCKPROXYFILE
#define SQLITE_SET_LOCKPROXYFILE SQLITE_FCNTL_SET_LOCKPROXYFILE
#define SQLITE_LAST_ERRNO SQLITE_FCNTL_LAST_ERRNO
#define SQLITE_ACCESS_EXISTS 0
#define SQLITE_ACCESS_READWRITE 1 /* Used by PRAGMA temp_store_directory */
#define SQLITE_ACCESS_READ 2 /* Unused */
#define SQLITE_SHM_UNLOCK 1
#define SQLITE_SHM_LOCK 2
#define SQLITE_SHM_SHARED 4
#define SQLITE_SHM_EXCLUSIVE 8
#define SQLITE_SHM_NLOCK 8
#define SQLITE_CONFIG_SINGLETHREAD 1 /* nil */
#define SQLITE_CONFIG_MULTITHREAD 2 /* nil */
#define SQLITE_CONFIG_SERIALIZED 3 /* nil */
#define SQLITE_CONFIG_MALLOC 4 /* sqlite3_mem_methods* */
#define SQLITE_CONFIG_GETMALLOC 5 /* sqlite3_mem_methods* */
#define SQLITE_CONFIG_SCRATCH 6 /* void*, int sz, int N */
#define SQLITE_CONFIG_PAGECACHE 7 /* void*, int sz, int N */
#define SQLITE_CONFIG_HEAP 8 /* void*, int nByte, int min */
#define SQLITE_CONFIG_MEMSTATUS 9 /* boolean */
#define SQLITE_CONFIG_MUTEX 10 /* sqlite3_mutex_methods* */
#define SQLITE_CONFIG_GETMUTEX 11 /* sqlite3_mutex_methods* */
#define SQLITE_CONFIG_LOOKASIDE 13 /* int int */
#define SQLITE_CONFIG_PCACHE 14 /* no-op */
#define SQLITE_CONFIG_GETPCACHE 15 /* no-op */
#define SQLITE_CONFIG_LOG 16 /* xFunc, void* */
#define SQLITE_CONFIG_URI 17 /* int */
#define SQLITE_CONFIG_PCACHE2 18 /* sqlite3_pcache_methods2* */
#define SQLITE_CONFIG_GETPCACHE2 19 /* sqlite3_pcache_methods2* */
#define SQLITE_CONFIG_COVERING_INDEX_SCAN 20 /* int */
#define SQLITE_CONFIG_SQLLOG 21 /* xSqllog, void* */
#define SQLITE_CONFIG_MMAP_SIZE 22 /* sqlite3_int64, sqlite3_int64 */
#define SQLITE_CONFIG_WIN32_HEAPSIZE 23 /* int nByte */
#define SQLITE_CONFIG_PCACHE_HDRSZ 24 /* int *psz */
#define SQLITE_CONFIG_PMASZ 25 /* unsigned int szPma */
#define SQLITE_DBCONFIG_LOOKASIDE 1001 /* void* int int */
#define SQLITE_DBCONFIG_ENABLE_FKEY 1002 /* int int* */
#define SQLITE_DBCONFIG_ENABLE_TRIGGER 1003 /* int int* */
#define SQLITE_DENY 1 /* Abort the SQL statement with an error */
#define SQLITE_IGNORE 2 /* Don't allow access, but don't generate an error */
#define SQLITE_CREATE_INDEX 1 /* Index Name Table Name */
#define SQLITE_CREATE_TABLE 2 /* Table Name NULL */
#define SQLITE_CREATE_TEMP_INDEX 3 /* Index Name Table Name */
#define SQLITE_CREATE_TEMP_TABLE 4 /* Table Name NULL */
#define SQLITE_CREATE_TEMP_TRIGGER 5 /* Trigger Name Table Name */
#define SQLITE_CREATE_TEMP_VIEW 6 /* View Name NULL */
#define SQLITE_CREATE_TRIGGER 7 /* Trigger Name Table Name */
#define SQLITE_CREATE_VIEW 8 /* View Name NULL */
#define SQLITE_DELETE 9 /* Table Name NULL */
#define SQLITE_DROP_INDEX 10 /* Index Name Table Name */
#define SQLITE_DROP_TABLE 11 /* Table Name NULL */
#define SQLITE_DROP_TEMP_INDEX 12 /* Index Name Table Name */
#define SQLITE_DROP_TEMP_TABLE 13 /* Table Name NULL */
#define SQLITE_DROP_TEMP_TRIGGER 14 /* Trigger Name Table Name */
#define SQLITE_DROP_TEMP_VIEW 15 /* View Name NULL */
#define SQLITE_DROP_TRIGGER 16 /* Trigger Name Table Name */
#define SQLITE_DROP_VIEW 17 /* View Name NULL */
#define SQLITE_INSERT 18 /* Table Name NULL */
#define SQLITE_PRAGMA 19 /* Pragma Name 1st arg or NULL */
#define SQLITE_READ 20 /* Table Name Column Name */
#define SQLITE_SELECT 21 /* NULL NULL */
#define SQLITE_TRANSACTION 22 /* Operation NULL */
#define SQLITE_UPDATE 23 /* Table Name Column Name */
#define SQLITE_ATTACH 24 /* Filename NULL */
#define SQLITE_DETACH 25 /* Database Name NULL */
#define SQLITE_ALTER_TABLE 26 /* Database Name Table Name */
#define SQLITE_REINDEX 27 /* Index Name NULL */
#define SQLITE_ANALYZE 28 /* Table Name NULL */
#define SQLITE_CREATE_VTABLE 29 /* Table Name Module Name */
#define SQLITE_DROP_VTABLE 30 /* Table Name Module Name */
#define SQLITE_FUNCTION 31 /* NULL Function Name */
#define SQLITE_SAVEPOINT 32 /* Operation Savepoint Name */
#define SQLITE_COPY 0 /* No longer used */
#define SQLITE_RECURSIVE 33 /* NULL NULL */
#define SQLITE_LIMIT_LENGTH 0
#define SQLITE_LIMIT_SQL_LENGTH 1
#define SQLITE_LIMIT_COLUMN 2
#define SQLITE_LIMIT_EXPR_DEPTH 3
#define SQLITE_LIMIT_COMPOUND_SELECT 4
#define SQLITE_LIMIT_VDBE_OP 5
#define SQLITE_LIMIT_FUNCTION_ARG 6
#define SQLITE_LIMIT_ATTACHED 7
#define SQLITE_LIMIT_LIKE_PATTERN_LENGTH 8
#define SQLITE_LIMIT_VARIABLE_NUMBER 9
#define SQLITE_LIMIT_TRIGGER_DEPTH 10
#define SQLITE_LIMIT_WORKER_THREADS 11
#define SQLITE_INTEGER 1
#define SQLITE_FLOAT 2
#define SQLITE_BLOB 4
#define SQLITE_NULL 5
#define SQLITE_TEXT 3
#define SQLITE3_TEXT 3
#define SQLITE_UTF8 1 /* IMP: R-37514-35566 */
#define SQLITE_UTF16LE 2 /* IMP: R-03371-37637 */
#define SQLITE_UTF16BE 3 /* IMP: R-51971-34154 */
#define SQLITE_UTF16 4 /* Use native byte order */
#define SQLITE_ANY 5 /* Deprecated */
#define SQLITE_UTF16_ALIGNED 8 /* sqlite3_create_collation only */
#define SQLITE_DETERMINISTIC 0x800
#define SQLITE_STATIC ((sqlite3_destructor_type)0)
#define SQLITE_TRANSIENT ((sqlite3_destructor_type)-1)
#define SQLITE_INDEX_CONSTRAINT_EQ 2
#define SQLITE_INDEX_CONSTRAINT_GT 4
#define SQLITE_INDEX_CONSTRAINT_LE 8
#define SQLITE_INDEX_CONSTRAINT_LT 16
#define SQLITE_INDEX_CONSTRAINT_GE 32
#define SQLITE_INDEX_CONSTRAINT_MATCH 64
#define SQLITE_MUTEX_FAST 0
#define SQLITE_MUTEX_RECURSIVE 1
#define SQLITE_MUTEX_STATIC_MASTER 2
#define SQLITE_MUTEX_STATIC_MEM 3 /* sqlite3_malloc() */
#define SQLITE_MUTEX_STATIC_MEM2 4 /* NOT USED */
#define SQLITE_MUTEX_STATIC_OPEN 4 /* sqlite3BtreeOpen() */
#define SQLITE_MUTEX_STATIC_PRNG 5 /* sqlite3_random() */
#define SQLITE_MUTEX_STATIC_LRU 6 /* lru page list */
#define SQLITE_MUTEX_STATIC_LRU2 7 /* NOT USED */
#define SQLITE_MUTEX_STATIC_PMEM 7 /* sqlite3PageMalloc() */
#define SQLITE_MUTEX_STATIC_APP1 8 /* For use by application */
#define SQLITE_MUTEX_STATIC_APP2 9 /* For use by application */
#define SQLITE_MUTEX_STATIC_APP3 10 /* For use by application */
#define SQLITE_TESTCTRL_FIRST 5
#define SQLITE_TESTCTRL_PRNG_SAVE 5
#define SQLITE_TESTCTRL_PRNG_RESTORE 6
#define SQLITE_TESTCTRL_PRNG_RESET 7
#define SQLITE_TESTCTRL_BITVEC_TEST 8
#define SQLITE_TESTCTRL_FAULT_INSTALL 9
#define SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS 10
#define SQLITE_TESTCTRL_PENDING_BYTE 11
#define SQLITE_TESTCTRL_ASSERT 12
#define SQLITE_TESTCTRL_ALWAYS 13
#define SQLITE_TESTCTRL_RESERVE 14
#define SQLITE_TESTCTRL_OPTIMIZATIONS 15
#define SQLITE_TESTCTRL_ISKEYWORD 16
#define SQLITE_TESTCTRL_SCRATCHMALLOC 17
#define SQLITE_TESTCTRL_LOCALTIME_FAULT 18
#define SQLITE_TESTCTRL_EXPLAIN_STMT 19 /* NOT USED */
#define SQLITE_TESTCTRL_NEVER_CORRUPT 20
#define SQLITE_TESTCTRL_VDBE_COVERAGE 21
#define SQLITE_TESTCTRL_BYTEORDER 22
#define SQLITE_TESTCTRL_ISINIT 23
#define SQLITE_TESTCTRL_SORTER_MMAP 24
#define SQLITE_TESTCTRL_IMPOSTER 25
#define SQLITE_TESTCTRL_LAST 25
#define SQLITE_STATUS_MEMORY_USED 0
#define SQLITE_STATUS_PAGECACHE_USED 1
#define SQLITE_STATUS_PAGECACHE_OVERFLOW 2
#define SQLITE_STATUS_SCRATCH_USED 3
#define SQLITE_STATUS_SCRATCH_OVERFLOW 4
#define SQLITE_STATUS_MALLOC_SIZE 5
#define SQLITE_STATUS_PARSER_STACK 6
#define SQLITE_STATUS_PAGECACHE_SIZE 7
#define SQLITE_STATUS_SCRATCH_SIZE 8
#define SQLITE_STATUS_MALLOC_COUNT 9
#define SQLITE_DBSTATUS_LOOKASIDE_USED 0
#define SQLITE_DBSTATUS_CACHE_USED 1
#define SQLITE_DBSTATUS_SCHEMA_USED 2
#define SQLITE_DBSTATUS_STMT_USED 3
#define SQLITE_DBSTATUS_LOOKASIDE_HIT 4
#define SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE 5
#define SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL 6
#define SQLITE_DBSTATUS_CACHE_HIT 7
#define SQLITE_DBSTATUS_CACHE_MISS 8
#define SQLITE_DBSTATUS_CACHE_WRITE 9
#define SQLITE_DBSTATUS_DEFERRED_FKS 10
#define SQLITE_DBSTATUS_MAX 10 /* Largest defined DBSTATUS */
#define SQLITE_STMTSTATUS_FULLSCAN_STEP 1
#define SQLITE_STMTSTATUS_SORT 2
#define SQLITE_STMTSTATUS_AUTOINDEX 3
#define SQLITE_STMTSTATUS_VM_STEP 4
#define SQLITE_CHECKPOINT_PASSIVE 0 /* Do as much as possible w/o blocking */
#define SQLITE_CHECKPOINT_FULL 1 /* Wait for writers, then checkpoint */
#define SQLITE_CHECKPOINT_RESTART 2 /* Like FULL but wait for for readers */
#define SQLITE_CHECKPOINT_TRUNCATE 3 /* Like RESTART but also truncate WAL */
#define SQLITE_VTAB_CONSTRAINT_SUPPORT 1
#define SQLITE_ROLLBACK 1
#define SQLITE_FAIL 3
#define SQLITE_REPLACE 5
#define SQLITE_SCANSTAT_NLOOP 0
#define SQLITE_SCANSTAT_NVISIT 1
#define SQLITE_SCANSTAT_EST 2
#define SQLITE_SCANSTAT_NAME 3
#define SQLITE_SCANSTAT_EXPLAIN 4
#define SQLITE_SCANSTAT_SELECTID 5
#define _SQLITE3RTREE_H_
#define NOT_WITHIN 0 /* Object completely outside of query region */
#define PARTLY_WITHIN 1 /* Object partially overlaps query region */
#define FULLY_WITHIN 2 /* Object fully contained within query region */
Typedefs
typedef long long int sqlite_int64
typedef unsigned long long int sqlite_uint64
typedef sqlite_int64 sqlite3_int64
typedef sqlite_uint64 sqlite3_uint64
typedef int(* sqlite3_callback) (void *, int, char **, char **)
typedef void(* sqlite3_syscall_ptr) (void)
typedef struct sqlite3_stmt sqlite3_stmt
typedef void(* sqlite3_destructor_type) (void *)
typedef struct sqlite3_blob sqlite3_blob
typedef struct sqlite3_pcache sqlite3_pcache
typedef double sqlite3_rtree_dbl
Functions
SQLITE_API const char *SQLITE_STDCALL sqlite3_libversion (void)
SQLITE_API const char *SQLITE_STDCALL sqlite3_sourceid (void)
SQLITE_API int SQLITE_STDCALL sqlite3_libversion_number (void)
SQLITE_API int SQLITE_STDCALL sqlite3_compileoption_used (const char *zOptName)
SQLITE_API const char *SQLITE_STDCALL sqlite3_compileoption_get (int N)
SQLITE_API int SQLITE_STDCALL sqlite3_threadsafe (void)
SQLITE_API int SQLITE_STDCALL sqlite3_close (sqlite3 *)
SQLITE_API int SQLITE_STDCALL sqlite3_close_v2 (sqlite3 *)
SQLITE_API int SQLITE_STDCALL sqlite3_exec (sqlite3 *, const char *sql, int(*callback)(void *, int, char **, char **), void *, char **errmsg)
SQLITE_API int SQLITE_STDCALL sqlite3_initialize (void)
SQLITE_API int SQLITE_STDCALL sqlite3_shutdown (void)
SQLITE_API int SQLITE_STDCALL sqlite3_os_init (void)
SQLITE_API int SQLITE_STDCALL sqlite3_os_end (void)
SQLITE_API int SQLITE_CDECL sqlite3_config (int,...)
SQLITE_API int SQLITE_CDECL sqlite3_db_config (sqlite3 *, int op,...)
SQLITE_API int SQLITE_STDCALL sqlite3_extended_result_codes (sqlite3 *, int onoff)
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_last_insert_rowid (sqlite3 *)
SQLITE_API int SQLITE_STDCALL sqlite3_changes (sqlite3 *)
SQLITE_API int SQLITE_STDCALL sqlite3_total_changes (sqlite3 *)
SQLITE_API void SQLITE_STDCALL sqlite3_interrupt (sqlite3 *)
SQLITE_API int SQLITE_STDCALL sqlite3_complete (const char *sql)
SQLITE_API int SQLITE_STDCALL sqlite3_complete16 (const void *sql)
SQLITE_API int SQLITE_STDCALL sqlite3_busy_handler (sqlite3 *, int(*)(void *, int), void *)
SQLITE_API int SQLITE_STDCALL sqlite3_busy_timeout (sqlite3 *, int ms)
SQLITE_API int SQLITE_STDCALL sqlite3_get_table (sqlite3 *db, const char *zSql, char ***pazResult, int *pnRow, int *pnColumn, char **pzErrmsg)
SQLITE_API void SQLITE_STDCALL sqlite3_free_table (char **result)
SQLITE_API char *SQLITE_CDECL sqlite3_mprintf (const char *,...)
SQLITE_API char *SQLITE_STDCALL sqlite3_vmprintf (const char *, va_list)
SQLITE_API char *SQLITE_CDECL sqlite3_snprintf (int, char *, const char *,...)
SQLITE_API char *SQLITE_STDCALL sqlite3_vsnprintf (int, char *, const char *, va_list)
SQLITE_API void *SQLITE_STDCALL sqlite3_malloc (int)
SQLITE_API void *SQLITE_STDCALL sqlite3_malloc64 (sqlite3_uint64)
SQLITE_API void *SQLITE_STDCALL sqlite3_realloc (void *, int)
SQLITE_API void *SQLITE_STDCALL sqlite3_realloc64 (void *, sqlite3_uint64)
SQLITE_API void SQLITE_STDCALL sqlite3_free (void *)
SQLITE_API sqlite3_uint64 SQLITE_STDCALL sqlite3_msize (void *)
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_memory_used (void)
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_memory_highwater (int resetFlag)
SQLITE_API void SQLITE_STDCALL sqlite3_randomness (int N, void *P)
SQLITE_API int SQLITE_STDCALL sqlite3_set_authorizer (sqlite3 *, int(*xAuth)(void *, int, const char *, const char *, const char *, const char *), void *pUserData)
SQLITE_API void *SQLITE_STDCALL sqlite3_trace (sqlite3 *, void(*xTrace)(void *, const char *), void *)
SQLITE_API SQLITE_EXPERIMENTAL void *SQLITE_STDCALL sqlite3_profile (sqlite3 *, void(*xProfile)(void *, const char *, sqlite3_uint64), void *)
SQLITE_API void SQLITE_STDCALL sqlite3_progress_handler (sqlite3 *, int, int(*)(void *), void *)
SQLITE_API int SQLITE_STDCALL sqlite3_open (const char *filename, sqlite3 **ppDb)
SQLITE_API int SQLITE_STDCALL sqlite3_open16 (const void *filename, sqlite3 **ppDb)
SQLITE_API int SQLITE_STDCALL sqlite3_open_v2 (const char *filename, sqlite3 **ppDb, int flags, const char *zVfs)
SQLITE_API const char *SQLITE_STDCALL sqlite3_uri_parameter (const char *zFilename, const char *zParam)
SQLITE_API int SQLITE_STDCALL sqlite3_uri_boolean (const char *zFile, const char *zParam, int bDefault)
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_uri_int64 (const char *, const char *, sqlite3_int64)
SQLITE_API int SQLITE_STDCALL sqlite3_errcode (sqlite3 *db)
SQLITE_API int SQLITE_STDCALL sqlite3_extended_errcode (sqlite3 *db)
SQLITE_API const char *SQLITE_STDCALL sqlite3_errmsg (sqlite3 *)
SQLITE_API const void *SQLITE_STDCALL sqlite3_errmsg16 (sqlite3 *)
SQLITE_API const char *SQLITE_STDCALL sqlite3_errstr (int)
SQLITE_API int SQLITE_STDCALL sqlite3_limit (sqlite3 *, int id, int newVal)
SQLITE_API int SQLITE_STDCALL sqlite3_prepare (sqlite3 *db, const char *zSql, int nByte, sqlite3_stmt **ppStmt, const char **pzTail)
SQLITE_API int SQLITE_STDCALL sqlite3_prepare_v2 (sqlite3 *db, const char *zSql, int nByte, sqlite3_stmt **ppStmt, const char **pzTail)
SQLITE_API int SQLITE_STDCALL sqlite3_prepare16 (sqlite3 *db, const void *zSql, int nByte, sqlite3_stmt **ppStmt, const void **pzTail)
SQLITE_API int SQLITE_STDCALL sqlite3_prepare16_v2 (sqlite3 *db, const void *zSql, int nByte, sqlite3_stmt **ppStmt, const void **pzTail)
SQLITE_API const char *SQLITE_STDCALL sqlite3_sql (sqlite3_stmt *pStmt)
SQLITE_API int SQLITE_STDCALL sqlite3_stmt_readonly (sqlite3_stmt *pStmt)
SQLITE_API int SQLITE_STDCALL sqlite3_stmt_busy (sqlite3_stmt *)
SQLITE_API int SQLITE_STDCALL sqlite3_bind_blob (sqlite3_stmt *, int, const void *, int n, void(*)(void *))
SQLITE_API int SQLITE_STDCALL sqlite3_bind_blob64 (sqlite3_stmt *, int, const void *, sqlite3_uint64, void(*)(void *))
SQLITE_API int SQLITE_STDCALL sqlite3_bind_double (sqlite3_stmt *, int, double)
SQLITE_API int SQLITE_STDCALL sqlite3_bind_int (sqlite3_stmt *, int, int)
SQLITE_API int SQLITE_STDCALL sqlite3_bind_int64 (sqlite3_stmt *, int, sqlite3_int64)
SQLITE_API int SQLITE_STDCALL sqlite3_bind_null (sqlite3_stmt *, int)
SQLITE_API int SQLITE_STDCALL sqlite3_bind_text (sqlite3_stmt *, int, const char *, int, void(*)(void *))
SQLITE_API int SQLITE_STDCALL sqlite3_bind_text16 (sqlite3_stmt *, int, const void *, int, void(*)(void *))
SQLITE_API int SQLITE_STDCALL sqlite3_bind_text64 (sqlite3_stmt *, int, const char *, sqlite3_uint64, void(*)(void *), unsigned char encoding)
SQLITE_API int SQLITE_STDCALL sqlite3_bind_value (sqlite3_stmt *, int, const sqlite3_value *)
SQLITE_API int SQLITE_STDCALL sqlite3_bind_zeroblob (sqlite3_stmt *, int, int n)
SQLITE_API int SQLITE_STDCALL sqlite3_bind_parameter_count (sqlite3_stmt *)
SQLITE_API const char *SQLITE_STDCALL sqlite3_bind_parameter_name (sqlite3_stmt *, int)
SQLITE_API int SQLITE_STDCALL sqlite3_bind_parameter_index (sqlite3_stmt *, const char *zName)
SQLITE_API int SQLITE_STDCALL sqlite3_clear_bindings (sqlite3_stmt *)
SQLITE_API int SQLITE_STDCALL sqlite3_column_count (sqlite3_stmt *pStmt)
SQLITE_API const char *SQLITE_STDCALL sqlite3_column_name (sqlite3_stmt *, int N)
SQLITE_API const void *SQLITE_STDCALL sqlite3_column_name16 (sqlite3_stmt *, int N)
SQLITE_API const char *SQLITE_STDCALL sqlite3_column_database_name (sqlite3_stmt *, int)
SQLITE_API const void *SQLITE_STDCALL sqlite3_column_database_name16 (sqlite3_stmt *, int)
SQLITE_API const char *SQLITE_STDCALL sqlite3_column_table_name (sqlite3_stmt *, int)
SQLITE_API const void *SQLITE_STDCALL sqlite3_column_table_name16 (sqlite3_stmt *, int)
SQLITE_API const char *SQLITE_STDCALL sqlite3_column_origin_name (sqlite3_stmt *, int)
SQLITE_API const void *SQLITE_STDCALL sqlite3_column_origin_name16 (sqlite3_stmt *, int)
SQLITE_API const char *SQLITE_STDCALL sqlite3_column_decltype (sqlite3_stmt *, int)
SQLITE_API const void *SQLITE_STDCALL sqlite3_column_decltype16 (sqlite3_stmt *, int)
SQLITE_API int SQLITE_STDCALL sqlite3_step (sqlite3_stmt *)
SQLITE_API int SQLITE_STDCALL sqlite3_data_count (sqlite3_stmt *pStmt)
SQLITE_API const void *SQLITE_STDCALL sqlite3_column_blob (sqlite3_stmt *, int iCol)
SQLITE_API int SQLITE_STDCALL sqlite3_column_bytes (sqlite3_stmt *, int iCol)
SQLITE_API int SQLITE_STDCALL sqlite3_column_bytes16 (sqlite3_stmt *, int iCol)
SQLITE_API double SQLITE_STDCALL sqlite3_column_double (sqlite3_stmt *, int iCol)
SQLITE_API int SQLITE_STDCALL sqlite3_column_int (sqlite3_stmt *, int iCol)
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_column_int64 (sqlite3_stmt *, int iCol)
SQLITE_API const unsigned char *SQLITE_STDCALL sqlite3_column_text (sqlite3_stmt *, int iCol)
SQLITE_API const void *SQLITE_STDCALL sqlite3_column_text16 (sqlite3_stmt *, int iCol)
SQLITE_API int SQLITE_STDCALL sqlite3_column_type (sqlite3_stmt *, int iCol)
SQLITE_API sqlite3_value *SQLITE_STDCALL sqlite3_column_value (sqlite3_stmt *, int iCol)
SQLITE_API int SQLITE_STDCALL sqlite3_finalize (sqlite3_stmt *pStmt)
SQLITE_API int SQLITE_STDCALL sqlite3_reset (sqlite3_stmt *pStmt)
SQLITE_API int SQLITE_STDCALL sqlite3_create_function (sqlite3 *db, const char *zFunctionName, int nArg, int eTextRep, void *pApp, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
SQLITE_API int SQLITE_STDCALL sqlite3_create_function16 (sqlite3 *db, const void *zFunctionName, int nArg, int eTextRep, void *pApp, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
SQLITE_API int SQLITE_STDCALL sqlite3_create_function_v2 (sqlite3 *db, const char *zFunctionName, int nArg, int eTextRep, void *pApp, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *), void(*xDestroy)(void *))
SQLITE_API SQLITE_DEPRECATED int SQLITE_STDCALL sqlite3_aggregate_count (sqlite3_context *)
SQLITE_API SQLITE_DEPRECATED int SQLITE_STDCALL sqlite3_expired (sqlite3_stmt *)
SQLITE_API SQLITE_DEPRECATED int SQLITE_STDCALL sqlite3_transfer_bindings (sqlite3_stmt *, sqlite3_stmt *)
SQLITE_API SQLITE_DEPRECATED int SQLITE_STDCALL sqlite3_global_recover (void)
SQLITE_API SQLITE_DEPRECATED void SQLITE_STDCALL sqlite3_thread_cleanup (void)
SQLITE_API SQLITE_DEPRECATED int SQLITE_STDCALL sqlite3_memory_alarm (void(*)(void *, sqlite3_int64, int), void *, sqlite3_int64)
SQLITE_API const void *SQLITE_STDCALL sqlite3_value_blob (sqlite3_value *)
SQLITE_API int SQLITE_STDCALL sqlite3_value_bytes (sqlite3_value *)
SQLITE_API int SQLITE_STDCALL sqlite3_value_bytes16 (sqlite3_value *)
SQLITE_API double SQLITE_STDCALL sqlite3_value_double (sqlite3_value *)
SQLITE_API int SQLITE_STDCALL sqlite3_value_int (sqlite3_value *)
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_value_int64 (sqlite3_value *)
SQLITE_API const unsigned char *SQLITE_STDCALL sqlite3_value_text (sqlite3_value *)
SQLITE_API const void *SQLITE_STDCALL sqlite3_value_text16 (sqlite3_value *)
SQLITE_API const void *SQLITE_STDCALL sqlite3_value_text16le (sqlite3_value *)
SQLITE_API const void *SQLITE_STDCALL sqlite3_value_text16be (sqlite3_value *)
SQLITE_API int SQLITE_STDCALL sqlite3_value_type (sqlite3_value *)
SQLITE_API int SQLITE_STDCALL sqlite3_value_numeric_type (sqlite3_value *)
SQLITE_API void *SQLITE_STDCALL sqlite3_aggregate_context (sqlite3_context *, int nBytes)
SQLITE_API void *SQLITE_STDCALL sqlite3_user_data (sqlite3_context *)
SQLITE_API sqlite3 *SQLITE_STDCALL sqlite3_context_db_handle (sqlite3_context *)
SQLITE_API void *SQLITE_STDCALL sqlite3_get_auxdata (sqlite3_context *, int N)
SQLITE_API void SQLITE_STDCALL sqlite3_set_auxdata (sqlite3_context *, int N, void *, void(*)(void *))
SQLITE_API void SQLITE_STDCALL sqlite3_result_blob (sqlite3_context *, const void *, int, void(*)(void *))
SQLITE_API void SQLITE_STDCALL sqlite3_result_blob64 (sqlite3_context *, const void *, sqlite3_uint64, void(*)(void *))
SQLITE_API void SQLITE_STDCALL sqlite3_result_double (sqlite3_context *, double)
SQLITE_API void SQLITE_STDCALL sqlite3_result_error (sqlite3_context *, const char *, int)
SQLITE_API void SQLITE_STDCALL sqlite3_result_error16 (sqlite3_context *, const void *, int)
SQLITE_API void SQLITE_STDCALL sqlite3_result_error_toobig (sqlite3_context *)
SQLITE_API void SQLITE_STDCALL sqlite3_result_error_nomem (sqlite3_context *)
SQLITE_API void SQLITE_STDCALL sqlite3_result_error_code (sqlite3_context *, int)
SQLITE_API void SQLITE_STDCALL sqlite3_result_int (sqlite3_context *, int)
SQLITE_API void SQLITE_STDCALL sqlite3_result_int64 (sqlite3_context *, sqlite3_int64)
SQLITE_API void SQLITE_STDCALL sqlite3_result_null (sqlite3_context *)
SQLITE_API void SQLITE_STDCALL sqlite3_result_text (sqlite3_context *, const char *, int, void(*)(void *))
SQLITE_API void SQLITE_STDCALL sqlite3_result_text64 (sqlite3_context *, const char *, sqlite3_uint64, void(*)(void *), unsigned char encoding)
SQLITE_API void SQLITE_STDCALL sqlite3_result_text16 (sqlite3_context *, const void *, int, void(*)(void *))
SQLITE_API void SQLITE_STDCALL sqlite3_result_text16le (sqlite3_context *, const void *, int, void(*)(void *))
SQLITE_API void SQLITE_STDCALL sqlite3_result_text16be (sqlite3_context *, const void *, int, void(*)(void *))
SQLITE_API void SQLITE_STDCALL sqlite3_result_value (sqlite3_context *, sqlite3_value *)
SQLITE_API void SQLITE_STDCALL sqlite3_result_zeroblob (sqlite3_context *, int n)
SQLITE_API int SQLITE_STDCALL sqlite3_create_collation (sqlite3 *, const char *zName, int eTextRep, void *pArg, int(*xCompare)(void *, int, const void *, int, const void *))
SQLITE_API int SQLITE_STDCALL sqlite3_create_collation_v2 (sqlite3 *, const char *zName, int eTextRep, void *pArg, int(*xCompare)(void *, int, const void *, int, const void *), void(*xDestroy)(void *))
SQLITE_API int SQLITE_STDCALL sqlite3_create_collation16 (sqlite3 *, const void *zName, int eTextRep, void *pArg, int(*xCompare)(void *, int, const void *, int, const void *))
SQLITE_API int SQLITE_STDCALL sqlite3_collation_needed (sqlite3 *, void *, void(*)(void *, sqlite3 *, int eTextRep, const char *))
SQLITE_API int SQLITE_STDCALL sqlite3_collation_needed16 (sqlite3 *, void *, void(*)(void *, sqlite3 *, int eTextRep, const void *))
SQLITE_API int SQLITE_STDCALL sqlite3_sleep (int)
SQLITE_API int SQLITE_STDCALL sqlite3_get_autocommit (sqlite3 *)
SQLITE_API sqlite3 *SQLITE_STDCALL sqlite3_db_handle (sqlite3_stmt *)
SQLITE_API const char *SQLITE_STDCALL sqlite3_db_filename (sqlite3 *db, const char *zDbName)
SQLITE_API int SQLITE_STDCALL sqlite3_db_readonly (sqlite3 *db, const char *zDbName)
SQLITE_API sqlite3_stmt *SQLITE_STDCALL sqlite3_next_stmt (sqlite3 *pDb, sqlite3_stmt *pStmt)
SQLITE_API void *SQLITE_STDCALL sqlite3_commit_hook (sqlite3 *, int(*)(void *), void *)
SQLITE_API void *SQLITE_STDCALL sqlite3_rollback_hook (sqlite3 *, void(*)(void *), void *)
SQLITE_API void *SQLITE_STDCALL sqlite3_update_hook (sqlite3 *, void(*)(void *, int, char const *, char const *, sqlite3_int64), void *)
SQLITE_API int SQLITE_STDCALL sqlite3_enable_shared_cache (int)
SQLITE_API int SQLITE_STDCALL sqlite3_release_memory (int)
SQLITE_API int SQLITE_STDCALL sqlite3_db_release_memory (sqlite3 *)
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_soft_heap_limit64 (sqlite3_int64 N)
SQLITE_API SQLITE_DEPRECATED void SQLITE_STDCALL sqlite3_soft_heap_limit (int N)
SQLITE_API int SQLITE_STDCALL sqlite3_table_column_metadata (sqlite3 *db, const char *zDbName, const char *zTableName, const char *zColumnName, char const **pzDataType, char const **pzCollSeq, int *pNotNull, int *pPrimaryKey, int *pAutoinc)
SQLITE_API int SQLITE_STDCALL sqlite3_load_extension (sqlite3 *db, const char *zFile, const char *zProc, char **pzErrMsg)
SQLITE_API int SQLITE_STDCALL sqlite3_enable_load_extension (sqlite3 *db, int onoff)
SQLITE_API int SQLITE_STDCALL sqlite3_auto_extension (void(*xEntryPoint)(void))
SQLITE_API int SQLITE_STDCALL sqlite3_cancel_auto_extension (void(*xEntryPoint)(void))
SQLITE_API void SQLITE_STDCALL sqlite3_reset_auto_extension (void)
SQLITE_API int SQLITE_STDCALL sqlite3_create_module (sqlite3 *db, const char *zName, const sqlite3_module *p, void *pClientData)
SQLITE_API int SQLITE_STDCALL sqlite3_create_module_v2 (sqlite3 *db, const char *zName, const sqlite3_module *p, void *pClientData, void(*xDestroy)(void *))
SQLITE_API int SQLITE_STDCALL sqlite3_declare_vtab (sqlite3 *, const char *zSQL)
SQLITE_API int SQLITE_STDCALL sqlite3_overload_function (sqlite3 *, const char *zFuncName, int nArg)
SQLITE_API int SQLITE_STDCALL sqlite3_blob_open (sqlite3 *, const char *zDb, const char *zTable, const char *zColumn, sqlite3_int64 iRow, int flags, sqlite3_blob **ppBlob)
SQLITE_API SQLITE_EXPERIMENTAL int SQLITE_STDCALL sqlite3_blob_reopen (sqlite3_blob *, sqlite3_int64)
SQLITE_API int SQLITE_STDCALL sqlite3_blob_close (sqlite3_blob *)
SQLITE_API int SQLITE_STDCALL sqlite3_blob_bytes (sqlite3_blob *)
SQLITE_API int SQLITE_STDCALL sqlite3_blob_read (sqlite3_blob *, void *Z, int N, int iOffset)
SQLITE_API int SQLITE_STDCALL sqlite3_blob_write (sqlite3_blob *, const void *z, int n, int iOffset)
SQLITE_API sqlite3_vfs *SQLITE_STDCALL sqlite3_vfs_find (const char *zVfsName)
SQLITE_API int SQLITE_STDCALL sqlite3_vfs_register (sqlite3_vfs *, int makeDflt)
SQLITE_API int SQLITE_STDCALL sqlite3_vfs_unregister (sqlite3_vfs *)
SQLITE_API sqlite3_mutex *SQLITE_STDCALL sqlite3_mutex_alloc (int)
SQLITE_API void SQLITE_STDCALL sqlite3_mutex_free (sqlite3_mutex *)
SQLITE_API void SQLITE_STDCALL sqlite3_mutex_enter (sqlite3_mutex *)
SQLITE_API int SQLITE_STDCALL sqlite3_mutex_try (sqlite3_mutex *)
SQLITE_API void SQLITE_STDCALL sqlite3_mutex_leave (sqlite3_mutex *)
SQLITE_API int SQLITE_STDCALL sqlite3_mutex_held (sqlite3_mutex *)
SQLITE_API int SQLITE_STDCALL sqlite3_mutex_notheld (sqlite3_mutex *)
SQLITE_API sqlite3_mutex *SQLITE_STDCALL sqlite3_db_mutex (sqlite3 *)
SQLITE_API int SQLITE_STDCALL sqlite3_file_control (sqlite3 *, const char *zDbName, int op, void *)
SQLITE_API int SQLITE_CDECL sqlite3_test_control (int op,...)
SQLITE_API int SQLITE_STDCALL sqlite3_status (int op, int *pCurrent, int *pHighwater, int resetFlag)
SQLITE_API int SQLITE_STDCALL sqlite3_status64 (int op, sqlite3_int64 *pCurrent, sqlite3_int64 *pHighwater, int resetFlag)
SQLITE_API int SQLITE_STDCALL sqlite3_db_status (sqlite3 *, int op, int *pCur, int *pHiwtr, int resetFlg)
SQLITE_API int SQLITE_STDCALL sqlite3_stmt_status (sqlite3_stmt *, int op, int resetFlg)
SQLITE_API sqlite3_backup *SQLITE_STDCALL sqlite3_backup_init (sqlite3 *pDest, const char *zDestName, sqlite3 *pSource, const char *zSourceName)
SQLITE_API int SQLITE_STDCALL sqlite3_backup_step (sqlite3_backup *p, int nPage)
SQLITE_API int SQLITE_STDCALL sqlite3_backup_finish (sqlite3_backup *p)
SQLITE_API int SQLITE_STDCALL sqlite3_backup_remaining (sqlite3_backup *p)
SQLITE_API int SQLITE_STDCALL sqlite3_backup_pagecount (sqlite3_backup *p)
SQLITE_API int SQLITE_STDCALL sqlite3_unlock_notify (sqlite3 *pBlocked, void(*xNotify)(void **apArg, int nArg), void *pNotifyArg)
SQLITE_API int SQLITE_STDCALL sqlite3_stricmp (const char *, const char *)
SQLITE_API int SQLITE_STDCALL sqlite3_strnicmp (const char *, const char *, int)
SQLITE_API int SQLITE_STDCALL sqlite3_strglob (const char *zGlob, const char *zStr)
SQLITE_API void SQLITE_CDECL sqlite3_log (int iErrCode, const char *zFormat,...)
SQLITE_API void *SQLITE_STDCALL sqlite3_wal_hook (sqlite3 *, int(*)(void *, sqlite3 *, const char *, int), void *)
SQLITE_API int SQLITE_STDCALL sqlite3_wal_autocheckpoint (sqlite3 *db, int N)
SQLITE_API int SQLITE_STDCALL sqlite3_wal_checkpoint (sqlite3 *db, const char *zDb)
SQLITE_API int SQLITE_STDCALL sqlite3_wal_checkpoint_v2 (sqlite3 *db, const char *zDb, int eMode, int *pnLog, int *pnCkpt)
SQLITE_API int SQLITE_CDECL sqlite3_vtab_config (sqlite3 *, int op,...)
SQLITE_API int SQLITE_STDCALL sqlite3_vtab_on_conflict (sqlite3 *)
SQLITE_API SQLITE_EXPERIMENTAL int SQLITE_STDCALL sqlite3_stmt_scanstatus (sqlite3_stmt *pStmt, int idx, int iScanStatusOp, void *pOut)
SQLITE_API SQLITE_EXPERIMENTAL void SQLITE_STDCALL sqlite3_stmt_scanstatus_reset (sqlite3_stmt *)
SQLITE_API int SQLITE_STDCALL sqlite3_rtree_geometry_callback (sqlite3 *db, const char *zGeom, int(*xGeom)(sqlite3_rtree_geometry *, int, sqlite3_rtree_dbl *, int *), void *pContext)
SQLITE_API int SQLITE_STDCALL sqlite3_rtree_query_callback (sqlite3 *db, const char *zQueryFunc, int(*xQueryFunc)(sqlite3_rtree_query_info *), void *pContext, void(*xDestructor)(void *))
Variables
SQLITE_API SQLITE_EXTERN const char sqlite3_version []
SQLITE_API SQLITE_EXTERN char * sqlite3_temp_directory
SQLITE_API SQLITE_EXTERN char * sqlite3_data_directory
Macro Definition Documentation
#define _SQLITE3RTREE_H_
Definition at line 7731 of file sqlite3.h.
#define FULLY_WITHIN 2 /* Object fully contained within query region */
Definition at line 7823 of file sqlite3.h.
#define NOT_WITHIN 0 /* Object completely outside of query region */
Definition at line 7821 of file sqlite3.h.
#define PARTLY_WITHIN 1 /* Object partially overlaps query region */
Definition at line 7822 of file sqlite3.h.
#define SQLITE3_TEXT 3
Definition at line 3889 of file sqlite3.h.
#define SQLITE_ABORT 4 /* Callback routine requested an abort */
Definition at line 409 of file sqlite3.h.
#define SQLITE_ABORT_ROLLBACK (SQLITE_ABORT | (2<<8))
Definition at line 492 of file sqlite3.h.
#define SQLITE_ACCESS_EXISTS 0
Definition at line 1228 of file sqlite3.h.
#define SQLITE_ACCESS_READ 2 /* Unused */
Definition at line 1230 of file sqlite3.h.
#define SQLITE_ACCESS_READWRITE 1 /* Used by PRAGMA temp_store_directory */
Definition at line 1229 of file sqlite3.h.
#define SQLITE_ALTER_TABLE 26 /* Database Name Table Name */
Definition at line 2661 of file sqlite3.h.
#define SQLITE_ANALYZE 28 /* Table Name NULL */
Definition at line 2663 of file sqlite3.h.
#define SQLITE_ANY 5 /* Deprecated */
Definition at line 4260 of file sqlite3.h.
#define SQLITE_API
Definition at line 52 of file sqlite3.h.
#define SQLITE_ATTACH 24 /* Filename NULL */
Definition at line 2659 of file sqlite3.h.
#define SQLITE_AUTH 23 /* Authorization denied */
Definition at line 428 of file sqlite3.h.
#define SQLITE_AUTH_USER (SQLITE_AUTH | (1<<8))
Definition at line 506 of file sqlite3.h.
#define SQLITE_BLOB 4
Definition at line 3882 of file sqlite3.h.
#define SQLITE_BUSY 5 /* The database file is locked */
Definition at line 410 of file sqlite3.h.
#define SQLITE_BUSY_RECOVERY (SQLITE_BUSY | (1<<8))
Definition at line 481 of file sqlite3.h.
#define SQLITE_BUSY_SNAPSHOT (SQLITE_BUSY | (2<<8))
Definition at line 482 of file sqlite3.h.
#define SQLITE_CANTOPEN 14 /* Unable to open the database file */
Definition at line 419 of file sqlite3.h.
#define SQLITE_CANTOPEN_CONVPATH (SQLITE_CANTOPEN | (4<<8))
Definition at line 486 of file sqlite3.h.
#define SQLITE_CANTOPEN_FULLPATH (SQLITE_CANTOPEN | (3<<8))
Definition at line 485 of file sqlite3.h.
#define SQLITE_CANTOPEN_ISDIR (SQLITE_CANTOPEN | (2<<8))
Definition at line 484 of file sqlite3.h.
#define SQLITE_CANTOPEN_NOTEMPDIR (SQLITE_CANTOPEN | (1<<8))
Definition at line 483 of file sqlite3.h.
#define SQLITE_CDECL
Definition at line 55 of file sqlite3.h.
#define SQLITE_CHECKPOINT_FULL 1 /* Wait for writers, then checkpoint */
Definition at line 7509 of file sqlite3.h.
#define SQLITE_CHECKPOINT_PASSIVE 0 /* Do as much as possible w/o blocking */
Definition at line 7508 of file sqlite3.h.
#define SQLITE_CHECKPOINT_RESTART 2 /* Like FULL but wait for for readers */
Definition at line 7510 of file sqlite3.h.
#define SQLITE_CHECKPOINT_TRUNCATE 3 /* Like RESTART but also truncate WAL */
Definition at line 7511 of file sqlite3.h.
#define SQLITE_CONFIG_COVERING_INDEX_SCAN 20 /* int */
Definition at line 1809 of file sqlite3.h.
#define SQLITE_CONFIG_GETMALLOC 5 /* sqlite3_mem_methods* */
Definition at line 1794 of file sqlite3.h.
#define SQLITE_CONFIG_GETMUTEX 11 /* sqlite3_mutex_methods* */
Definition at line 1800 of file sqlite3.h.
#define SQLITE_CONFIG_GETPCACHE 15 /* no-op */
Definition at line 1804 of file sqlite3.h.
#define SQLITE_CONFIG_GETPCACHE2 19 /* sqlite3_pcache_methods2* */
Definition at line 1808 of file sqlite3.h.
#define SQLITE_CONFIG_HEAP 8 /* void*, int nByte, int min */
Definition at line 1797 of file sqlite3.h.
#define SQLITE_CONFIG_LOG 16 /* xFunc, void* */
Definition at line 1805 of file sqlite3.h.
#define SQLITE_CONFIG_LOOKASIDE 13 /* int int */
Definition at line 1802 of file sqlite3.h.
#define SQLITE_CONFIG_MALLOC 4 /* sqlite3_mem_methods* */
Definition at line 1793 of file sqlite3.h.
#define SQLITE_CONFIG_MEMSTATUS 9 /* boolean */
Definition at line 1798 of file sqlite3.h.
#define SQLITE_CONFIG_MMAP_SIZE 22 /* sqlite3_int64, sqlite3_int64 */
Definition at line 1811 of file sqlite3.h.
#define SQLITE_CONFIG_MULTITHREAD 2 /* nil */
Definition at line 1791 of file sqlite3.h.
#define SQLITE_CONFIG_MUTEX 10 /* sqlite3_mutex_methods* */
Definition at line 1799 of file sqlite3.h.
#define SQLITE_CONFIG_PAGECACHE 7 /* void*, int sz, int N */
Definition at line 1796 of file sqlite3.h.
#define SQLITE_CONFIG_PCACHE 14 /* no-op */
Definition at line 1803 of file sqlite3.h.
#define SQLITE_CONFIG_PCACHE2 18 /* sqlite3_pcache_methods2* */
Definition at line 1807 of file sqlite3.h.
#define SQLITE_CONFIG_PCACHE_HDRSZ 24 /* int *psz */
Definition at line 1813 of file sqlite3.h.
#define SQLITE_CONFIG_PMASZ 25 /* unsigned int szPma */
Definition at line 1814 of file sqlite3.h.
#define SQLITE_CONFIG_SCRATCH 6 /* void*, int sz, int N */
Definition at line 1795 of file sqlite3.h.
#define SQLITE_CONFIG_SERIALIZED 3 /* nil */
Definition at line 1792 of file sqlite3.h.
#define SQLITE_CONFIG_SINGLETHREAD 1 /* nil */
Definition at line 1790 of file sqlite3.h.
#define SQLITE_CONFIG_SQLLOG 21 /* xSqllog, void* */
Definition at line 1810 of file sqlite3.h.
#define SQLITE_CONFIG_URI 17 /* int */
Definition at line 1806 of file sqlite3.h.
#define SQLITE_CONFIG_WIN32_HEAPSIZE 23 /* int nByte */
Definition at line 1812 of file sqlite3.h.
#define SQLITE_CONSTRAINT 19 /* Abort due to constraint violation */
Definition at line 424 of file sqlite3.h.
#define SQLITE_CONSTRAINT_CHECK (SQLITE_CONSTRAINT | (1<<8))
Definition at line 493 of file sqlite3.h.
#define SQLITE_CONSTRAINT_COMMITHOOK (SQLITE_CONSTRAINT | (2<<8))
Definition at line 494 of file sqlite3.h.
#define SQLITE_CONSTRAINT_FOREIGNKEY (SQLITE_CONSTRAINT | (3<<8))
Definition at line 495 of file sqlite3.h.
#define SQLITE_CONSTRAINT_FUNCTION (SQLITE_CONSTRAINT | (4<<8))
Definition at line 496 of file sqlite3.h.
#define SQLITE_CONSTRAINT_NOTNULL (SQLITE_CONSTRAINT | (5<<8))
Definition at line 497 of file sqlite3.h.
#define SQLITE_CONSTRAINT_PRIMARYKEY (SQLITE_CONSTRAINT | (6<<8))
Definition at line 498 of file sqlite3.h.
#define SQLITE_CONSTRAINT_ROWID (SQLITE_CONSTRAINT |(10<<8))
Definition at line 502 of file sqlite3.h.
#define SQLITE_CONSTRAINT_TRIGGER (SQLITE_CONSTRAINT | (7<<8))
Definition at line 499 of file sqlite3.h.
#define SQLITE_CONSTRAINT_UNIQUE (SQLITE_CONSTRAINT | (8<<8))
Definition at line 500 of file sqlite3.h.
#define SQLITE_CONSTRAINT_VTAB (SQLITE_CONSTRAINT | (9<<8))
Definition at line 501 of file sqlite3.h.
#define SQLITE_COPY 0 /* No longer used */
Definition at line 2668 of file sqlite3.h.
#define SQLITE_CORRUPT 11 /* The database disk image is malformed */
Definition at line 416 of file sqlite3.h.
#define SQLITE_CORRUPT_VTAB (SQLITE_CORRUPT | (1<<8))
Definition at line 487 of file sqlite3.h.
#define SQLITE_CREATE_INDEX 1 /* Index Name Table Name */
Definition at line 2636 of file sqlite3.h.
#define SQLITE_CREATE_TABLE 2 /* Table Name NULL */
Definition at line 2637 of file sqlite3.h.
#define SQLITE_CREATE_TEMP_INDEX 3 /* Index Name Table Name */
Definition at line 2638 of file sqlite3.h.
#define SQLITE_CREATE_TEMP_TABLE 4 /* Table Name NULL */
Definition at line 2639 of file sqlite3.h.
#define SQLITE_CREATE_TEMP_TRIGGER 5 /* Trigger Name Table Name */
Definition at line 2640 of file sqlite3.h.
#define SQLITE_CREATE_TEMP_VIEW 6 /* View Name NULL */
Definition at line 2641 of file sqlite3.h.
#define SQLITE_CREATE_TRIGGER 7 /* Trigger Name Table Name */
Definition at line 2642 of file sqlite3.h.
#define SQLITE_CREATE_VIEW 8 /* View Name NULL */
Definition at line 2643 of file sqlite3.h.
#define SQLITE_CREATE_VTABLE 29 /* Table Name Module Name */
Definition at line 2664 of file sqlite3.h.
#define SQLITE_DBCONFIG_ENABLE_FKEY 1002 /* int int* */
Definition at line 1875 of file sqlite3.h.
#define SQLITE_DBCONFIG_ENABLE_TRIGGER 1003 /* int int* */
Definition at line 1876 of file sqlite3.h.
#define SQLITE_DBCONFIG_LOOKASIDE 1001 /* void* int int */
Definition at line 1874 of file sqlite3.h.
#define SQLITE_DBSTATUS_CACHE_HIT 7
Definition at line 6624 of file sqlite3.h.
#define SQLITE_DBSTATUS_CACHE_MISS 8
Definition at line 6625 of file sqlite3.h.
#define SQLITE_DBSTATUS_CACHE_USED 1
Definition at line 6618 of file sqlite3.h.
#define SQLITE_DBSTATUS_CACHE_WRITE 9
Definition at line 6626 of file sqlite3.h.
#define SQLITE_DBSTATUS_DEFERRED_FKS 10
Definition at line 6627 of file sqlite3.h.
#define SQLITE_DBSTATUS_LOOKASIDE_HIT 4
Definition at line 6621 of file sqlite3.h.
#define SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL 6
Definition at line 6623 of file sqlite3.h.
#define SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE 5
Definition at line 6622 of file sqlite3.h.
#define SQLITE_DBSTATUS_LOOKASIDE_USED 0
Definition at line 6617 of file sqlite3.h.
#define SQLITE_DBSTATUS_MAX 10 /* Largest defined DBSTATUS */
Definition at line 6628 of file sqlite3.h.
#define SQLITE_DBSTATUS_SCHEMA_USED 2
Definition at line 6619 of file sqlite3.h.
#define SQLITE_DBSTATUS_STMT_USED 3
Definition at line 6620 of file sqlite3.h.
#define SQLITE_DELETE 9 /* Table Name NULL */
Definition at line 2644 of file sqlite3.h.
#define SQLITE_DENY 1 /* Abort the SQL statement with an error */
Definition at line 2613 of file sqlite3.h.
#define SQLITE_DEPRECATED
Definition at line 74 of file sqlite3.h.
#define SQLITE_DETACH 25 /* Database Name NULL */
Definition at line 2660 of file sqlite3.h.
#define SQLITE_DETERMINISTIC 0x800
Definition at line 4271 of file sqlite3.h.
#define SQLITE_DONE 101 /* sqlite3_step() has finished executing */
Definition at line 435 of file sqlite3.h.
#define SQLITE_DROP_INDEX 10 /* Index Name Table Name */
Definition at line 2645 of file sqlite3.h.
#define SQLITE_DROP_TABLE 11 /* Table Name NULL */
Definition at line 2646 of file sqlite3.h.
#define SQLITE_DROP_TEMP_INDEX 12 /* Index Name Table Name */
Definition at line 2647 of file sqlite3.h.
#define SQLITE_DROP_TEMP_TABLE 13 /* Table Name NULL */
Definition at line 2648 of file sqlite3.h.
#define SQLITE_DROP_TEMP_TRIGGER 14 /* Trigger Name Table Name */
Definition at line 2649 of file sqlite3.h.
#define SQLITE_DROP_TEMP_VIEW 15 /* View Name NULL */
Definition at line 2650 of file sqlite3.h.
#define SQLITE_DROP_TRIGGER 16 /* Trigger Name Table Name */
Definition at line 2651 of file sqlite3.h.
#define SQLITE_DROP_VIEW 17 /* View Name NULL */
Definition at line 2652 of file sqlite3.h.
#define SQLITE_DROP_VTABLE 30 /* Table Name Module Name */
Definition at line 2665 of file sqlite3.h.
#define SQLITE_EMPTY 16 /* Database is empty */
Definition at line 421 of file sqlite3.h.
#define SQLITE_ERROR 1 /* SQL error or missing database */
Definition at line 406 of file sqlite3.h.
#define SQLITE_EXPERIMENTAL
Definition at line 75 of file sqlite3.h.
#define SQLITE_EXTERN extern
Definition at line 49 of file sqlite3.h.
#define SQLITE_FAIL 3
Definition at line 7596 of file sqlite3.h.
#define SQLITE_FCNTL_BUSYHANDLER 15
Definition at line 982 of file sqlite3.h.
#define SQLITE_FCNTL_CHUNK_SIZE 6
Definition at line 973 of file sqlite3.h.
#define SQLITE_FCNTL_COMMIT_PHASETWO 22
Definition at line 988 of file sqlite3.h.
#define SQLITE_FCNTL_FILE_POINTER 7
Definition at line 974 of file sqlite3.h.
#define SQLITE_FCNTL_GET_LOCKPROXYFILE 2
Definition at line 969 of file sqlite3.h.
#define SQLITE_FCNTL_HAS_MOVED 20
Definition at line 986 of file sqlite3.h.
#define SQLITE_FCNTL_LAST_ERRNO 4
Definition at line 971 of file sqlite3.h.
#define SQLITE_FCNTL_LOCKSTATE 1
Definition at line 968 of file sqlite3.h.
#define SQLITE_FCNTL_MMAP_SIZE 18
Definition at line 984 of file sqlite3.h.
#define SQLITE_FCNTL_OVERWRITE 11
Definition at line 978 of file sqlite3.h.
#define SQLITE_FCNTL_PERSIST_WAL 10
Definition at line 977 of file sqlite3.h.
#define SQLITE_FCNTL_POWERSAFE_OVERWRITE 13
Definition at line 980 of file sqlite3.h.
#define SQLITE_FCNTL_PRAGMA 14
Definition at line 981 of file sqlite3.h.
#define SQLITE_FCNTL_SET_LOCKPROXYFILE 3
Definition at line 970 of file sqlite3.h.
#define SQLITE_FCNTL_SIZE_HINT 5
Definition at line 972 of file sqlite3.h.
#define SQLITE_FCNTL_SYNC 21
Definition at line 987 of file sqlite3.h.
#define SQLITE_FCNTL_SYNC_OMITTED 8
Definition at line 975 of file sqlite3.h.
#define SQLITE_FCNTL_TEMPFILENAME 16
Definition at line 983 of file sqlite3.h.
#define SQLITE_FCNTL_TRACE 19
Definition at line 985 of file sqlite3.h.
#define SQLITE_FCNTL_VFSNAME 12
Definition at line 979 of file sqlite3.h.
#define SQLITE_FCNTL_WAL_BLOCK 24
Definition at line 990 of file sqlite3.h.
#define SQLITE_FCNTL_WIN32_AV_RETRY 9
Definition at line 976 of file sqlite3.h.
#define SQLITE_FCNTL_WIN32_SET_HANDLE 23
Definition at line 989 of file sqlite3.h.
#define SQLITE_FLOAT 2
Definition at line 3881 of file sqlite3.h.
#define SQLITE_FORMAT 24 /* Auxiliary database format error */
Definition at line 429 of file sqlite3.h.
#define SQLITE_FULL 13 /* Insertion failed because database is full */
Definition at line 418 of file sqlite3.h.
#define SQLITE_FUNCTION 31 /* NULL Function Name */
Definition at line 2666 of file sqlite3.h.
#define SQLITE_GET_LOCKPROXYFILE SQLITE_FCNTL_GET_LOCKPROXYFILE
Definition at line 993 of file sqlite3.h.
#define SQLITE_IGNORE 2 /* Don't allow access, but don't generate an error */
Definition at line 2614 of file sqlite3.h.
#define SQLITE_INDEX_CONSTRAINT_EQ 2
Definition at line 5622 of file sqlite3.h.
#define SQLITE_INDEX_CONSTRAINT_GE 32
Definition at line 5626 of file sqlite3.h.
#define SQLITE_INDEX_CONSTRAINT_GT 4
Definition at line 5623 of file sqlite3.h.
#define SQLITE_INDEX_CONSTRAINT_LE 8
Definition at line 5624 of file sqlite3.h.
#define SQLITE_INDEX_CONSTRAINT_LT 16
Definition at line 5625 of file sqlite3.h.
#define SQLITE_INDEX_CONSTRAINT_MATCH 64
Definition at line 5627 of file sqlite3.h.
#define SQLITE_INSERT 18 /* Table Name NULL */
Definition at line 2653 of file sqlite3.h.
#define SQLITE_INTEGER 1
Definition at line 3880 of file sqlite3.h.
#define SQLITE_INTERNAL 2 /* Internal logic error in SQLite */
Definition at line 407 of file sqlite3.h.
#define SQLITE_INTERRUPT 9 /* Operation terminated by sqlite3_interrupt()*/
Definition at line 414 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC 0x00000001
Definition at line 566 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC16K 0x00000040
Definition at line 572 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC1K 0x00000004
Definition at line 568 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC2K 0x00000008
Definition at line 569 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC32K 0x00000080
Definition at line 573 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC4K 0x00000010
Definition at line 570 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC512 0x00000002
Definition at line 567 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC64K 0x00000100
Definition at line 574 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC8K 0x00000020
Definition at line 571 of file sqlite3.h.
#define SQLITE_IOCAP_IMMUTABLE 0x00002000
Definition at line 579 of file sqlite3.h.
#define SQLITE_IOCAP_POWERSAFE_OVERWRITE 0x00001000
Definition at line 578 of file sqlite3.h.
#define SQLITE_IOCAP_SAFE_APPEND 0x00000200
Definition at line 575 of file sqlite3.h.
#define SQLITE_IOCAP_SEQUENTIAL 0x00000400
Definition at line 576 of file sqlite3.h.
#define SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN 0x00000800
Definition at line 577 of file sqlite3.h.
#define SQLITE_IOERR 10 /* Some kind of disk I/O error occurred */
Definition at line 415 of file sqlite3.h.
#define SQLITE_IOERR_ACCESS (SQLITE_IOERR | (13<<8))
Definition at line 466 of file sqlite3.h.
#define SQLITE_IOERR_BLOCKED (SQLITE_IOERR | (11<<8))
Definition at line 464 of file sqlite3.h.
#define SQLITE_IOERR_CHECKRESERVEDLOCK (SQLITE_IOERR | (14<<8))
Definition at line 467 of file sqlite3.h.
#define SQLITE_IOERR_CLOSE (SQLITE_IOERR | (16<<8))
Definition at line 469 of file sqlite3.h.
#define SQLITE_IOERR_CONVPATH (SQLITE_IOERR | (26<<8))
Definition at line 479 of file sqlite3.h.
#define SQLITE_IOERR_DELETE (SQLITE_IOERR | (10<<8))
Definition at line 463 of file sqlite3.h.
#define SQLITE_IOERR_DELETE_NOENT (SQLITE_IOERR | (23<<8))
Definition at line 476 of file sqlite3.h.
#define SQLITE_IOERR_DIR_CLOSE (SQLITE_IOERR | (17<<8))
Definition at line 470 of file sqlite3.h.
#define SQLITE_IOERR_DIR_FSYNC (SQLITE_IOERR | (5<<8))
Definition at line 458 of file sqlite3.h.
#define SQLITE_IOERR_FSTAT (SQLITE_IOERR | (7<<8))
Definition at line 460 of file sqlite3.h.
#define SQLITE_IOERR_FSYNC (SQLITE_IOERR | (4<<8))
Definition at line 457 of file sqlite3.h.
#define SQLITE_IOERR_GETTEMPPATH (SQLITE_IOERR | (25<<8))
Definition at line 478 of file sqlite3.h.
#define SQLITE_IOERR_LOCK (SQLITE_IOERR | (15<<8))
Definition at line 468 of file sqlite3.h.
#define SQLITE_IOERR_MMAP (SQLITE_IOERR | (24<<8))
Definition at line 477 of file sqlite3.h.
#define SQLITE_IOERR_NOMEM (SQLITE_IOERR | (12<<8))
Definition at line 465 of file sqlite3.h.
#define SQLITE_IOERR_RDLOCK (SQLITE_IOERR | (9<<8))
Definition at line 462 of file sqlite3.h.
#define SQLITE_IOERR_READ (SQLITE_IOERR | (1<<8))
Definition at line 454 of file sqlite3.h.
#define SQLITE_IOERR_SEEK (SQLITE_IOERR | (22<<8))
Definition at line 475 of file sqlite3.h.
#define SQLITE_IOERR_SHMLOCK (SQLITE_IOERR | (20<<8))
Definition at line 473 of file sqlite3.h.
#define SQLITE_IOERR_SHMMAP (SQLITE_IOERR | (21<<8))
Definition at line 474 of file sqlite3.h.
#define SQLITE_IOERR_SHMOPEN (SQLITE_IOERR | (18<<8))
Definition at line 471 of file sqlite3.h.
#define SQLITE_IOERR_SHMSIZE (SQLITE_IOERR | (19<<8))
Definition at line 472 of file sqlite3.h.
#define SQLITE_IOERR_SHORT_READ (SQLITE_IOERR | (2<<8))
Definition at line 455 of file sqlite3.h.
#define SQLITE_IOERR_TRUNCATE (SQLITE_IOERR | (6<<8))
Definition at line 459 of file sqlite3.h.
#define SQLITE_IOERR_UNLOCK (SQLITE_IOERR | (8<<8))
Definition at line 461 of file sqlite3.h.
#define SQLITE_IOERR_WRITE (SQLITE_IOERR | (3<<8))
Definition at line 456 of file sqlite3.h.
#define SQLITE_LAST_ERRNO SQLITE_FCNTL_LAST_ERRNO
Definition at line 995 of file sqlite3.h.
#define SQLITE_LIMIT_ATTACHED 7
Definition at line 3202 of file sqlite3.h.
#define SQLITE_LIMIT_COLUMN 2
Definition at line 3197 of file sqlite3.h.
#define SQLITE_LIMIT_COMPOUND_SELECT 4
Definition at line 3199 of file sqlite3.h.
#define SQLITE_LIMIT_EXPR_DEPTH 3
Definition at line 3198 of file sqlite3.h.
#define SQLITE_LIMIT_FUNCTION_ARG 6
Definition at line 3201 of file sqlite3.h.
#define SQLITE_LIMIT_LENGTH 0
Definition at line 3195 of file sqlite3.h.
#define SQLITE_LIMIT_LIKE_PATTERN_LENGTH 8
Definition at line 3203 of file sqlite3.h.
#define SQLITE_LIMIT_SQL_LENGTH 1
Definition at line 3196 of file sqlite3.h.
#define SQLITE_LIMIT_TRIGGER_DEPTH 10
Definition at line 3205 of file sqlite3.h.
#define SQLITE_LIMIT_VARIABLE_NUMBER 9
Definition at line 3204 of file sqlite3.h.
#define SQLITE_LIMIT_VDBE_OP 5
Definition at line 3200 of file sqlite3.h.
#define SQLITE_LIMIT_WORKER_THREADS 11
Definition at line 3206 of file sqlite3.h.
#define SQLITE_LOCK_EXCLUSIVE 4
Definition at line 592 of file sqlite3.h.
#define SQLITE_LOCK_NONE 0
Definition at line 588 of file sqlite3.h.
#define SQLITE_LOCK_PENDING 3
Definition at line 591 of file sqlite3.h.
#define SQLITE_LOCK_RESERVED 2
Definition at line 590 of file sqlite3.h.
#define SQLITE_LOCK_SHARED 1
Definition at line 589 of file sqlite3.h.
#define SQLITE_LOCKED 6 /* A table in the database is locked */
Definition at line 411 of file sqlite3.h.
#define SQLITE_LOCKED_SHAREDCACHE (SQLITE_LOCKED | (1<<8))
Definition at line 480 of file sqlite3.h.
#define SQLITE_MISMATCH 20 /* Data type mismatch */
Definition at line 425 of file sqlite3.h.
#define SQLITE_MISUSE 21 /* Library used incorrectly */
Definition at line 426 of file sqlite3.h.
#define SQLITE_MUTEX_FAST 0
Definition at line 6259 of file sqlite3.h.
#define SQLITE_MUTEX_RECURSIVE 1
Definition at line 6260 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_APP1 8 /* For use by application */
Definition at line 6269 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_APP2 9 /* For use by application */
Definition at line 6270 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_APP3 10 /* For use by application */
Definition at line 6271 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_LRU 6 /* lru page list */
Definition at line 6266 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_LRU2 7 /* NOT USED */
Definition at line 6267 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_MASTER 2
Definition at line 6261 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_MEM 3 /* sqlite3_malloc() */
Definition at line 6262 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_MEM2 4 /* NOT USED */
Definition at line 6263 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_OPEN 4 /* sqlite3BtreeOpen() */
Definition at line 6264 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_PMEM 7 /* sqlite3PageMalloc() */
Definition at line 6268 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_PRNG 5 /* sqlite3_random() */
Definition at line 6265 of file sqlite3.h.
#define SQLITE_NOLFS 22 /* Uses OS features not supported on host */
Definition at line 427 of file sqlite3.h.
#define SQLITE_NOMEM 7 /* A malloc() failed */
Definition at line 412 of file sqlite3.h.
#define SQLITE_NOTADB 26 /* File opened that is not a database file */
Definition at line 431 of file sqlite3.h.
#define SQLITE_NOTFOUND 12 /* Unknown opcode in sqlite3_file_control() */
Definition at line 417 of file sqlite3.h.
#define SQLITE_NOTICE 27 /* Notifications from sqlite3_log() */
Definition at line 432 of file sqlite3.h.
#define SQLITE_NOTICE_RECOVER_ROLLBACK (SQLITE_NOTICE | (2<<8))
Definition at line 504 of file sqlite3.h.
#define SQLITE_NOTICE_RECOVER_WAL (SQLITE_NOTICE | (1<<8))
Definition at line 503 of file sqlite3.h.
#define SQLITE_NULL 5
Definition at line 3883 of file sqlite3.h.
#define SQLITE_OK 0 /* Successful result */
Definition at line 404 of file sqlite3.h.
#define SQLITE_OPEN_AUTOPROXY 0x00000020 /* VFS only */
Definition at line 520 of file sqlite3.h.
#define SQLITE_OPEN_CREATE 0x00000004 /* Ok for sqlite3_open_v2() */
Definition at line 517 of file sqlite3.h.
#define SQLITE_OPEN_DELETEONCLOSE 0x00000008 /* VFS only */
Definition at line 518 of file sqlite3.h.
#define SQLITE_OPEN_EXCLUSIVE 0x00000010 /* VFS only */
Definition at line 519 of file sqlite3.h.
#define SQLITE_OPEN_FULLMUTEX 0x00010000 /* Ok for sqlite3_open_v2() */
Definition at line 531 of file sqlite3.h.
#define SQLITE_OPEN_MAIN_DB 0x00000100 /* VFS only */
Definition at line 523 of file sqlite3.h.
#define SQLITE_OPEN_MAIN_JOURNAL 0x00000800 /* VFS only */
Definition at line 526 of file sqlite3.h.
#define SQLITE_OPEN_MASTER_JOURNAL 0x00004000 /* VFS only */
Definition at line 529 of file sqlite3.h.
#define SQLITE_OPEN_MEMORY 0x00000080 /* Ok for sqlite3_open_v2() */
Definition at line 522 of file sqlite3.h.
#define SQLITE_OPEN_NOMUTEX 0x00008000 /* Ok for sqlite3_open_v2() */
Definition at line 530 of file sqlite3.h.
#define SQLITE_OPEN_PRIVATECACHE 0x00040000 /* Ok for sqlite3_open_v2() */
Definition at line 533 of file sqlite3.h.
#define SQLITE_OPEN_READONLY 0x00000001 /* Ok for sqlite3_open_v2() */
Definition at line 515 of file sqlite3.h.
#define SQLITE_OPEN_READWRITE 0x00000002 /* Ok for sqlite3_open_v2() */
Definition at line 516 of file sqlite3.h.
#define SQLITE_OPEN_SHAREDCACHE 0x00020000 /* Ok for sqlite3_open_v2() */
Definition at line 532 of file sqlite3.h.
#define SQLITE_OPEN_SUBJOURNAL 0x00002000 /* VFS only */
Definition at line 528 of file sqlite3.h.
#define SQLITE_OPEN_TEMP_DB 0x00000200 /* VFS only */
Definition at line 524 of file sqlite3.h.
#define SQLITE_OPEN_TEMP_JOURNAL 0x00001000 /* VFS only */
Definition at line 527 of file sqlite3.h.
#define SQLITE_OPEN_TRANSIENT_DB 0x00000400 /* VFS only */
Definition at line 525 of file sqlite3.h.
#define SQLITE_OPEN_URI 0x00000040 /* Ok for sqlite3_open_v2() */
Definition at line 521 of file sqlite3.h.
#define SQLITE_OPEN_WAL 0x00080000 /* VFS only */
Definition at line 534 of file sqlite3.h.
#define SQLITE_PERM 3 /* Access permission denied */
Definition at line 408 of file sqlite3.h.
#define SQLITE_PRAGMA 19 /* Pragma Name 1st arg or NULL */
Definition at line 2654 of file sqlite3.h.
#define SQLITE_PROTOCOL 15 /* Database lock protocol error */
Definition at line 420 of file sqlite3.h.
#define SQLITE_RANGE 25 /* 2nd parameter to sqlite3_bind out of range */
Definition at line 430 of file sqlite3.h.
#define SQLITE_READ 20 /* Table Name Column Name */
Definition at line 2655 of file sqlite3.h.
#define SQLITE_READONLY 8 /* Attempt to write a readonly database */
Definition at line 413 of file sqlite3.h.
#define SQLITE_READONLY_CANTLOCK (SQLITE_READONLY | (2<<8))
Definition at line 489 of file sqlite3.h.
#define SQLITE_READONLY_DBMOVED (SQLITE_READONLY | (4<<8))
Definition at line 491 of file sqlite3.h.
#define SQLITE_READONLY_RECOVERY (SQLITE_READONLY | (1<<8))
Definition at line 488 of file sqlite3.h.
#define SQLITE_READONLY_ROLLBACK (SQLITE_READONLY | (3<<8))
Definition at line 490 of file sqlite3.h.
#define SQLITE_RECURSIVE 33 /* NULL NULL */
Definition at line 2669 of file sqlite3.h.
#define SQLITE_REINDEX 27 /* Index Name NULL */
Definition at line 2662 of file sqlite3.h.
#define SQLITE_REPLACE 5
Definition at line 7598 of file sqlite3.h.
#define SQLITE_ROLLBACK 1
Definition at line 7594 of file sqlite3.h.
#define SQLITE_ROW 100 /* sqlite3_step() has another row ready */
Definition at line 434 of file sqlite3.h.
#define SQLITE_SAVEPOINT 32 /* Operation Savepoint Name */
Definition at line 2667 of file sqlite3.h.
#define SQLITE_SCANSTAT_EST 2
Definition at line 7649 of file sqlite3.h.
#define SQLITE_SCANSTAT_EXPLAIN 4
Definition at line 7651 of file sqlite3.h.
#define SQLITE_SCANSTAT_NAME 3
Definition at line 7650 of file sqlite3.h.
#define SQLITE_SCANSTAT_NLOOP 0
Definition at line 7647 of file sqlite3.h.
#define SQLITE_SCANSTAT_NVISIT 1
Definition at line 7648 of file sqlite3.h.
#define SQLITE_SCANSTAT_SELECTID 5
Definition at line 7652 of file sqlite3.h.
#define SQLITE_SCHEMA 17 /* The database schema changed */
Definition at line 422 of file sqlite3.h.
#define SQLITE_SELECT 21 /* NULL NULL */
Definition at line 2656 of file sqlite3.h.
#define SQLITE_SET_LOCKPROXYFILE SQLITE_FCNTL_SET_LOCKPROXYFILE
Definition at line 994 of file sqlite3.h.
#define SQLITE_SHM_EXCLUSIVE 8
Definition at line 1257 of file sqlite3.h.
#define SQLITE_SHM_LOCK 2
Definition at line 1255 of file sqlite3.h.
#define SQLITE_SHM_NLOCK 8
Definition at line 1267 of file sqlite3.h.
#define SQLITE_SHM_SHARED 4
Definition at line 1256 of file sqlite3.h.
#define SQLITE_SHM_UNLOCK 1
Definition at line 1254 of file sqlite3.h.
#define SQLITE_SOURCE_ID `2015-04-23 13:37:05 b5e43602833249aa4b73337bf85b7f308450dab6`
Definition at line 116 of file sqlite3.h.
#define SQLITE_STATIC ((sqlite3_destructor_type)0)
Definition at line 4494 of file sqlite3.h.
#define SQLITE_STATUS_MALLOC_COUNT 9
Definition at line 6500 of file sqlite3.h.
#define SQLITE_STATUS_MALLOC_SIZE 5
Definition at line 6496 of file sqlite3.h.
#define SQLITE_STATUS_MEMORY_USED 0
Definition at line 6491 of file sqlite3.h.
#define SQLITE_STATUS_PAGECACHE_OVERFLOW 2
Definition at line 6493 of file sqlite3.h.
#define SQLITE_STATUS_PAGECACHE_SIZE 7
Definition at line 6498 of file sqlite3.h.
#define SQLITE_STATUS_PAGECACHE_USED 1
Definition at line 6492 of file sqlite3.h.
#define SQLITE_STATUS_PARSER_STACK 6
Definition at line 6497 of file sqlite3.h.
#define SQLITE_STATUS_SCRATCH_OVERFLOW 4
Definition at line 6495 of file sqlite3.h.
#define SQLITE_STATUS_SCRATCH_SIZE 8
Definition at line 6499 of file sqlite3.h.
#define SQLITE_STATUS_SCRATCH_USED 3
Definition at line 6494 of file sqlite3.h.
#define SQLITE_STDCALL
Definition at line 58 of file sqlite3.h.
#define SQLITE_STMTSTATUS_AUTOINDEX 3
Definition at line 6696 of file sqlite3.h.
#define SQLITE_STMTSTATUS_FULLSCAN_STEP 1
Definition at line 6694 of file sqlite3.h.
#define SQLITE_STMTSTATUS_SORT 2
Definition at line 6695 of file sqlite3.h.
#define SQLITE_STMTSTATUS_VM_STEP 4
Definition at line 6697 of file sqlite3.h.
#define SQLITE_SYNC_DATAONLY 0x00010
Definition at line 622 of file sqlite3.h.
#define SQLITE_SYNC_FULL 0x00003
Definition at line 621 of file sqlite3.h.
#define SQLITE_SYNC_NORMAL 0x00002
Definition at line 620 of file sqlite3.h.
#define SQLITE_TESTCTRL_ALWAYS 13
Definition at line 6359 of file sqlite3.h.
#define SQLITE_TESTCTRL_ASSERT 12
Definition at line 6358 of file sqlite3.h.
#define SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS 10
Definition at line 6356 of file sqlite3.h.
#define SQLITE_TESTCTRL_BITVEC_TEST 8
Definition at line 6354 of file sqlite3.h.
#define SQLITE_TESTCTRL_BYTEORDER 22
Definition at line 6368 of file sqlite3.h.
#define SQLITE_TESTCTRL_EXPLAIN_STMT 19 /* NOT USED */
Definition at line 6365 of file sqlite3.h.
#define SQLITE_TESTCTRL_FAULT_INSTALL 9
Definition at line 6355 of file sqlite3.h.
#define SQLITE_TESTCTRL_FIRST 5
Definition at line 6350 of file sqlite3.h.
#define SQLITE_TESTCTRL_IMPOSTER 25
Definition at line 6371 of file sqlite3.h.
#define SQLITE_TESTCTRL_ISINIT 23
Definition at line 6369 of file sqlite3.h.
#define SQLITE_TESTCTRL_ISKEYWORD 16
Definition at line 6362 of file sqlite3.h.
#define SQLITE_TESTCTRL_LAST 25
Definition at line 6372 of file sqlite3.h.
#define SQLITE_TESTCTRL_LOCALTIME_FAULT 18
Definition at line 6364 of file sqlite3.h.
#define SQLITE_TESTCTRL_NEVER_CORRUPT 20
Definition at line 6366 of file sqlite3.h.
#define SQLITE_TESTCTRL_OPTIMIZATIONS 15
Definition at line 6361 of file sqlite3.h.
#define SQLITE_TESTCTRL_PENDING_BYTE 11
Definition at line 6357 of file sqlite3.h.
#define SQLITE_TESTCTRL_PRNG_RESET 7
Definition at line 6353 of file sqlite3.h.
#define SQLITE_TESTCTRL_PRNG_RESTORE 6
Definition at line 6352 of file sqlite3.h.
#define SQLITE_TESTCTRL_PRNG_SAVE 5
Definition at line 6351 of file sqlite3.h.
#define SQLITE_TESTCTRL_RESERVE 14
Definition at line 6360 of file sqlite3.h.
#define SQLITE_TESTCTRL_SCRATCHMALLOC 17
Definition at line 6363 of file sqlite3.h.
#define SQLITE_TESTCTRL_SORTER_MMAP 24
Definition at line 6370 of file sqlite3.h.
#define SQLITE_TESTCTRL_VDBE_COVERAGE 21
Definition at line 6367 of file sqlite3.h.
#define SQLITE_TEXT 3
Definition at line 3887 of file sqlite3.h.
#define SQLITE_TOOBIG 18 /* String or BLOB exceeds size limit */
Definition at line 423 of file sqlite3.h.
#define SQLITE_TRANSACTION 22 /* Operation NULL */
Definition at line 2657 of file sqlite3.h.
#define SQLITE_TRANSIENT ((sqlite3_destructor_type)-1)
Definition at line 4495 of file sqlite3.h.
#define SQLITE_UPDATE 23 /* Table Name Column Name */
Definition at line 2658 of file sqlite3.h.
#define SQLITE_UTF16 4 /* Use native byte order */
Definition at line 4259 of file sqlite3.h.
#define SQLITE_UTF16_ALIGNED 8 /* sqlite3_create_collation only */
Definition at line 4261 of file sqlite3.h.
#define SQLITE_UTF16BE 3 /* IMP: R-51971-34154 */
Definition at line 4258 of file sqlite3.h.
#define SQLITE_UTF16LE 2 /* IMP: R-03371-37637 */
Definition at line 4257 of file sqlite3.h.
#define SQLITE_UTF8 1 /* IMP: R-37514-35566 */
Definition at line 4256 of file sqlite3.h.
#define SQLITE_VERSION `3.8.10`
Definition at line 114 of file sqlite3.h.
#define SQLITE_VERSION_NUMBER 3008010
Definition at line 115 of file sqlite3.h.
#define SQLITE_VTAB_CONSTRAINT_SUPPORT 1
Definition at line 7568 of file sqlite3.h.
#define SQLITE_WARNING 28 /* Warnings from sqlite3_log() */
Definition at line 433 of file sqlite3.h.
#define SQLITE_WARNING_AUTOINDEX (SQLITE_WARNING | (1<<8))
Definition at line 505 of file sqlite3.h.
Typedef Documentation
typedef struct sqlite3_blob sqlite3_blob
Definition at line 5767 of file sqlite3.h.
typedef int(* sqlite3_callback) (void *, int, char **, char **)
Definition at line 321 of file sqlite3.h.
typedef void(* sqlite3_destructor_type) (void *)
Definition at line 4493 of file sqlite3.h.
typedef sqlite_int64 sqlite3_int64
Definition at line 260 of file sqlite3.h.
typedef struct sqlite3_pcache sqlite3_pcache
Definition at line 6710 of file sqlite3.h.
typedef double sqlite3_rtree_dbl
Definition at line 7747 of file sqlite3.h.
typedef struct sqlite3_stmt sqlite3_stmt
Definition at line 3095 of file sqlite3.h.
typedef void(* sqlite3_syscall_ptr) (void)
Definition at line 1168 of file sqlite3.h.
typedef sqlite_uint64 sqlite3_uint64
Definition at line 261 of file sqlite3.h.
typedef long long int sqlite_int64
Definition at line 257 of file sqlite3.h.
typedef unsigned long long int sqlite_uint64
Definition at line 258 of file sqlite3.h.
Function Documentation
SQLITE_API void* SQLITE_STDCALL sqlite3_aggregate_context (sqlite3_context * , int nBytes)
Definition at line 69712 of file sqlite3.c.
References sqlite3_value::flags, sqlite3_context::pMem, and sqlite3_value::z.
                                                                                        {
  assert(p && p->pFunc && p->pFunc->xStep);
  assert(sqlite3_mutex_held(p->pOut->db->mutex));
  testcase(nByte<0);
  if((p->pMem->flags & MEM_Agg)==0){
    return createAggContext(p, nByte);
  }else{
    return (void*)p->pMem->z;
  }
}
SQLITE_API SQLITE_DEPRECATED int SQLITE_STDCALL sqlite3_aggregate_count (sqlite3_context *)
Definition at line 69803 of file sqlite3.c.
References sqlite3_value::n, and sqlite3_context::pMem.
                                                                         {
  assert(p && p->pMem && p->pFunc && p->pFunc->xStep);
  return p->pMem->n;
}
SQLITE_API int SQLITE_STDCALL sqlite3_auto_extension (void(*)(void) xEntryPoint)
Definition at line 103011 of file sqlite3.c.
References sqlite3_initialize(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3MutexAlloc().
                                                                         {
  int rc = SQLITE_OK;
#ifndef SQLITE_OMIT_AUTOINIT
  rc = sqlite3_initialize();
  if(rc){
    return rc;
  }else
#endif
  {
    int i;
#if SQLITE_THREADSAFE
    sqlite3_mutex *mutex = sqlite3MutexAlloc(
      SQLITE_MUTEX_STATIC_MASTER);
#endif
    wsdAutoextInit;
    sqlite3_mutex_enter(mutex);
    for(i=0; i<wsdAutoext.nExt; i++){
      if(wsdAutoext.aExt[i]==xInit) break;
    }
    if(i==wsdAutoext.nExt){
      int nByte = (wsdAutoext.nExt+1)*sizeof(wsdAutoext.aExt[0]);
      void (**aNew)(void);
      aNew = sqlite3_realloc(wsdAutoext.aExt, nByte);
      if(aNew==0){
        rc = SQLITE_NOMEM;
      }else{
        wsdAutoext.aExt = aNew;
        wsdAutoext.aExt[wsdAutoext.nExt] = xInit;
        wsdAutoext.nExt++;
      }
    }
    sqlite3_mutex_leave(mutex);
    assert((rc&0xff)==rc);
    return rc;
  }
}
SQLITE_API int SQLITE_STDCALL sqlite3_backup_finish (sqlite3_backup * p)
Definition at line 62930 of file sqlite3.c.
References sqlite3_backup::isAttached, sqlite3::mutex, Btree::nBackup, sqlite3_backup::pDest, sqlite3_backup::pDestDb, sqlite3_backup::pNext, sqlite3_backup::pSrc, sqlite3_backup::pSrcDb, sqlite3_backup::rc, sqlite3_free(), sqlite3_mutex_enter(), sqlite3BtreeEnter(), sqlite3BtreeLeave(), sqlite3BtreePager(), sqlite3BtreeRollback(), sqlite3Error(), sqlite3LeaveMutexAndCloseZombie(), and sqlite3PagerBackupPtr().
Referenced by sqlite3BtreeCopyFile().
                                                                      {
  sqlite3_backup **pp; /* Ptr to head of pagers backup list */
  sqlite3 *pSrcDb; /* Source database connection */
  int rc; /* Value to return */
  /* Enter the mutexes */
  if(p==0) return SQLITE_OK;
  pSrcDb = p->pSrcDb;
  sqlite3_mutex_enter(pSrcDb->mutex);
  sqlite3BtreeEnter(p->pSrc);
  if(p->pDestDb){
    sqlite3_mutex_enter(p->pDestDb->mutex);
  }
  /* Detach this backup from the source pager. */
  if(p->pDestDb){
    p->pSrc->nBackup--;
  }
  if(p->isAttached){
    pp = sqlite3PagerBackupPtr(sqlite3BtreePager(p->
      pSrc));
    while(*pp!=p){
      pp = &(*pp)->pNext;
    }
    *pp = p->pNext;
  }
  /* If a transaction is still open on the Btree, roll it back. */
  sqlite3BtreeRollback(p->pDest, SQLITE_OK, 0);
  /* Set the error code of the destination database handle. */
  rc = (p->rc==SQLITE_DONE) ? SQLITE_OK : p->rc;
  if(p->pDestDb){
    sqlite3Error(p->pDestDb, rc);
    /* Exit the mutexes and free the backup context structure. */
    sqlite3LeaveMutexAndCloseZombie(p->pDestDb);
  }
  sqlite3BtreeLeave(p->pSrc);
  if(p->pDestDb){
    /* EVIDENCE-OF: R-64852-21591 The sqlite3_backup object is created by a
    ** call to sqlite3_backup_init() and is destroyed by a call to
    ** sqlite3_backup_finish(). */
    sqlite3_free(p);
  }
  sqlite3LeaveMutexAndCloseZombie(pSrcDb);
  return rc;
}
SQLITE_API sqlite3_backup* SQLITE_STDCALL sqlite3_backup_init (sqlite3 * pDest, const char * zDestName, sqlite3 * pSource, const char * zSourceName)
Definition at line 62477 of file sqlite3.c.
References sqlite3_backup::iNext, sqlite3_backup::isAttached, sqlite3::mutex, Btree::nBackup, sqlite3_backup::pDest, sqlite3_backup::pDestDb, sqlite3_backup::pSrc, sqlite3_backup::pSrcDb, sqlite3_free(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3Error(), sqlite3ErrorWithMsg(), and sqlite3MallocZero().
 {
  sqlite3_backup *p; /* Value to return */
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(pSrcDb)||!sqlite3SafetyCheckOk(pDestDb)
       ){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  /* Lock the source database handle. The destination database
  ** handle is not locked in this routine, but it is locked in
  ** sqlite3_backup_step(). The user is required to ensure that no
  ** other thread accesses the destination handle for the duration
  ** of the backup operation. Any attempt to use the destination
  ** database connection while a backup is in progress may cause
  ** a malfunction or a deadlock.
  */
  sqlite3_mutex_enter(pSrcDb->mutex);
  sqlite3_mutex_enter(pDestDb->mutex);
  if(pSrcDb==pDestDb){
    sqlite3ErrorWithMsg(
        pDestDb, SQLITE_ERROR, "source and destination must be distinct"
    );
    p = 0;
  }else {
    /* Allocate space for a new sqlite3_backup object...
    ** EVIDENCE-OF: R-64852-21591 The sqlite3_backup object is created by a
    ** call to sqlite3_backup_init() and is destroyed by a call to
    ** sqlite3_backup_finish(). */
    p = (sqlite3_backup *)sqlite3MallocZero(sizeof(
      sqlite3_backup));
    if(!p){
      sqlite3Error(pDestDb, SQLITE_NOMEM);
    }
  }
  /* If the allocation succeeded, populate the new object. */
  if(p){
    p->pSrc = findBtree(pDestDb, pSrcDb, zSrcDb);
    p->pDest = findBtree(pDestDb, pDestDb, zDestDb);
    p->pDestDb = pDestDb;
    p->pSrcDb = pSrcDb;
    p->iNext = 1;
    p->isAttached = 0;
    if(0==p->pSrc || 0==p->pDest
     || setDestPgsz(p)==SQLITE_NOMEM
     || checkReadTransaction(pDestDb, p->pDest)!=SQLITE_OK
     ){
      /* One (or both) of the named databases did not exist or an OOM
      ** error was hit. Or there is a transaction open on the destination
      ** database. The error has already been written into the pDestDb
      ** handle. All that is left to do here is free the sqlite3_backup
      ** structure. */
      sqlite3_free(p);
      p = 0;
    }
  }
  if(p){
    p->pSrc->nBackup++;
  }
  sqlite3_mutex_leave(pDestDb->mutex);
  sqlite3_mutex_leave(pSrcDb->mutex);
  return p;
}
SQLITE_API int SQLITE_STDCALL sqlite3_backup_pagecount (sqlite3_backup * p)
Definition at line 62996 of file sqlite3.c.
References sqlite3_backup::nPagecount.
                                                                         {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(p==0){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  return p->nPagecount;
}
SQLITE_API int SQLITE_STDCALL sqlite3_backup_remaining (sqlite3_backup * p)
Definition at line 62982 of file sqlite3.c.
References sqlite3_backup::nRemaining.
                                                                         {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(p==0){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  return p->nRemaining;
}
SQLITE_API int SQLITE_STDCALL sqlite3_backup_step (sqlite3_backup * p, int nPage)
Definition at line 62685 of file sqlite3.c.
References sqlite3_backup::bDestLocked, sqlite3_backup::iDestSchema, sqlite3_backup::iNext, BtShared::inTransaction, sqlite3_backup::isAttached, sqlite3::mutex, sqlite3_backup::nPagecount, sqlite3_backup::nRemaining, Btree::pBt, sqlite3_backup::pDest, sqlite3_backup::pDestDb, sqlite3_backup::pSrc, sqlite3_backup::pSrcDb, sqlite3_backup::rc, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3BtreeBeginTrans(), sqlite3BtreeCommitPhaseOne(), sqlite3BtreeCommitPhaseTwo(), sqlite3BtreeEnter(), sqlite3BtreeGetMeta(), sqlite3BtreeGetPageSize(), sqlite3BtreeIsInReadTrans(), sqlite3BtreeLastPage(), sqlite3BtreeLeave(), sqlite3BtreeNewDb(), sqlite3BtreePager(), sqlite3BtreeSetVersion(), sqlite3BtreeUpdateMeta(), sqlite3PagerAcquire(), sqlite3PagerCommitPhaseOne(), sqlite3PagerFile(), sqlite3PagerGetJournalMode(), sqlite3PagerPagecount(), sqlite3PagerSync(), sqlite3PagerTruncateImage(), sqlite3PagerUnref(), sqlite3PagerWrite(), and sqlite3ResetAllSchemasOfConnection().
Referenced by sqlite3BtreeCopyFile().
                                                                               {
  int rc;
  int destMode; /* Destination journal mode */
  int pgszSrc = 0; /* Source page size */
  int pgszDest = 0; /* Destination page size */
#ifdef SQLITE_ENABLE_API_ARMOR
  if(p==0) return SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(p->pSrcDb->mutex);
  sqlite3BtreeEnter(p->pSrc);
  if(p->pDestDb){
    sqlite3_mutex_enter(p->pDestDb->mutex);
  }
  rc = p->rc;
  if(!isFatalError(rc)){
    Pager * const pSrcPager = sqlite3BtreePager(p->pSrc); /* Source pager */
    Pager * const pDestPager = sqlite3BtreePager(p->pDest); /* Dest pager */
    int ii; /* Iterator variable */
    int nSrcPage = -1; /* Size of source db in pages */
    int bCloseTrans = 0; /* True if src db requires unlocking */
    /* If the source pager is currently in a write-transaction, return
    ** SQLITE_BUSY immediately.
    */
    if(p->pDestDb && p->pSrc->pBt->inTransaction==
      TRANS_WRITE){
      rc = SQLITE_BUSY;
    }else{
      rc = SQLITE_OK;
    }
    /* Lock the destination database, if it is not locked already. */
    if(SQLITE_OK==rc && p->bDestLocked==0
     && SQLITE_OK==(rc = sqlite3BtreeBeginTrans(p->
      pDest, 2))
    ){
      p->bDestLocked = 1;
      sqlite3BtreeGetMeta(p->pDest, BTREE_SCHEMA_VERSION, &p->
      iDestSchema);
    }
    /* If there is no open read-transaction on the source database, open
    ** one now. If a transaction is opened here, then it will be closed
    ** before this function exits.
    */
    if(rc==SQLITE_OK && 0==sqlite3BtreeIsInReadTrans(p->
      pSrc)){
      rc = sqlite3BtreeBeginTrans(p->pSrc, 0);
      bCloseTrans = 1;
    }
    /* Do not allow backup if the destination database is in WAL mode
    ** and the page sizes are different between source and destination */
    pgszSrc = sqlite3BtreeGetPageSize(p->pSrc);
    pgszDest = sqlite3BtreeGetPageSize(p->pDest);
    destMode = sqlite3PagerGetJournalMode(
      sqlite3BtreePager(p->pDest));
    if(SQLITE_OK==rc && destMode==PAGER_JOURNALMODE_WAL && pgszSrc!=pgszDest
       ){
      rc = SQLITE_READONLY;
    }
  
    /* Now that there is a read-lock on the source database, query the
    ** source pager for the number of pages in the database.
    */
    nSrcPage = (int)sqlite3BtreeLastPage(p->pSrc);
    assert(nSrcPage>=0);
    for(ii=0; (nPage<0 || ii<nPage) && p->iNext<=(Pgno)nSrcPage && !rc; ii++){
      const Pgno iSrcPg = p->iNext; /* Source page number */
      if(iSrcPg!=PENDING_BYTE_PAGE(p->pSrc->pBt)){
        DbPage *pSrcPg; /* Source page object */
        rc = sqlite3PagerAcquire(pSrcPager, iSrcPg, &pSrcPg,
                                 PAGER_GET_READONLY);
        if(rc==SQLITE_OK){
          rc = backupOnePage(p, iSrcPg, sqlite3PagerGetData(pSrcPg), 0);
          sqlite3PagerUnref(pSrcPg);
        }
      }
      p->iNext++;
    }
    if(rc==SQLITE_OK){
      p->nPagecount = nSrcPage;
      p->nRemaining = nSrcPage+1-p->iNext;
      if(p->iNext>(Pgno)nSrcPage){
        rc = SQLITE_DONE;
      }else if(!p->isAttached){
        attachBackupObject(p);
      }
    }
  
    /* Update the schema version field in the destination database. This
    ** is to make sure that the schema-version really does change in
    ** the case where the source and destination databases have the
    ** same schema version.
    */
    if(rc==SQLITE_DONE){
      if(nSrcPage==0){
        rc = sqlite3BtreeNewDb(p->pDest);
        nSrcPage = 1;
      }
      if(rc==SQLITE_OK || rc==SQLITE_DONE){
        rc = sqlite3BtreeUpdateMeta(p->pDest,1,p->
      iDestSchema+1);
      }
      if(rc==SQLITE_OK){
        if(p->pDestDb){
          sqlite3ResetAllSchemasOfConnection(p->
      pDestDb);
        }
        if(destMode==PAGER_JOURNALMODE_WAL){
          rc = sqlite3BtreeSetVersion(p->pDest, 2);
        }
      }
      if(rc==SQLITE_OK){
        int nDestTruncate;
        /* Set nDestTruncate to the final number of pages in the destination
        ** database. The complication here is that the destination page
        ** size may be different to the source page size.
        **
        ** If the source page size is smaller than the destination page size,
        ** round up. In this case the call to sqlite3OsTruncate() below will
        ** fix the size of the file. However it is important to call
        ** sqlite3PagerTruncateImage() here so that any pages in the
        ** destination file that lie beyond the nDestTruncate page mark are
        ** journalled by PagerCommitPhaseOne() before they are destroyed
        ** by the file truncation.
        */
        assert(pgszSrc==sqlite3BtreeGetPageSize(p->pSrc));
        assert(pgszDest==sqlite3BtreeGetPageSize(p->
      pDest));
        if(pgszSrc<pgszDest){
          int ratio = pgszDest/pgszSrc;
          nDestTruncate = (nSrcPage+ratio-1)/ratio;
          if(nDestTruncate==(int)PENDING_BYTE_PAGE(p->pDest->
      pBt)){
            nDestTruncate--;
          }
        }else{
          nDestTruncate = nSrcPage * (pgszSrc/pgszDest);
        }
        assert(nDestTruncate>0);
        if(pgszSrc<pgszDest){
          /* If the source page-size is smaller than the destination page-size,
          ** two extra things may need to happen:
          **
          ** * The destination may need to be truncated, and
          **
          ** * Data stored on the pages immediately following the
          ** pending-byte page in the source database may need to be
          ** copied into the destination database.
          */
          const i64 iSize = (i64)pgszSrc * (i64)nSrcPage;
          sqlite3_file * const pFile = sqlite3PagerFile(pDestPager);
          Pgno iPg;
          int nDstPage;
          i64 iOff;
          i64 iEnd;
          assert(pFile);
          assert(nDestTruncate==0
              || (i64)nDestTruncate*(i64)pgszDest >= iSize || (
                nDestTruncate==(int)(PENDING_BYTE_PAGE(p->pDest->
      pBt)-1)
             && iSize>=PENDING_BYTE && iSize<=PENDING_BYTE+pgszDest
          ));
          /* This block ensures that all data required to recreate the original
          ** database has been stored in the journal for pDestPager and the
          ** journal synced to disk. So at this point we may safely modify
          ** the database file in any way, knowing that if a power failure
          ** occurs, the original database will be reconstructed from the
          ** journal file. */
          sqlite3PagerPagecount(pDestPager, &nDstPage);
          for(iPg=nDestTruncate; rc==SQLITE_OK && iPg<=(Pgno)nDstPage; iPg++){
            if(iPg!=PENDING_BYTE_PAGE(p->pDest->pBt)){
              DbPage *pPg;
              rc = sqlite3PagerGet(pDestPager, iPg, &pPg);
              if(rc==SQLITE_OK){
                rc = sqlite3PagerWrite(pPg);
                sqlite3PagerUnref(pPg);
              }
            }
          }
          if(rc==SQLITE_OK){
            rc = sqlite3PagerCommitPhaseOne(pDestPager, 0, 1);
          }
          /* Write the extra pages and truncate the database file as required */
          iEnd = MIN(PENDING_BYTE + pgszDest, iSize);
          for(
            iOff=PENDING_BYTE+pgszSrc;
            rc==SQLITE_OK && iOff<iEnd;
            iOff+=pgszSrc
          ){
            PgHdr *pSrcPg = 0;
            const Pgno iSrcPg = (Pgno)((iOff/pgszSrc)+1);
            rc = sqlite3PagerGet(pSrcPager, iSrcPg, &pSrcPg);
            if(rc==SQLITE_OK){
              u8 *zData = sqlite3PagerGetData(pSrcPg);
              rc = sqlite3OsWrite(pFile, zData, pgszSrc, iOff);
            }
            sqlite3PagerUnref(pSrcPg);
          }
          if(rc==SQLITE_OK){
            rc = backupTruncateFile(pFile, iSize);
          }
          /* Sync the database file to disk. */
          if(rc==SQLITE_OK){
            rc = sqlite3PagerSync(pDestPager, 0);
          }
        }else{
          sqlite3PagerTruncateImage(pDestPager, nDestTruncate);
          rc = sqlite3PagerCommitPhaseOne(pDestPager, 0, 0);
        }
    
        /* Finish committing the transaction to the destination database. */
        if(SQLITE_OK==rc
         && SQLITE_OK==(rc = sqlite3BtreeCommitPhaseTwo(p->
      pDest, 0))
        ){
          rc = SQLITE_DONE;
        }
      }
    }
  
    /* If bCloseTrans is true, then this function opened a read transaction
    ** on the source database. Close the read transaction here. There is
    ** no need to check the return values of the btree methods here, as
    ** "committing" a read-only transaction cannot fail.
    */
    if(bCloseTrans){
      TESTONLY(int rc2);
      TESTONLY(rc2 =) sqlite3BtreeCommitPhaseOne(p->pSrc, 0);
      TESTONLY(rc2 |=) sqlite3BtreeCommitPhaseTwo(p->pSrc, 0);
      assert(rc2==SQLITE_OK);
    }
  
    if(rc==SQLITE_IOERR_NOMEM){
      rc = SQLITE_NOMEM;
    }
    p->rc = rc;
  }
  if(p->pDestDb){
    sqlite3_mutex_leave(p->pDestDb->mutex);
  }
  sqlite3BtreeLeave(p->pSrc);
  sqlite3_mutex_leave(p->pSrcDb->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_blob (sqlite3_stmt * , int , const void * , int n, void(*)(void *))
Definition at line 70224 of file sqlite3.c.
Referenced by sqlite3_bind_value().
 {
  return bindText(pStmt, i, zData, nData, xDel, 0);
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_blob64 (sqlite3_stmt * , int , const void * , sqlite3_uint64 , void(*)(void *))
Definition at line 70233 of file sqlite3.c.
 {
  assert(xDel!=SQLITE_DYNAMIC);
  if(nData>0x7fffffff){
    return invokeValueDestructor(zData, xDel, 0);
  }else{
    return bindText(pStmt, i, zData, (int)nData, xDel, 0);
  }
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_double (sqlite3_stmt * , int , double)
Definition at line 70247 of file sqlite3.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave(), and sqlite3VdbeMemSetDouble().
Referenced by sqlite3_bind_value().
                                                                                            {
  int rc;
  Vdbe *p = (Vdbe *)pStmt;
  rc = vdbeUnbind(p, i);
  if(rc==SQLITE_OK){
    sqlite3VdbeMemSetDouble(&p->aVar[i-1], rValue);
    sqlite3_mutex_leave(p->db->mutex);
  }
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_int (sqlite3_stmt * , int , int)
Definition at line 70257 of file sqlite3.c.
References sqlite3_bind_int64().
                                                                                  {
  return sqlite3_bind_int64(p, i, (i64)iValue);
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_int64 (sqlite3_stmt * , int , sqlite3_int64)
Definition at line 70260 of file sqlite3.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave(), and sqlite3VdbeMemSetInt64().
Referenced by sqlite3_bind_int(), sqlite3_bind_value(), and sqlite3_blob_open().
                                                                                                 {
  int rc;
  Vdbe *p = (Vdbe *)pStmt;
  rc = vdbeUnbind(p, i);
  if(rc==SQLITE_OK){
    sqlite3VdbeMemSetInt64(&p->aVar[i-1], iValue);
    sqlite3_mutex_leave(p->db->mutex);
  }
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_null (sqlite3_stmt * , int)
Definition at line 70270 of file sqlite3.c.
References Vdbe::db, sqlite3::mutex, and sqlite3_mutex_leave().
Referenced by sqlite3_bind_value().
                                                                           {
  int rc;
  Vdbe *p = (Vdbe*)pStmt;
  rc = vdbeUnbind(p, i);
  if(rc==SQLITE_OK){
    sqlite3_mutex_leave(p->db->mutex);
  }
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_parameter_count (sqlite3_stmt *)
Definition at line 70361 of file sqlite3.c.
References Vdbe::nVar.
                                                                               {
  Vdbe *p = (Vdbe*)pStmt;
  return p ? p->nVar : 0;
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_parameter_index (sqlite3_stmt * , const char * zName)
Definition at line 70400 of file sqlite3.c.
References sqlite3Strlen30(), and sqlite3VdbeParameterIndex().
                                                                                                  {
  return sqlite3VdbeParameterIndex((Vdbe*)pStmt, zName,
      sqlite3Strlen30(zName));
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_bind_parameter_name (sqlite3_stmt * , int)
Definition at line 70372 of file sqlite3.c.
References Vdbe::azVar, and Vdbe::nzVar.
                                                                                             {
  Vdbe *p = (Vdbe*)pStmt;
  if(p==0 || i<1 || i>p->nzVar){
    return 0;
  }
  return p->azVar[i-1];
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_text (sqlite3_stmt * , int , const char * , int , void(*)(void *))
Definition at line 70279 of file sqlite3.c.
 {
  return bindText(pStmt, i, zData, nData, xDel, SQLITE_UTF8);
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_text16 (sqlite3_stmt * , int , const void * , int , void(*)(void *))
Definition at line 70305 of file sqlite3.c.
 {
  return bindText(pStmt, i, zData, nData, xDel, SQLITE_UTF16NATIVE);
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_text64 (sqlite3_stmt * , int , const char * , sqlite3_uint64 , void(*)(void *) , unsigned char encoding)
Definition at line 70288 of file sqlite3.c.
 {
  assert(xDel!=SQLITE_DYNAMIC);
  if(nData>0x7fffffff){
    return invokeValueDestructor(zData, xDel, 0);
  }else{
    if(enc==SQLITE_UTF16) enc = SQLITE_UTF16NATIVE;
    return bindText(pStmt, i, zData, (int)nData, xDel, enc);
  }
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_value (sqlite3_stmt * , int , const sqlite3_value *)
Definition at line 70315 of file sqlite3.c.
References sqlite3_value::enc, sqlite3_value::flags, sqlite3_value::MemValue::i, sqlite3_value::n, sqlite3_value::MemValue::nZero, sqlite3_value::MemValue::r, sqlite3_bind_blob(), sqlite3_bind_double(), sqlite3_bind_int64(), sqlite3_bind_null(), sqlite3_bind_zeroblob(), sqlite3_value_type(), and sqlite3_value::z.
                                                                                                         {
  int rc;
  switch(sqlite3_value_type((sqlite3_value*)pValue)){
    case SQLITE_INTEGER: {
      rc = sqlite3_bind_int64(pStmt, i, pValue->u.i);
      break;
    }
    case SQLITE_FLOAT: {
      rc = sqlite3_bind_double(pStmt, i, pValue->u.r);
      break;
    }
    case SQLITE_BLOB: {
      if(pValue->flags & MEM_Zero){
        rc = sqlite3_bind_zeroblob(pStmt, i, pValue->u.nZero);
      }else{
        rc = sqlite3_bind_blob(pStmt, i, pValue->z, pValue->n,
      SQLITE_TRANSIENT);
      }
      break;
    }
    case SQLITE_TEXT: {
      rc = bindText(pStmt,i, pValue->z, pValue->n, SQLITE_TRANSIENT,
                              pValue->enc);
      break;
    }
    default: {
      rc = sqlite3_bind_null(pStmt, i);
      break;
    }
  }
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_bind_zeroblob (sqlite3_stmt * , int , int n)
Definition at line 70346 of file sqlite3.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave(), and sqlite3VdbeMemSetZeroBlob().
Referenced by sqlite3_bind_value().
                                                                                      {
  int rc;
  Vdbe *p = (Vdbe *)pStmt;
  rc = vdbeUnbind(p, i);
  if(rc==SQLITE_OK){
    sqlite3VdbeMemSetZeroBlob(&p->aVar[i-1], n);
    sqlite3_mutex_leave(p->db->mutex);
  }
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_blob_bytes (sqlite3_blob *)
Definition at line 77883 of file sqlite3.c.
References Incrblob::nByte, and Incrblob::pStmt.
                                                                     {
  Incrblob *p = (Incrblob *)pBlob;
  return (p && p->pStmt) ? p->nByte : 0;
}
SQLITE_API int SQLITE_STDCALL sqlite3_blob_close (sqlite3_blob *)
Definition at line 77797 of file sqlite3.c.
References Incrblob::db, sqlite3::mutex, Incrblob::pStmt, sqlite3_finalize(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3DbFree().
                                                                     {
  Incrblob *p = (Incrblob *)pBlob;
  int rc;
  sqlite3 *db;
  if(p){
    db = p->db;
    sqlite3_mutex_enter(db->mutex);
    rc = sqlite3_finalize(p->pStmt);
    sqlite3DbFree(db, p);
    sqlite3_mutex_leave(db->mutex);
  }else{
    rc = SQLITE_OK;
  }
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_blob_open (sqlite3 * , const char * zDb, const char * zTable, const char * zColumn, sqlite3_int64 iRow, int flags, sqlite3_blob ** ppBlob)
Definition at line 77560 of file sqlite3.c.
References Table::aCol, Index::aiColumn, Parse::db, Incrblob::db, sqlite3::flags, Incrblob::flags, Incrblob::iCol, FKey::sColMap::iFrom, Schema::iGeneration, sqlite3::mallocFailed, sqlite3::mutex, Table::nCol, FKey::nCol, Index::nKeyCol, Parse::nMem, Parse::nTab, Parse::nVar, Table::pFKey, Table::pIndex, Index::pNext, FKey::pNextFrom, Table::pSchema, Table::pSelect, Incrblob::pStmt, Schema::schema_cookie, sqlite3_bind_int64(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_stricmp(), sqlite3ApiExit(), sqlite3BtreeEnterAll(), sqlite3BtreeLeaveAll(), sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3ErrorMsg(), sqlite3ErrorWithMsg(), sqlite3LocateTable(), sqlite3MPrintf(), sqlite3ParserReset(), sqlite3SchemaToIndex(), sqlite3VdbeAddOp4Int(), sqlite3VdbeAddOpList(), sqlite3VdbeChangeP1(), sqlite3VdbeChangeP2(), sqlite3VdbeChangeP3(), sqlite3VdbeChangeP4(), sqlite3VdbeChangeP5(), sqlite3VdbeChangeToNoop(), sqlite3VdbeCreate(), sqlite3VdbeFinalize(), sqlite3VdbeMakeReady(), sqlite3VdbeUsesBtree(), Table::tnum, Parse::zErrMsg, Column::zName, and Table::zName.
 {
  int nAttempt = 0;
  int iCol; /* Index of zColumn in row-record */
  /* This VDBE program seeks a btree cursor to the identified
  ** db/table/row entry. The reason for using a vdbe program instead
  ** of writing code to use the b-tree layer directly is that the
  ** vdbe program will take advantage of the various transaction,
  ** locking and error handling infrastructure built into the vdbe.
  **
  ** After seeking the cursor, the vdbe executes an OP_ResultRow.
  ** Code external to the Vdbe then "borrows" the b-tree cursor and
  ** uses it to implement the blob_read(), blob_write() and
  ** blob_bytes() functions.
  **
  ** The sqlite3_blob_close() function finalizes the vdbe program,
  ** which closes the b-tree cursor and (possibly) commits the
  ** transaction.
  */
  static const int iLn = VDBE_OFFSET_LINENO(4);
  static const VdbeOpList openBlob[] = {
    /* {OP_Transaction, 0, 0, 0}, // 0: Inserted separately */
    {OP_TableLock, 0, 0, 0}, /* 1: Acquire a read or write lock */
    /* One of the following two instructions is replaced by an OP_Noop. */
    {OP_OpenRead, 0, 0, 0}, /* 2: Open cursor 0 for reading */
    {OP_OpenWrite, 0, 0, 0}, /* 3: Open cursor 0 for read/write */
    {OP_Variable, 1, 1, 1}, /* 4: Push the rowid to the stack */
    {OP_NotExists, 0, 10, 1}, /* 5: Seek the cursor */
    {OP_Column, 0, 0, 1}, /* 6 */
    {OP_ResultRow, 1, 0, 0}, /* 7 */
    {OP_Goto, 0, 4, 0}, /* 8 */
    {OP_Close, 0, 0, 0}, /* 9 */
    {OP_Halt, 0, 0, 0}, /* 10 */
  };
  int rc = SQLITE_OK;
  char *zErr = 0;
  Table *pTab;
  Parse *pParse = 0;
  Incrblob *pBlob = 0;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(ppBlob==0){
    return SQLITE_MISUSE_BKPT;
  }
#endif
  *ppBlob = 0;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || zTable==0){
    return SQLITE_MISUSE_BKPT;
  }
#endif
  flags = !!flags; /* flags = (flags ? 1 : 0); */
  sqlite3_mutex_enter(db->mutex);
  pBlob = (Incrblob *)sqlite3DbMallocZero(db, sizeof(
      Incrblob));
  if(!pBlob) goto blob_open_out;
  pParse = sqlite3StackAllocRaw(db, sizeof(*pParse));
  if(!pParse) goto blob_open_out;
  do {
    memset(pParse, 0, sizeof(Parse));
    pParse->db = db;
    sqlite3DbFree(db, zErr);
    zErr = 0;
    sqlite3BtreeEnterAll(db);
    pTab = sqlite3LocateTable(pParse, 0, zTable, zDb);
    if(pTab && IsVirtual(pTab)){
      pTab = 0;
      sqlite3ErrorMsg(pParse, "cannot open virtual table: %s", zTable);
    }
    if(pTab && !HasRowid(pTab)){
      pTab = 0;
      sqlite3ErrorMsg(pParse, "cannot open table without rowid: %s", zTable);
    }
#ifndef SQLITE_OMIT_VIEW
    if(pTab && pTab->pSelect){
      pTab = 0;
      sqlite3ErrorMsg(pParse, "cannot open view: %s", zTable);
    }
#endif
    if(!pTab){
      if(pParse->zErrMsg){
        sqlite3DbFree(db, zErr);
        zErr = pParse->zErrMsg;
        pParse->zErrMsg = 0;
      }
      rc = SQLITE_ERROR;
      sqlite3BtreeLeaveAll(db);
      goto blob_open_out;
    }
    /* Now search pTab for the exact column. */
    for(iCol=0; iCol<pTab->nCol; iCol++) {
      if(sqlite3StrICmp(pTab->aCol[iCol].zName, zColumn)==0){
        break;
      }
    }
    if(iCol==pTab->nCol){
      sqlite3DbFree(db, zErr);
      zErr = sqlite3MPrintf(db, "no such column: \"%s\"", zColumn);
      rc = SQLITE_ERROR;
      sqlite3BtreeLeaveAll(db);
      goto blob_open_out;
    }
    /* If the value is being opened for writing, check that the
    ** column is not indexed, and that it is not part of a foreign key.
    ** It is against the rules to open a column to which either of these
    ** descriptions applies for writing. */
    if(flags){
      const char *zFault = 0;
      Index *pIdx;
#ifndef SQLITE_OMIT_FOREIGN_KEY
      if(db->flags&SQLITE_ForeignKeys){
        /* Check that the column is not part of an FK child key definition. It
        ** is not necessary to check if it is part of a parent key, as parent
        ** key columns must be indexed. The check below will pick up this
        ** case. */
        FKey *pFKey;
        for(pFKey=pTab->pFKey; pFKey; pFKey=pFKey->pNextFrom){
          int j;
          for(j=0; j<pFKey->nCol; j++){
            if(pFKey->aCol[j].iFrom==iCol){
              zFault = "foreign key";
            }
          }
        }
      }
#endif
      for(pIdx=pTab->pIndex; pIdx; pIdx=pIdx->pNext){
        int j;
        for(j=0; j<pIdx->nKeyCol; j++){
          if(pIdx->aiColumn[j]==iCol){
            zFault = "indexed";
          }
        }
      }
      if(zFault){
        sqlite3DbFree(db, zErr);
        zErr = sqlite3MPrintf(db, "cannot open %s column for writing", zFault);
        rc = SQLITE_ERROR;
        sqlite3BtreeLeaveAll(db);
        goto blob_open_out;
      }
    }
    pBlob->pStmt = (sqlite3_stmt *)sqlite3VdbeCreate(pParse);
    assert(pBlob->pStmt || db->mallocFailed);
    if(pBlob->pStmt){
      Vdbe *v = (Vdbe *)pBlob->pStmt;
      int iDb = sqlite3SchemaToIndex(db, pTab->pSchema);
      sqlite3VdbeAddOp4Int(v, OP_Transaction, iDb, flags,
                           pTab->pSchema->schema_cookie,
                           pTab->pSchema->iGeneration);
      sqlite3VdbeChangeP5(v, 1);
      sqlite3VdbeAddOpList(v, ArraySize(openBlob), openBlob, iLn);
      /* Make sure a mutex is held on the table to be accessed */
      sqlite3VdbeUsesBtree(v, iDb);
      /* Configure the OP_TableLock instruction */
#ifdef SQLITE_OMIT_SHARED_CACHE
      sqlite3VdbeChangeToNoop(v, 1);
#else
      sqlite3VdbeChangeP1(v, 1, iDb);
      sqlite3VdbeChangeP2(v, 1, pTab->tnum);
      sqlite3VdbeChangeP3(v, 1, flags);
      sqlite3VdbeChangeP4(v, 1, pTab->zName,
      P4_TRANSIENT);
#endif
      /* Remove either the OP_OpenWrite or OpenRead. Set the P2
      ** parameter of the other to pTab->tnum. */
      sqlite3VdbeChangeToNoop(v, 3 - flags);
      sqlite3VdbeChangeP2(v, 2 + flags, pTab->tnum);
      sqlite3VdbeChangeP3(v, 2 + flags, iDb);
      /* Configure the number of columns. Configure the cursor to
      ** think that the table has one more column than it really
      ** does. An OP_Column to retrieve this imaginary column will
      ** always return an SQL NULL. This is useful because it means
      ** we can invoke OP_Column to fill in the vdbe cursors type
      ** and offset cache without causing any IO.
      */
      sqlite3VdbeChangeP4(v, 2+flags, SQLITE_INT_TO_PTR(pTab->
      nCol+1),P4_INT32);
      sqlite3VdbeChangeP2(v, 6, pTab->nCol);
      if(!db->mallocFailed){
        pParse->nVar = 1;
        pParse->nMem = 1;
        pParse->nTab = 1;
        sqlite3VdbeMakeReady(v, pParse);
      }
    }
   
    pBlob->flags = flags;
    pBlob->iCol = iCol;
    pBlob->db = db;
    sqlite3BtreeLeaveAll(db);
    if(db->mallocFailed){
      goto blob_open_out;
    }
    sqlite3_bind_int64(pBlob->pStmt, 1, iRow);
    rc = blobSeekToRow(pBlob, iRow, &zErr);
  } while((++nAttempt)<SQLITE_MAX_SCHEMA_RETRY && rc==
      SQLITE_SCHEMA);
blob_open_out:
  if(rc==SQLITE_OK && db->mallocFailed==0){
    *ppBlob = (sqlite3_blob *)pBlob;
  }else{
    if(pBlob && pBlob->pStmt) sqlite3VdbeFinalize((
      Vdbe *)pBlob->pStmt);
    sqlite3DbFree(db, pBlob);
  }
  sqlite3ErrorWithMsg(db, rc, (zErr ? "%s" : 0), zErr);
  sqlite3DbFree(db, zErr);
  sqlite3ParserReset(pParse);
  sqlite3StackFree(db, pParse);
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_blob_read (sqlite3_blob * , void * Z, int N, int iOffset)
Definition at line 77866 of file sqlite3.c.
References sqlite3BtreeData().
                                                                                                 {
  return blobReadWrite(pBlob, z, n, iOffset, sqlite3BtreeData);
}
SQLITE_API SQLITE_EXPERIMENTAL int SQLITE_STDCALL sqlite3_blob_reopen (sqlite3_blob * , sqlite3_int64)
Definition at line 77898 of file sqlite3.c.
References Incrblob::db, sqlite3::mutex, Incrblob::pStmt, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3DbFree(), and sqlite3ErrorWithMsg().
                                                                                          {
  int rc;
  Incrblob *p = (Incrblob *)pBlob;
  sqlite3 *db;
  if(p==0) return SQLITE_MISUSE_BKPT;
  db = p->db;
  sqlite3_mutex_enter(db->mutex);
  if(p->pStmt==0){
    /* If there is no statement handle, then the blob-handle has
    ** already been invalidated. Return SQLITE_ABORT in this case.
    */
    rc = SQLITE_ABORT;
  }else{
    char *zErr;
    rc = blobSeekToRow(p, iRow, &zErr);
    if(rc!=SQLITE_OK){
      sqlite3ErrorWithMsg(db, rc, (zErr ? "%s" : 0), zErr);
      sqlite3DbFree(db, zErr);
    }
    assert(rc!=SQLITE_SCHEMA);
  }
  rc = sqlite3ApiExit(db, rc);
  assert(rc==SQLITE_OK || p->pStmt==0);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_blob_write (sqlite3_blob * , const void * z, int n, int iOffset)
Definition at line 77873 of file sqlite3.c.
References sqlite3BtreePutData().
                                                                                                        {
  return blobReadWrite(pBlob, (void *)z, n, iOffset, sqlite3BtreePutData);
}
SQLITE_API int SQLITE_STDCALL sqlite3_busy_handler (sqlite3 * , int(*)(void *, int) , void *)
Definition at line 129415 of file sqlite3.c.
References sqlite3::busyHandler, sqlite3::busyTimeout, sqlite3::mutex, BusyHandler::nBusy, BusyHandler::pArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and BusyHandler::xFunc.
Referenced by sqlite3_busy_timeout().
 {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  db->busyHandler.xFunc = xBusy;
  db->busyHandler.pArg = pArg;
  db->busyHandler.nBusy = 0;
  db->busyTimeout = 0;
  sqlite3_mutex_leave(db->mutex);
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_busy_timeout (sqlite3 * , int ms)
Definition at line 129469 of file sqlite3.c.
References sqlite3::busyTimeout, and sqlite3_busy_handler().
Referenced by sqlite3Pragma().
                                                                       {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return SQLITE_MISUSE_BKPT;
#endif
  if(ms>0){
    sqlite3_busy_handler(db, sqliteDefaultBusyCallback, (void*)db);
    db->busyTimeout = ms;
  }else{
    sqlite3_busy_handler(db, 0, 0);
  }
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_cancel_auto_extension (void(*)(void) xEntryPoint)
Definition at line 103056 of file sqlite3.c.
References sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3MutexAlloc().
                                                                                {
#if SQLITE_THREADSAFE
  sqlite3_mutex *mutex = sqlite3MutexAlloc(
      SQLITE_MUTEX_STATIC_MASTER);
#endif
  int i;
  int n = 0;
  wsdAutoextInit;
  sqlite3_mutex_enter(mutex);
  for(i=wsdAutoext.nExt-1; i>=0; i--){
    if(wsdAutoext.aExt[i]==xInit){
      wsdAutoext.nExt--;
      wsdAutoext.aExt[i] = wsdAutoext.aExt[wsdAutoext.nExt];
      n++;
      break;
    }
  }
  sqlite3_mutex_leave(mutex);
  return n;
}
SQLITE_API int SQLITE_STDCALL sqlite3_changes (sqlite3 *)
Definition at line 128852 of file sqlite3.c.
References sqlite3::nChange.
                                                          {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  return db->nChange;
}
SQLITE_API int SQLITE_STDCALL sqlite3_clear_bindings (sqlite3_stmt *)
Definition at line 69116 of file sqlite3.c.
References Vdbe::aVar, Vdbe::db, Vdbe::expired, Vdbe::expmask, sqlite3_value::flags, Vdbe::isPrepareV2, sqlite3::mutex, Vdbe::nVar, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3VdbeMemRelease().
                                                                         {
  int i;
  int rc = SQLITE_OK;
  Vdbe *p = (Vdbe*)pStmt;
#if SQLITE_THREADSAFE
  sqlite3_mutex *mutex = ((Vdbe*)pStmt)->db->mutex;
#endif
  sqlite3_mutex_enter(mutex);
  for(i=0; i<p->nVar; i++){
    sqlite3VdbeMemRelease(&p->aVar[i]);
    p->aVar[i].flags = MEM_Null;
  }
  if(p->isPrepareV2 && p->expmask){
    p->expired = 1;
  }
  sqlite3_mutex_leave(mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_close (sqlite3 *)
Definition at line 129007 of file sqlite3.c.
{ return sqlite3Close(db,0); }
SQLITE_API int SQLITE_STDCALL sqlite3_close_v2 (sqlite3 *)
Definition at line 129008 of file sqlite3.c.
{ return sqlite3Close(db,1); }
SQLITE_API int SQLITE_STDCALL sqlite3_collation_needed (sqlite3 * , void * , void(*)(void *, sqlite3 *, int eTextRep, const char *))
Definition at line 131035 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pCollNeededArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3::xCollNeeded, and sqlite3::xCollNeeded16.
 {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  db->xCollNeeded = xCollNeeded;
  db->xCollNeeded16 = 0;
  db->pCollNeededArg = pCollNeededArg;
  sqlite3_mutex_leave(db->mutex);
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_collation_needed16 (sqlite3 * , void * , void(*)(void *, sqlite3 *, int eTextRep, const void *))
Definition at line 131056 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pCollNeededArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3::xCollNeeded, and sqlite3::xCollNeeded16.
 {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  db->xCollNeeded = 0;
  db->xCollNeeded16 = xCollNeeded16;
  db->pCollNeededArg = pCollNeededArg;
  sqlite3_mutex_leave(db->mutex);
  return SQLITE_OK;
}
SQLITE_API const void* SQLITE_STDCALL sqlite3_column_blob (sqlite3_stmt * , int iCol)
Definition at line 69923 of file sqlite3.c.
References sqlite3_value_blob().
                                                                                     {
  const void *val;
  val = sqlite3_value_blob(columnMem(pStmt,i));
  /* Even though there is no encoding conversion, value_blob() might
  ** need to call malloc() to expand the result of a zeroblob()
  ** expression.
  */
  columnMallocFailure(pStmt);
  return val;
}
SQLITE_API int SQLITE_STDCALL sqlite3_column_bytes (sqlite3_stmt * , int iCol)
Definition at line 69933 of file sqlite3.c.
References sqlite3_value_bytes().
                                                                              {
  int val = sqlite3_value_bytes(columnMem(pStmt,i));
  columnMallocFailure(pStmt);
  return val;
}
SQLITE_API int SQLITE_STDCALL sqlite3_column_bytes16 (sqlite3_stmt * , int iCol)
Definition at line 69938 of file sqlite3.c.
References sqlite3_value_bytes16().
                                                                                {
  int val = sqlite3_value_bytes16(columnMem(pStmt,i));
  columnMallocFailure(pStmt);
  return val;
}
SQLITE_API int SQLITE_STDCALL sqlite3_column_count (sqlite3_stmt * pStmt)
Definition at line 69812 of file sqlite3.c.
References Vdbe::nResColumn.
Referenced by sqlite3_exec().
                                                                       {
  Vdbe *pVm = (Vdbe *)pStmt;
  return pVm ? pVm->nResColumn : 0;
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_column_database_name (sqlite3_stmt * , int)
SQLITE_API const void* SQLITE_STDCALL sqlite3_column_database_name16 (sqlite3_stmt * , int)
SQLITE_API const char* SQLITE_STDCALL sqlite3_column_decltype (sqlite3_stmt * , int)
Definition at line 70068 of file sqlite3.c.
                                                                                         {
  return columnName(
      pStmt, N, (const void*(*)(Mem*))sqlite3_value_text,
      COLNAME_DECLTYPE);
}
SQLITE_API const void* SQLITE_STDCALL sqlite3_column_decltype16 (sqlite3_stmt * , int)
Definition at line 70073 of file sqlite3.c.
References sqlite3_value_text16().
                                                                                           {
  return columnName(
      pStmt, N, (const void*(*)(Mem*))sqlite3_value_text16,
      COLNAME_DECLTYPE);
}
SQLITE_API double SQLITE_STDCALL sqlite3_column_double (sqlite3_stmt * , int iCol)
Definition at line 69943 of file sqlite3.c.
References sqlite3_value_double().
                                                                                  {
  double val = sqlite3_value_double(columnMem(pStmt,i));
  columnMallocFailure(pStmt);
  return val;
}
SQLITE_API int SQLITE_STDCALL sqlite3_column_int (sqlite3_stmt * , int iCol)
Definition at line 69948 of file sqlite3.c.
References sqlite3_value_int().
                                                                            {
  int val = sqlite3_value_int(columnMem(pStmt,i));
  columnMallocFailure(pStmt);
  return val;
}
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_column_int64 (sqlite3_stmt * , int iCol)
Definition at line 69953 of file sqlite3.c.
References sqlite3_value_int64().
                                                                                       {
  sqlite_int64 val = sqlite3_value_int64(columnMem(pStmt,i));
  columnMallocFailure(pStmt);
  return val;
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_column_name (sqlite3_stmt * , int N)
Definition at line 70043 of file sqlite3.c.
Referenced by sqlite3_exec().
                                                                                     {
  return columnName(
      pStmt, N, (const void*(*)(Mem*))sqlite3_value_text,
      COLNAME_NAME);
}
SQLITE_API const void* SQLITE_STDCALL sqlite3_column_name16 (sqlite3_stmt * , int N)
Definition at line 70048 of file sqlite3.c.
References sqlite3_value_text16().
                                                                                       {
  return columnName(
      pStmt, N, (const void*(*)(Mem*))sqlite3_value_text16,
      COLNAME_NAME);
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_column_origin_name (sqlite3_stmt * , int)
SQLITE_API const void* SQLITE_STDCALL sqlite3_column_origin_name16 (sqlite3_stmt * , int)
SQLITE_API const char* SQLITE_STDCALL sqlite3_column_table_name (sqlite3_stmt * , int)
SQLITE_API const void* SQLITE_STDCALL sqlite3_column_table_name16 (sqlite3_stmt * , int)
SQLITE_API const unsigned char* SQLITE_STDCALL sqlite3_column_text (sqlite3_stmt * , int iCol)
Definition at line 69958 of file sqlite3.c.
References sqlite3_value_text().
Referenced by sqlite3_exec().
                                                                                              {
  const unsigned char *val = sqlite3_value_text(columnMem(pStmt,i));
  columnMallocFailure(pStmt);
  return val;
}
SQLITE_API const void* SQLITE_STDCALL sqlite3_column_text16 (sqlite3_stmt * , int iCol)
Definition at line 69973 of file sqlite3.c.
References sqlite3_value_text16().
                                                                                       {
  const void *val = sqlite3_value_text16(columnMem(pStmt,i));
  columnMallocFailure(pStmt);
  return val;
}
SQLITE_API int SQLITE_STDCALL sqlite3_column_type (sqlite3_stmt * , int iCol)
Definition at line 69979 of file sqlite3.c.
References sqlite3_value_type().
Referenced by sqlite3_exec().
                                                                             {
  int iType = sqlite3_value_type(columnMem(pStmt,i));
  columnMallocFailure(pStmt);
  return iType;
}
SQLITE_API sqlite3_value* SQLITE_STDCALL sqlite3_column_value (sqlite3_stmt * , int iCol)
Definition at line 69963 of file sqlite3.c.
References sqlite3_value::flags.
                                                                                         {
  Mem *pOut = columnMem(pStmt, i);
  if(pOut->flags&MEM_Static){
    pOut->flags &= ~MEM_Static;
    pOut->flags |= MEM_Ephem;
  }
  columnMallocFailure(pStmt);
  return (sqlite3_value *)pOut;
}
SQLITE_API void* SQLITE_STDCALL sqlite3_commit_hook (sqlite3 * , int(*)(void *) , void *)
Definition at line 129782 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pCommitArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3::xCommitCallback.
 {
  void *pOld;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  pOld = db->pCommitArg;
  db->xCommitCallback = xCallback;
  db->pCommitArg = pArg;
  sqlite3_mutex_leave(db->mutex);
  return pOld;
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_compileoption_get (int N)
Definition at line 14472 of file sqlite3.c.
Referenced by sqlite3Pragma().
                                                                      {
  if(N>=0 && N<ArraySize(azCompileOpt)){
    return azCompileOpt[N];
  }
  return 0;
}
SQLITE_API int SQLITE_STDCALL sqlite3_compileoption_used (const char * zOptName)
Definition at line 14444 of file sqlite3.c.
References sqlite3_strnicmp(), sqlite3IsIdChar(), and sqlite3Strlen30().
                                                                              {
  int i, n;
#if SQLITE_ENABLE_API_ARMOR
  if(zOptName==0){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  if(sqlite3StrNICmp(zOptName, "SQLITE_", 7)==0) zOptName += 7;
  n = sqlite3Strlen30(zOptName);
  /* Since ArraySize(azCompileOpt) is normally in single digits, a
  ** linear search is adequate. No need for a binary search. */
  for(i=0; i<ArraySize(azCompileOpt); i++){
    if(sqlite3StrNICmp(zOptName, azCompileOpt[i], n)==0
     && sqlite3IsIdChar((unsigned char)azCompileOpt[i][n])==0
    ){
      return 1;
    }
  }
  return 0;
}
SQLITE_API int SQLITE_STDCALL sqlite3_complete (const char * sql)
Definition at line 127718 of file sqlite3.c.
References sqlite3_strnicmp().
Referenced by sqlite3_complete16().
                                                                {
  u8 state = 0; /* Current state, using numbers defined in header comment */
  u8 token; /* Value of the next token */
#ifndef SQLITE_OMIT_TRIGGER
  /* A complex statement machine used to detect the end of a CREATE TRIGGER
  ** statement. This is the normal case.
  */
  static const u8 trans[8][8] = {
                     /* Token: */
     /* State: ** SEMI WS OTHER EXPLAIN CREATE TEMP TRIGGER END */
     /* 0 INVALID: */ { 1, 0, 2, 3, 4, 2, 2, 2, },
     /* 1 START: */ { 1, 1, 2, 3, 4, 2, 2, 2, },
     /* 2 NORMAL: */ { 1, 2, 2, 2, 2, 2, 2, 2, },
     /* 3 EXPLAIN: */ { 1, 3, 3, 2, 4, 2, 2, 2, },
     /* 4 CREATE: */ { 1, 4, 2, 2, 2, 4, 5, 2, },
     /* 5 TRIGGER: */ { 6, 5, 5, 5, 5, 5, 5, 5, },
     /* 6 SEMI: */ { 6, 6, 5, 5, 5, 5, 5, 7, },
     /* 7 END: */ { 1, 7, 5, 5, 5, 5, 5, 5, },
  };
#else
  /* If triggers are not supported by this compile then the statement machine
  ** used to detect the end of a statement is much simpler
  */
  static const u8 trans[3][3] = {
                     /* Token: */
     /* State: ** SEMI WS OTHER */
     /* 0 INVALID: */ { 1, 0, 2, },
     /* 1 START: */ { 1, 1, 2, },
     /* 2 NORMAL: */ { 1, 2, 2, },
  };
#endif /* SQLITE_OMIT_TRIGGER */
#ifdef SQLITE_ENABLE_API_ARMOR
  if(zSql==0){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  while(*zSql){
    switch(*zSql){
      case ';': { /* A semicolon */
        token = tkSEMI;
        break;
      }
      case ' ':
      case '\r':
      case '\t':
      case '\n':
      case '\f': { /* White space is ignored */
        token = tkWS;
        break;
      }
      case '/': { /* C-style comments */
        if(zSql[1]!='*'){
          token = tkOTHER;
          break;
        }
        zSql += 2;
        while(zSql[0] && (zSql[0]!='*' || zSql[1]!='/')){ zSql++; }
        if(zSql[0]==0) return 0;
        zSql++;
        token = tkWS;
        break;
      }
      case '-': { /* SQL-style comments from "--" to end of line */
        if(zSql[1]!='-'){
          token = tkOTHER;
          break;
        }
        while(*zSql && *zSql!='\n'){ zSql++; }
        if(*zSql==0) return state==1;
        token = tkWS;
        break;
      }
      case '[': { /* Microsoft-style identifiers in [...] */
        zSql++;
        while(*zSql && *zSql!=']'){ zSql++; }
        if(*zSql==0) return 0;
        token = tkOTHER;
        break;
      }
      case '`': /* Grave-accent quoted symbols used by MySQL */
      case '"': /* single- and double-quoted strings */
      case '\'': {
        int c = *zSql;
        zSql++;
        while(*zSql && *zSql!=c){ zSql++; }
        if(*zSql==0) return 0;
        token = tkOTHER;
        break;
      }
      default: {
#ifdef SQLITE_EBCDIC
        unsigned char c;
#endif
        if(IdChar((u8)*zSql)){
          /* Keywords and unquoted identifiers */
          int nId;
          for(nId=1; IdChar(zSql[nId]); nId++){}
#ifdef SQLITE_OMIT_TRIGGER
          token = tkOTHER;
#else
          switch(*zSql){
            case 'c': case 'C': {
              if(nId==6 && sqlite3StrNICmp(zSql, "create", 6)==0){
                token = tkCREATE;
              }else{
                token = tkOTHER;
              }
              break;
            }
            case 't': case 'T': {
              if(nId==7 && sqlite3StrNICmp(zSql, "trigger", 7)==0){
                token = tkTRIGGER;
              }else if(nId==4 && sqlite3StrNICmp(zSql, "temp", 4)==0){
                token = tkTEMP;
              }else if(nId==9 && sqlite3StrNICmp(zSql, "temporary", 9)==0){
                token = tkTEMP;
              }else{
                token = tkOTHER;
              }
              break;
            }
            case 'e': case 'E': {
              if(nId==3 && sqlite3StrNICmp(zSql, "end", 3)==0){
                token = tkEND;
              }else
#ifndef SQLITE_OMIT_EXPLAIN
              if(nId==7 && sqlite3StrNICmp(zSql, "explain", 7)==0){
                token = tkEXPLAIN;
              }else
#endif
              {
                token = tkOTHER;
              }
              break;
            }
            default: {
              token = tkOTHER;
              break;
            }
          }
#endif /* SQLITE_OMIT_TRIGGER */
          zSql += nId-1;
        }else{
          /* Operators and special symbols */
          token = tkOTHER;
        }
        break;
      }
    }
    state = trans[state][token];
    zSql++;
  }
  return state==1;
}
SQLITE_API int SQLITE_STDCALL sqlite3_complete16 (const void * sql)
Definition at line 127883 of file sqlite3.c.
References sqlite3_complete(), sqlite3_initialize(), sqlite3ApiExit(), sqlite3ValueFree(), sqlite3ValueNew(), and sqlite3ValueSetStr().
                                                                  {
  sqlite3_value *pVal;
  char const *zSql8;
  int rc;
#ifndef SQLITE_OMIT_AUTOINIT
  rc = sqlite3_initialize();
  if(rc) return rc;
#endif
  pVal = sqlite3ValueNew(0);
  sqlite3ValueSetStr(pVal, -1, zSql, SQLITE_UTF16NATIVE,
      SQLITE_STATIC);
  zSql8 = sqlite3ValueText(pVal, SQLITE_UTF8);
  if(zSql8){
    rc = sqlite3_complete(zSql8);
  }else{
    rc = SQLITE_NOMEM;
  }
  sqlite3ValueFree(pVal);
  return sqlite3ApiExit(0, rc);
}
SQLITE_API int SQLITE_CDECL sqlite3_config (int , ...)
Definition at line 128326 of file sqlite3.c.
References Sqlite3Config::bCoreMutex, Sqlite3Config::bFullMutex, Sqlite3Config::isInit, Sqlite3Config::m, Sqlite3Config::mxMmap, Sqlite3Config::pcache2, sqlite3MemSetDefault(), sqlite3PCacheSetDefault(), Sqlite3Config::szMmap, sqlite3_pcache_methods2::xInit, and sqlite3_mem_methods::xMalloc.
Referenced by sqlite3MemSetDefault(), and sqlite3PCacheSetDefault().
                                                       {
  va_list ap;
  int rc = SQLITE_OK;
  /* sqlite3_config() shall return SQLITE_MISUSE if it is invoked while
  ** the SQLite library is in use. */
  if(sqlite3GlobalConfig.isInit) return SQLITE_MISUSE_BKPT;
  va_start(ap, op);
  switch(op){
    /* Mutex configuration options are only available in a threadsafe
    ** compile.
    */
#if defined(SQLITE_THREADSAFE) && SQLITE_THREADSAFE>0 /* IMP: R-54466-46756 */
    case SQLITE_CONFIG_SINGLETHREAD: {
      /* EVIDENCE-OF: R-02748-19096 This option sets the threading mode to
      ** Single-thread. */
      sqlite3GlobalConfig.bCoreMutex = 0; /* Disable mutex on core */
      sqlite3GlobalConfig.bFullMutex = 0; /* Disable mutex on connections */
      break;
    }
#endif
#if defined(SQLITE_THREADSAFE) && SQLITE_THREADSAFE>0 /* IMP: R-20520-54086 */
    case SQLITE_CONFIG_MULTITHREAD: {
      /* EVIDENCE-OF: R-14374-42468 This option sets the threading mode to
      ** Multi-thread. */
      sqlite3GlobalConfig.bCoreMutex = 1; /* Enable mutex on core */
      sqlite3GlobalConfig.bFullMutex = 0; /* Disable mutex on connections */
      break;
    }
#endif
#if defined(SQLITE_THREADSAFE) && SQLITE_THREADSAFE>0 /* IMP: R-59593-21810 */
    case SQLITE_CONFIG_SERIALIZED: {
      /* EVIDENCE-OF: R-41220-51800 This option sets the threading mode to
      ** Serialized. */
      sqlite3GlobalConfig.bCoreMutex = 1; /* Enable mutex on core */
      sqlite3GlobalConfig.bFullMutex = 1; /* Enable mutex on connections */
      break;
    }
#endif
#if defined(SQLITE_THREADSAFE) && SQLITE_THREADSAFE>0 /* IMP: R-63666-48755 */
    case SQLITE_CONFIG_MUTEX: {
      /* Specify an alternative mutex implementation */
      sqlite3GlobalConfig.mutex = *va_arg(ap,
      sqlite3_mutex_methods*);
      break;
    }
#endif
#if defined(SQLITE_THREADSAFE) && SQLITE_THREADSAFE>0 /* IMP: R-14450-37597 */
    case SQLITE_CONFIG_GETMUTEX: {
      /* Retrieve the current mutex implementation */
      *va_arg(ap, sqlite3_mutex_methods*) =
      sqlite3GlobalConfig.mutex;
      break;
    }
#endif
    case SQLITE_CONFIG_MALLOC: {
      /* EVIDENCE-OF: R-55594-21030 The SQLITE_CONFIG_MALLOC option takes a
      ** single argument which is a pointer to an instance of the
      ** sqlite3_mem_methods structure. The argument specifies alternative
      ** low-level memory allocation routines to be used in place of the memory
      ** allocation routines built into SQLite. */
      sqlite3GlobalConfig.m = *va_arg(ap, sqlite3_mem_methods*);
      break;
    }
    case SQLITE_CONFIG_GETMALLOC: {
      /* EVIDENCE-OF: R-51213-46414 The SQLITE_CONFIG_GETMALLOC option takes a
      ** single argument which is a pointer to an instance of the
      ** sqlite3_mem_methods structure. The sqlite3_mem_methods structure is
      ** filled with the currently defined memory allocation routines. */
      if(sqlite3GlobalConfig.m.xMalloc==0)
      sqlite3MemSetDefault();
      *va_arg(ap, sqlite3_mem_methods*) = sqlite3GlobalConfig.m;
      break;
    }
    case SQLITE_CONFIG_MEMSTATUS: {
      /* EVIDENCE-OF: R-61275-35157 The SQLITE_CONFIG_MEMSTATUS option takes
      ** single argument of type int, interpreted as a boolean, which enables
      ** or disables the collection of memory allocation statistics. */
      sqlite3GlobalConfig.bMemstat = va_arg(ap, int);
      break;
    }
    case SQLITE_CONFIG_SCRATCH: {
      /* EVIDENCE-OF: R-08404-60887 There are three arguments to
      ** SQLITE_CONFIG_SCRATCH: A pointer an 8-byte aligned memory buffer from
      ** which the scratch allocations will be drawn, the size of each scratch
      ** allocation (sz), and the maximum number of scratch allocations (N). */
      sqlite3GlobalConfig.pScratch = va_arg(ap, void*);
      sqlite3GlobalConfig.szScratch = va_arg(ap, int);
      sqlite3GlobalConfig.nScratch = va_arg(ap, int);
      break;
    }
    case SQLITE_CONFIG_PAGECACHE: {
      /* EVIDENCE-OF: R-31408-40510 There are three arguments to
      ** SQLITE_CONFIG_PAGECACHE: A pointer to 8-byte aligned memory, the size
      ** of each page buffer (sz), and the number of pages (N). */
      sqlite3GlobalConfig.pPage = va_arg(ap, void*);
      sqlite3GlobalConfig.szPage = va_arg(ap, int);
      sqlite3GlobalConfig.nPage = va_arg(ap, int);
      break;
    }
    case SQLITE_CONFIG_PCACHE_HDRSZ: {
      /* EVIDENCE-OF: R-39100-27317 The SQLITE_CONFIG_PCACHE_HDRSZ option takes
      ** a single parameter which is a pointer to an integer and writes into
      ** that integer the number of extra bytes per page required for each page
      ** in SQLITE_CONFIG_PAGECACHE. */
      *va_arg(ap, int*) =
          sqlite3HeaderSizeBtree() +
          sqlite3HeaderSizePcache() +
          sqlite3HeaderSizePcache1();
      break;
    }
    case SQLITE_CONFIG_PCACHE: {
      /* no-op */
      break;
    }
    case SQLITE_CONFIG_GETPCACHE: {
      /* now an error */
      rc = SQLITE_ERROR;
      break;
    }
    case SQLITE_CONFIG_PCACHE2: {
      /* EVIDENCE-OF: R-63325-48378 The SQLITE_CONFIG_PCACHE2 option takes a
      ** single argument which is a pointer to an sqlite3_pcache_methods2
      ** object. This object specifies the interface to a custom page cache
      ** implementation. */
      sqlite3GlobalConfig.pcache2 = *va_arg(ap,
      sqlite3_pcache_methods2*);
      break;
    }
    case SQLITE_CONFIG_GETPCACHE2: {
      /* EVIDENCE-OF: R-22035-46182 The SQLITE_CONFIG_GETPCACHE2 option takes a
      ** single argument which is a pointer to an sqlite3_pcache_methods2
      ** object. SQLite copies of the current page cache implementation into
      ** that object. */
      if(sqlite3GlobalConfig.pcache2.xInit==0){
        sqlite3PCacheSetDefault();
      }
      *va_arg(ap, sqlite3_pcache_methods2*) =
      sqlite3GlobalConfig.pcache2;
      break;
    }
/* EVIDENCE-OF: R-06626-12911 The SQLITE_CONFIG_HEAP option is only
** available if SQLite is compiled with either SQLITE_ENABLE_MEMSYS3 or
** SQLITE_ENABLE_MEMSYS5 and returns SQLITE_ERROR if invoked otherwise. */
#if defined(SQLITE_ENABLE_MEMSYS3) || defined(SQLITE_ENABLE_MEMSYS5)
    case SQLITE_CONFIG_HEAP: {
      /* EVIDENCE-OF: R-19854-42126 There are three arguments to
      ** SQLITE_CONFIG_HEAP: An 8-byte aligned pointer to the memory, the
      ** number of bytes in the memory buffer, and the minimum allocation size.
      */
      sqlite3GlobalConfig.pHeap = va_arg(ap, void*);
      sqlite3GlobalConfig.nHeap = va_arg(ap, int);
      sqlite3GlobalConfig.mnReq = va_arg(ap, int);
      if(sqlite3GlobalConfig.mnReq<1){
        sqlite3GlobalConfig.mnReq = 1;
      }else if(sqlite3GlobalConfig.mnReq>(1<<12)){
        /* cap min request size at 2^12 */
        sqlite3GlobalConfig.mnReq = (1<<12);
      }
      if(sqlite3GlobalConfig.pHeap==0){
        /* EVIDENCE-OF: R-49920-60189 If the first pointer (the memory pointer)
        ** is NULL, then SQLite reverts to using its default memory allocator
        ** (the system malloc() implementation), undoing any prior invocation of
        ** SQLITE_CONFIG_MALLOC.
        **
        ** Setting sqlite3GlobalConfig.m to all zeros will cause malloc to
        ** revert to its default implementation when sqlite3_initialize() is run
        */
        memset(&sqlite3GlobalConfig.m, 0, sizeof(
      sqlite3GlobalConfig.m));
      }else{
        /* EVIDENCE-OF: R-61006-08918 If the memory pointer is not NULL then the
        ** alternative memory allocator is engaged to handle all of SQLites
        ** memory allocation needs. */
#ifdef SQLITE_ENABLE_MEMSYS3
        sqlite3GlobalConfig.m = *sqlite3MemGetMemsys3();
#endif
#ifdef SQLITE_ENABLE_MEMSYS5
        sqlite3GlobalConfig.m = *sqlite3MemGetMemsys5();
#endif
      }
      break;
    }
#endif
    case SQLITE_CONFIG_LOOKASIDE: {
      sqlite3GlobalConfig.szLookaside = va_arg(ap, int);
      sqlite3GlobalConfig.nLookaside = va_arg(ap, int);
      break;
    }
    
    /* Record a pointer to the logger function and its first argument.
    ** The default is NULL. Logging is disabled if the function pointer is
    ** NULL.
    */
    case SQLITE_CONFIG_LOG: {
      /* MSVC is picky about pulling func ptrs from va lists.
      ** http://support.microsoft.com/kb/47961
      ** sqlite3GlobalConfig.xLog = va_arg(ap, void(*)(void*,int,const char*));
      */
      typedef void(*LOGFUNC_t)(void*,int,const char*);
      sqlite3GlobalConfig.xLog = va_arg(ap, LOGFUNC_t);
      sqlite3GlobalConfig.pLogArg = va_arg(ap, void*);
      break;
    }
    /* EVIDENCE-OF: R-55548-33817 The compile-time setting for URI filenames
    ** can be changed at start-time using the
    ** sqlite3_config(SQLITE_CONFIG_URI,1) or
    ** sqlite3_config(SQLITE_CONFIG_URI,0) configuration calls.
    */
    case SQLITE_CONFIG_URI: {
      /* EVIDENCE-OF: R-25451-61125 The SQLITE_CONFIG_URI option takes a single
      ** argument of type int. If non-zero, then URI handling is globally
      ** enabled. If the parameter is zero, then URI handling is globally
      ** disabled. */
      sqlite3GlobalConfig.bOpenUri = va_arg(ap, int);
      break;
    }
    case SQLITE_CONFIG_COVERING_INDEX_SCAN: {
      /* EVIDENCE-OF: R-36592-02772 The SQLITE_CONFIG_COVERING_INDEX_SCAN
      ** option takes a single integer argument which is interpreted as a
      ** boolean in order to enable or disable the use of covering indices for
      ** full table scans in the query optimizer. */
      sqlite3GlobalConfig.bUseCis = va_arg(ap, int);
      break;
    }
#ifdef SQLITE_ENABLE_SQLLOG
    case SQLITE_CONFIG_SQLLOG: {
      typedef void(*SQLLOGFUNC_t)(void*, sqlite3*, const char*, int);
      sqlite3GlobalConfig.xSqllog = va_arg(ap, SQLLOGFUNC_t);
      sqlite3GlobalConfig.pSqllogArg = va_arg(ap, void *);
      break;
    }
#endif
    case SQLITE_CONFIG_MMAP_SIZE: {
      /* EVIDENCE-OF: R-58063-38258 SQLITE_CONFIG_MMAP_SIZE takes two 64-bit
      ** integer (sqlite3_int64) values that are the default mmap size limit
      ** (the default setting for PRAGMA mmap_size) and the maximum allowed
      ** mmap size limit. */
      sqlite3_int64 szMmap = va_arg(ap, sqlite3_int64);
      sqlite3_int64 mxMmap = va_arg(ap, sqlite3_int64);
      /* EVIDENCE-OF: R-53367-43190 If either argument to this option is
      ** negative, then that argument is changed to its compile-time default.
      **
      ** EVIDENCE-OF: R-34993-45031 The maximum allowed mmap size will be
      ** silently truncated if necessary so that it does not exceed the
      ** compile-time maximum mmap size set by the SQLITE_MAX_MMAP_SIZE
      ** compile-time option.
      */
      if(mxMmap<0 || mxMmap>SQLITE_MAX_MMAP_SIZE){
        mxMmap = SQLITE_MAX_MMAP_SIZE;
      }
      if(szMmap<0) szMmap = SQLITE_DEFAULT_MMAP_SIZE;
      if(szMmap>mxMmap) szMmap = mxMmap;
      sqlite3GlobalConfig.mxMmap = mxMmap;
      sqlite3GlobalConfig.szMmap = szMmap;
      break;
    }
#if SQLITE_OS_WIN && defined(SQLITE_WIN32_MALLOC) /* IMP: R-04780-55815 */
    case SQLITE_CONFIG_WIN32_HEAPSIZE: {
      /* EVIDENCE-OF: R-34926-03360 SQLITE_CONFIG_WIN32_HEAPSIZE takes a 32-bit
      ** unsigned integer value that specifies the maximum size of the created
      ** heap. */
      sqlite3GlobalConfig.nHeap = va_arg(ap, int);
      break;
    }
#endif
    case SQLITE_CONFIG_PMASZ: {
      sqlite3GlobalConfig.szPma = va_arg(ap, unsigned int);
      break;
    }
    default: {
      rc = SQLITE_ERROR;
      break;
    }
  }
  va_end(ap);
  return rc;
}
SQLITE_API sqlite3* SQLITE_STDCALL sqlite3_context_db_handle (sqlite3_context *)
Definition at line 69636 of file sqlite3.c.
References sqlite3_value::db, and sqlite3_context::pOut.
                                                                                {
  assert(p && p->pFunc);
  return p->pOut->db;
}
SQLITE_API int SQLITE_STDCALL sqlite3_create_collation (sqlite3 * , const char * zName, int eTextRep, void * pArg, int(*)(void *, int, const void *, int, const void *) xCompare)
Definition at line 130967 of file sqlite3.c.
References sqlite3_create_collation_v2().
 {
  return sqlite3_create_collation_v2(db, zName, enc, pCtx, xCompare, 0);
}
SQLITE_API int SQLITE_STDCALL sqlite3_create_collation16 (sqlite3 * , const void * zName, int eTextRep, void * pArg, int(*)(void *, int, const void *, int, const void *) xCompare)
Definition at line 131005 of file sqlite3.c.
References sqlite3::mutex, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3DbFree(), and sqlite3Utf16to8().
 {
  int rc = SQLITE_OK;
  char *zName8;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || zName==0) return
      SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  assert(!db->mallocFailed);
  zName8 = sqlite3Utf16to8(db, zName, -1, SQLITE_UTF16NATIVE);
  if(zName8){
    rc = createCollation(db, zName8, (u8)enc, pCtx, xCompare, 0);
    sqlite3DbFree(db, zName8);
  }
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_create_collation_v2 (sqlite3 * , const char * zName, int eTextRep, void * pArg, int(*)(void *, int, const void *, int, const void *) xCompare, void(*)(void *) xDestroy)
Definition at line 130980 of file sqlite3.c.
References sqlite3::mutex, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3ApiExit().
Referenced by sqlite3_create_collation().
 {
  int rc;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || zName==0) return
      SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  assert(!db->mallocFailed);
  rc = createCollation(db, zName, (u8)enc, pCtx, xCompare, xDel);
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_create_function (sqlite3 * db, const char * zFunctionName, int nArg, int eTextRep, void * pApp, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
Definition at line 129602 of file sqlite3.c.
References sqlite3_create_function_v2().
 {
  return sqlite3_create_function_v2(db, zFunc, nArg, enc, p, xFunc, xStep,
                                    xFinal, 0);
}
SQLITE_API int SQLITE_STDCALL sqlite3_create_function16 (sqlite3 * db, const void * zFunctionName, int nArg, int eTextRep, void * pApp, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
Definition at line 129659 of file sqlite3.c.
References sqlite3::mutex, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3CreateFunc(), sqlite3DbFree(), and sqlite3Utf16to8().
 {
  int rc;
  char *zFunc8;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || zFunctionName==0) return
      SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  assert(!db->mallocFailed);
  zFunc8 = sqlite3Utf16to8(db, zFunctionName, -1,
      SQLITE_UTF16NATIVE);
  rc = sqlite3CreateFunc(db, zFunc8, nArg, eTextRep, p, xFunc, xStep, xFinal,0);
  sqlite3DbFree(db, zFunc8);
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_create_function_v2 (sqlite3 * db, const char * zFunctionName, int nArg, int eTextRep, void * pApp, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal, void(*)(void *) xDestroy)
Definition at line 129616 of file sqlite3.c.
References sqlite3::mutex, FuncDestructor::nRef, FuncDestructor::pUserData, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3CreateFunc(), sqlite3DbFree(), sqlite3DbMallocZero(), and FuncDestructor::xDestroy.
Referenced by sqlite3_create_function().
 {
  int rc = SQLITE_ERROR;
  FuncDestructor *pArg = 0;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    return SQLITE_MISUSE_BKPT;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  if(xDestroy){
    pArg = (FuncDestructor *)sqlite3DbMallocZero(db, sizeof(
      FuncDestructor));
    if(!pArg){
      xDestroy(p);
      goto out;
    }
    pArg->xDestroy = xDestroy;
    pArg->pUserData = p;
  }
  rc = sqlite3CreateFunc(db, zFunc, nArg, enc, p, xFunc, xStep, xFinal, pArg);
  if(pArg && pArg->nRef==0){
    assert(rc!=SQLITE_OK);
    xDestroy(p);
    sqlite3DbFree(db, pArg);
  }
 out:
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_create_module (sqlite3 * db, const char * zName, const sqlite3_module * p, void * pClientData)
Definition at line 114638 of file sqlite3.c.
 {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || zName==0) return
      SQLITE_MISUSE_BKPT;
#endif
  return createModule(db, zName, pModule, pAux, 0);
}
SQLITE_API int SQLITE_STDCALL sqlite3_create_module_v2 (sqlite3 * db, const char * zName, const sqlite3_module * p, void * pClientData, void(*)(void *) xDestroy)
Definition at line 114653 of file sqlite3.c.
 {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || zName==0) return
      SQLITE_MISUSE_BKPT;
#endif
  return createModule(db, zName, pModule, pAux, xDestroy);
}
SQLITE_API int SQLITE_STDCALL sqlite3_data_count (sqlite3_stmt * pStmt)
Definition at line 69821 of file sqlite3.c.
References Vdbe::nResColumn, and Vdbe::pResultSet.
                                                                     {
  Vdbe *pVm = (Vdbe *)pStmt;
  if(pVm==0 || pVm->pResultSet==0) return 0;
  return pVm->nResColumn;
}
SQLITE_API int SQLITE_CDECL sqlite3_db_config (sqlite3 * , int op, ...)
Definition at line 128720 of file sqlite3.c.
References sqlite3::flags, and sqlite3ExpirePreparedStatements().
                                                                       {
  va_list ap;
  int rc;
  va_start(ap, op);
  switch(op){
    case SQLITE_DBCONFIG_LOOKASIDE: {
      void *pBuf = va_arg(ap, void*); /* IMP: R-26835-10964 */
      int sz = va_arg(ap, int); /* IMP: R-47871-25994 */
      int cnt = va_arg(ap, int); /* IMP: R-04460-53386 */
      rc = setupLookaside(db, pBuf, sz, cnt);
      break;
    }
    default: {
      static const struct {
        int op; /* The opcode */
        u32 mask; /* Mask of the bit in sqlite3.flags to set/clear */
      } aFlagOp[] = {
        { SQLITE_DBCONFIG_ENABLE_FKEY,
      SQLITE_ForeignKeys },
        { SQLITE_DBCONFIG_ENABLE_TRIGGER,
      SQLITE_EnableTrigger },
      };
      unsigned int i;
      rc = SQLITE_ERROR; /* IMP: R-42790-23372 */
      for(i=0; i<ArraySize(aFlagOp); i++){
        if(aFlagOp[i].op==op){
          int onoff = va_arg(ap, int);
          int *pRes = va_arg(ap, int*);
          int oldFlags = db->flags;
          if(onoff>0){
            db->flags |= aFlagOp[i].mask;
          }else if(onoff==0){
            db->flags &= ~aFlagOp[i].mask;
          }
          if(oldFlags!=db->flags){
            sqlite3ExpirePreparedStatements(db);
          }
          if(pRes){
            *pRes = (db->flags & aFlagOp[i].mask)!=0;
          }
          rc = SQLITE_OK;
          break;
        }
      }
      break;
    }
  }
  va_end(ap);
  return rc;
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_db_filename (sqlite3 * db, const char * zDbName)
Definition at line 131729 of file sqlite3.c.
References sqlite3BtreeGetFilename(), and sqlite3DbNameToBtree().
                                                                                           {
  Btree *pBt;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  pBt = sqlite3DbNameToBtree(db, zDbName);
  return pBt ? sqlite3BtreeGetFilename(pBt) : 0;
}
SQLITE_API sqlite3* SQLITE_STDCALL sqlite3_db_handle (sqlite3_stmt *)
Definition at line 70456 of file sqlite3.c.
References Vdbe::db.
                                                                         {
  return pStmt ? ((Vdbe*)pStmt)->db : 0;
}
SQLITE_API sqlite3_mutex* SQLITE_STDCALL sqlite3_db_mutex (sqlite3 *)
Definition at line 128683 of file sqlite3.c.
References sqlite3::mutex.
                                                                      {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  return db->mutex;
}
SQLITE_API int SQLITE_STDCALL sqlite3_db_readonly (sqlite3 * db, const char * zDbName)
Definition at line 131745 of file sqlite3.c.
References sqlite3BtreeIsReadonly(), and sqlite3DbNameToBtree().
                                                                                   {
  Btree *pBt;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return -1;
  }
#endif
  pBt = sqlite3DbNameToBtree(db, zDbName);
  return pBt ? sqlite3BtreeIsReadonly(pBt) : -1;
}
SQLITE_API int SQLITE_STDCALL sqlite3_db_release_memory (sqlite3 *)
Definition at line 128697 of file sqlite3.c.
References sqlite3::aDb, sqlite3::mutex, sqlite3::nDb, Db::pBt, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3BtreeEnterAll(), sqlite3BtreeLeaveAll(), sqlite3BtreePager(), and sqlite3PagerShrink().
Referenced by sqlite3Pragma().
                                                                    {
  int i;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  sqlite3BtreeEnterAll(db);
  for(i=0; i<db->nDb; i++){
    Btree *pBt = db->aDb[i].pBt;
    if(pBt){
      Pager *pPager = sqlite3BtreePager(pBt);
      sqlite3PagerShrink(pPager);
    }
  }
  sqlite3BtreeLeaveAll(db);
  sqlite3_mutex_leave(db->mutex);
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_db_status (sqlite3 * , int op, int * pCur, int * pHiwtr, int resetFlg)
Definition at line 15151 of file sqlite3.c.
References sqlite3::aDb, Lookaside::anStat, Hash::count, Schema::fkeyHash, Schema::idxHash, sqlite3::lookaside, Sqlite3Config::m, sqlite3::mutex, Lookaside::mxOut, sqlite3::nDb, sqlite3::nDeferredCons, sqlite3::nDeferredImmCons, Lookaside::nOut, Db::pBt, sqlite3::pnBytesFreed, Vdbe::pNext, Db::pSchema, sqlite3::pVdbe, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3BtreeEnterAll(), sqlite3BtreeLeaveAll(), sqlite3BtreePager(), sqlite3DbFree(), sqlite3DeleteTable(), sqlite3DeleteTrigger(), sqlite3MallocSize(), sqlite3PagerCacheStat(), sqlite3PagerMemUsed(), sqlite3VdbeClearObject(), Schema::tblHash, Schema::trigHash, and sqlite3_mem_methods::xRoundup.
 {
  int rc = SQLITE_OK; /* Return code */
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || pCurrent==0|| pHighwater==0){
    return SQLITE_MISUSE_BKPT;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  switch(op){
    case SQLITE_DBSTATUS_LOOKASIDE_USED: {
      *pCurrent = db->lookaside.nOut;
      *pHighwater = db->lookaside.mxOut;
      if(resetFlag){
        db->lookaside.mxOut = db->lookaside.nOut;
      }
      break;
    }
    case SQLITE_DBSTATUS_LOOKASIDE_HIT:
    case SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE:
    case SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL: {
      testcase(op==SQLITE_DBSTATUS_LOOKASIDE_HIT);
      testcase(op==SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE);
      testcase(op==SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL);
      assert((op-SQLITE_DBSTATUS_LOOKASIDE_HIT)>=0);
      assert((op-SQLITE_DBSTATUS_LOOKASIDE_HIT)<3);
      *pCurrent = 0;
      *pHighwater = db->lookaside.anStat[op - SQLITE_DBSTATUS_LOOKASIDE_HIT];
      if(resetFlag){
        db->lookaside.anStat[op - SQLITE_DBSTATUS_LOOKASIDE_HIT] = 0;
      }
      break;
    }
    /*
    ** Return an approximation for the amount of memory currently used
    ** by all pagers associated with the given database connection. The
    ** highwater mark is meaningless and is returned as zero.
    */
    case SQLITE_DBSTATUS_CACHE_USED: {
      int totalUsed = 0;
      int i;
      sqlite3BtreeEnterAll(db);
      for(i=0; i<db->nDb; i++){
        Btree *pBt = db->aDb[i].pBt;
        if(pBt){
          Pager *pPager = sqlite3BtreePager(pBt);
          totalUsed += sqlite3PagerMemUsed(pPager);
        }
      }
      sqlite3BtreeLeaveAll(db);
      *pCurrent = totalUsed;
      *pHighwater = 0;
      break;
    }
    /*
    ** *pCurrent gets an accurate estimate of the amount of memory used
    ** to store the schema for all databases (main, temp, and any ATTACHed
    ** databases. *pHighwater is set to zero.
    */
    case SQLITE_DBSTATUS_SCHEMA_USED: {
      int i; /* Used to iterate through schemas */
      int nByte = 0; /* Used to accumulate return value */
      sqlite3BtreeEnterAll(db);
      db->pnBytesFreed = &nByte;
      for(i=0; i<db->nDb; i++){
        Schema *pSchema = db->aDb[i].pSchema;
        if(ALWAYS(pSchema!=0)){
          HashElem *p;
          nByte += sqlite3GlobalConfig.m.xRoundup(sizeof(
      HashElem)) * (
              pSchema->tblHash.count
            + pSchema->trigHash.count
            + pSchema->idxHash.count
            + pSchema->fkeyHash.count
          );
          nByte += sqlite3MallocSize(pSchema->tblHash.ht);
          nByte += sqlite3MallocSize(pSchema->trigHash.
      ht);
          nByte += sqlite3MallocSize(pSchema->idxHash.ht);
          nByte += sqlite3MallocSize(pSchema->fkeyHash.
      ht);
          for(p=sqliteHashFirst(&pSchema->trigHash); p; p=
      sqliteHashNext(p)){
            sqlite3DeleteTrigger(db, (Trigger*)
      sqliteHashData(p));
          }
          for(p=sqliteHashFirst(&pSchema->tblHash); p; p=
      sqliteHashNext(p)){
            sqlite3DeleteTable(db, (Table *)
      sqliteHashData(p));
          }
        }
      }
      db->pnBytesFreed = 0;
      sqlite3BtreeLeaveAll(db);
      *pHighwater = 0;
      *pCurrent = nByte;
      break;
    }
    /*
    ** *pCurrent gets an accurate estimate of the amount of memory used
    ** to store all prepared statements.
    ** *pHighwater is set to zero.
    */
    case SQLITE_DBSTATUS_STMT_USED: {
      struct Vdbe *pVdbe; /* Used to iterate through VMs */
      int nByte = 0; /* Used to accumulate return value */
      db->pnBytesFreed = &nByte;
      for(pVdbe=db->pVdbe; pVdbe; pVdbe=pVdbe->pNext){
        sqlite3VdbeClearObject(db, pVdbe);
        sqlite3DbFree(db, pVdbe);
      }
      db->pnBytesFreed = 0;
      *pHighwater = 0; /* IMP: R-64479-57858 */
      *pCurrent = nByte;
      break;
    }
    /*
    ** Set *pCurrent to the total cache hits or misses encountered by all
    ** pagers the database handle is connected to. *pHighwater is always set
    ** to zero.
    */
    case SQLITE_DBSTATUS_CACHE_HIT:
    case SQLITE_DBSTATUS_CACHE_MISS:
    case SQLITE_DBSTATUS_CACHE_WRITE:{
      int i;
      int nRet = 0;
      assert(SQLITE_DBSTATUS_CACHE_MISS==
      SQLITE_DBSTATUS_CACHE_HIT+1);
      assert(SQLITE_DBSTATUS_CACHE_WRITE==
      SQLITE_DBSTATUS_CACHE_HIT+2);
      for(i=0; i<db->nDb; i++){
        if(db->aDb[i].pBt){
          Pager *pPager = sqlite3BtreePager(db->aDb[i].
      pBt);
          sqlite3PagerCacheStat(pPager, op, resetFlag, &nRet);
        }
      }
      *pHighwater = 0; /* IMP: R-42420-56072 */
                       /* IMP: R-54100-20147 */
                       /* IMP: R-29431-39229 */
      *pCurrent = nRet;
      break;
    }
    /* Set *pCurrent to non-zero if there are unresolved deferred foreign
    ** key constraints. Set *pCurrent to zero if all foreign key constraints
    ** have been satisfied. The *pHighwater is always set to zero.
    */
    case SQLITE_DBSTATUS_DEFERRED_FKS: {
      *pHighwater = 0; /* IMP: R-11967-56545 */
      *pCurrent = db->nDeferredImmCons>0 || db->
      nDeferredCons>0;
      break;
    }
    default: {
      rc = SQLITE_ERROR;
    }
  }
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_declare_vtab (sqlite3 * , const char * zSQL)
Definition at line 115289 of file sqlite3.c.
References Table::aCol, VtabCtx::bDeclared, Parse::db, Parse::declareVtab, sqlite3::mallocFailed, sqlite3::mutex, Table::nCol, Parse::nQueryLoop, Parse::pNewTable, Table::pSelect, VtabCtx::pTab, Parse::pVdbe, sqlite3::pVtabCtx, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3DbFree(), sqlite3DeleteTable(), sqlite3Error(), sqlite3ErrorWithMsg(), sqlite3ParserReset(), sqlite3RunParser(), sqlite3VdbeFinalize(), and Table::tabFlags.
                                                                                         {
  VtabCtx *pCtx;
  Parse *pParse;
  int rc = SQLITE_OK;
  Table *pTab;
  char *zErr = 0;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || zCreateTable==0){
    return SQLITE_MISUSE_BKPT;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  pCtx = db->pVtabCtx;
  if(!pCtx || pCtx->bDeclared){
    sqlite3Error(db, SQLITE_MISUSE);
    sqlite3_mutex_leave(db->mutex);
    return SQLITE_MISUSE_BKPT;
  }
  pTab = pCtx->pTab;
  assert((pTab->tabFlags & TF_Virtual)!=0);
  pParse = sqlite3StackAllocZero(db, sizeof(*pParse));
  if(pParse==0){
    rc = SQLITE_NOMEM;
  }else{
    pParse->declareVtab = 1;
    pParse->db = db;
    pParse->nQueryLoop = 1;
  
    if(SQLITE_OK==sqlite3RunParser(pParse, zCreateTable, &zErr)
     && pParse->pNewTable
     && !db->mallocFailed
     && !pParse->pNewTable->pSelect
     && (pParse->pNewTable->tabFlags & TF_Virtual)==0
    ){
      if(!pTab->aCol){
        pTab->aCol = pParse->pNewTable->aCol;
        pTab->nCol = pParse->pNewTable->nCol;
        pParse->pNewTable->nCol = 0;
        pParse->pNewTable->aCol = 0;
      }
      pCtx->bDeclared = 1;
    }else{
      sqlite3ErrorWithMsg(db, SQLITE_ERROR, (zErr ? "%s" : 0), zErr);
      sqlite3DbFree(db, zErr);
      rc = SQLITE_ERROR;
    }
    pParse->declareVtab = 0;
  
    if(pParse->pVdbe){
      sqlite3VdbeFinalize(pParse->pVdbe);
    }
    sqlite3DeleteTable(db, pParse->pNewTable);
    sqlite3ParserReset(pParse);
    sqlite3StackFree(db, pParse);
  }
  assert((rc&0xff)==rc);
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_enable_load_extension (sqlite3 * db, int onoff)
Definition at line 102954 of file sqlite3.c.
References sqlite3::flags, sqlite3::mutex, sqlite3_mutex_enter(), and sqlite3_mutex_leave().
                                                                                   {
  sqlite3_mutex_enter(db->mutex);
  if(onoff){
    db->flags |= SQLITE_LoadExtension;
  }else{
    db->flags &= ~SQLITE_LoadExtension;
  }
  sqlite3_mutex_leave(db->mutex);
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_enable_shared_cache (int)
Definition at line 53171 of file sqlite3.c.
References Sqlite3Config::sharedCacheEnabled.
                                                                     {
  sqlite3GlobalConfig.sharedCacheEnabled = enable;
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_errcode (sqlite3 * db)
Definition at line 130151 of file sqlite3.c.
References sqlite3::errCode, sqlite3::errMask, sqlite3::mallocFailed, and sqlite3SafetyCheckSickOrOk().
                                                          {
  if(db && !sqlite3SafetyCheckSickOrOk(db)){
    return SQLITE_MISUSE_BKPT;
  }
  if(!db || db->mallocFailed){
    return SQLITE_NOMEM;
  }
  return db->errCode & db->errMask;
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_errmsg (sqlite3 *)
Definition at line 130078 of file sqlite3.c.
References sqlite3::errCode, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::pErr, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_value_text(), sqlite3ErrStr(), and sqlite3SafetyCheckSickOrOk().
Referenced by sqlite3_exec(), and sqlite3InitCallback().
                                                                 {
  const char *z;
  if(!db){
    return sqlite3ErrStr(SQLITE_NOMEM);
  }
  if(!sqlite3SafetyCheckSickOrOk(db)){
    return sqlite3ErrStr(SQLITE_MISUSE_BKPT);
  }
  sqlite3_mutex_enter(db->mutex);
  if(db->mallocFailed){
    z = sqlite3ErrStr(SQLITE_NOMEM);
  }else{
    testcase(db->pErr==0);
    z = (char*)sqlite3_value_text(db->pErr);
    assert(!db->mallocFailed);
    if(z==0){
      z = sqlite3ErrStr(db->errCode);
    }
  }
  sqlite3_mutex_leave(db->mutex);
  return z;
}
SQLITE_API const void* SQLITE_STDCALL sqlite3_errmsg16 (sqlite3 *)
Definition at line 130106 of file sqlite3.c.
References sqlite3::errCode, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::pErr, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_value_text16(), sqlite3ErrorWithMsg(), sqlite3ErrStr(), and sqlite3SafetyCheckSickOrOk().
                                                                   {
  static const u16 outOfMem[] = {
    'o', 'u', 't', ' ', 'o', 'f', ' ', 'm', 'e', 'm', 'o', 'r', 'y', 0
  };
  static const u16 misuse[] = {
    'l', 'i', 'b', 'r', 'a', 'r', 'y', ' ',
    'r', 'o', 'u', 't', 'i', 'n', 'e', ' ',
    'c', 'a', 'l', 'l', 'e', 'd', ' ',
    'o', 'u', 't', ' ',
    'o', 'f', ' ',
    's', 'e', 'q', 'u', 'e', 'n', 'c', 'e', 0
  };
  const void *z;
  if(!db){
    return (void *)outOfMem;
  }
  if(!sqlite3SafetyCheckSickOrOk(db)){
    return (void *)misuse;
  }
  sqlite3_mutex_enter(db->mutex);
  if(db->mallocFailed){
    z = (void *)outOfMem;
  }else{
    z = sqlite3_value_text16(db->pErr);
    if(z==0){
      sqlite3ErrorWithMsg(db, db->errCode,
      sqlite3ErrStr(db->errCode));
      z = sqlite3_value_text16(db->pErr);
    }
    /* A malloc() may have failed within the call to sqlite3_value_text16()
    ** above. If this is the case, then the db->mallocFailed flag needs to
    ** be cleared before returning. Do this directly, instead of via
    ** sqlite3ApiExit(), to avoid setting the database handle error message.
    */
    db->mallocFailed = 0;
  }
  sqlite3_mutex_leave(db->mutex);
  return z;
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_errstr (int)
Definition at line 130175 of file sqlite3.c.
References sqlite3ErrStr().
                                                            {
  return sqlite3ErrStr(rc);
}
SQLITE_API int SQLITE_STDCALL sqlite3_exec (sqlite3 * , const char * sql, int(*)(void *, int, char **, char **) callback, void * , char ** errmsg)
Definition at line 101728 of file sqlite3.c.
References sqlite3::flags, sqlite3::mallocFailed, sqlite3::mutex, sqlite3_column_count(), sqlite3_column_name(), sqlite3_column_text(), sqlite3_column_type(), sqlite3_errmsg(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_prepare_v2(), sqlite3_step(), sqlite3ApiExit(), sqlite3DbFree(), sqlite3Error(), sqlite3SafetyCheckOk(), sqlite3Strlen30(), and sqlite3VdbeFinalize().
Referenced by sqlite3_get_table(), sqlite3AnalysisLoad(), and sqlite3VdbeExec().
 {
  int rc = SQLITE_OK; /* Return code */
  const char *zLeftover; /* Tail of unprocessed SQL */
  sqlite3_stmt *pStmt = 0; /* The current SQL statement */
  char **azCols = 0; /* Names of result columns */
  int callbackIsInit; /* True if callback data is initialized */
  if(!sqlite3SafetyCheckOk(db)) return
      SQLITE_MISUSE_BKPT;
  if(zSql==0) zSql = "";
  sqlite3_mutex_enter(db->mutex);
  sqlite3Error(db, SQLITE_OK);
  while(rc==SQLITE_OK && zSql[0]){
    int nCol;
    char **azVals = 0;
    pStmt = 0;
    rc = sqlite3_prepare_v2(db, zSql, -1, &pStmt, &zLeftover);
    assert(rc==SQLITE_OK || pStmt==0);
    if(rc!=SQLITE_OK){
      continue;
    }
    if(!pStmt){
      /* this happens for a comment or white-space */
      zSql = zLeftover;
      continue;
    }
    callbackIsInit = 0;
    nCol = sqlite3_column_count(pStmt);
    while(1){
      int i;
      rc = sqlite3_step(pStmt);
      /* Invoke the callback function if required */
      if(xCallback && (SQLITE_ROW==rc ||
          (SQLITE_DONE==rc && !callbackIsInit
                           && db->flags&SQLITE_NullCallback))){
        if(!callbackIsInit){
          azCols = sqlite3DbMallocZero(db, 2*nCol*sizeof(const char*) + 1);
          if(azCols==0){
            goto exec_out;
          }
          for(i=0; i<nCol; i++){
            azCols[i] = (char *)sqlite3_column_name(pStmt, i);
            /* sqlite3VdbeSetColName() installs column names as UTF8
            ** strings so there is no way for sqlite3_column_name() to fail. */
            assert(azCols[i]!=0);
          }
          callbackIsInit = 1;
        }
        if(rc==SQLITE_ROW){
          azVals = &azCols[nCol];
          for(i=0; i<nCol; i++){
            azVals[i] = (char *)sqlite3_column_text(pStmt, i);
            if(!azVals[i] && sqlite3_column_type(pStmt, i)!=
      SQLITE_NULL){
              db->mallocFailed = 1;
              goto exec_out;
            }
          }
        }
        if(xCallback(pArg, nCol, azVals, azCols)){
          /* EVIDENCE-OF: R-38229-40159 If the callback function to
          ** sqlite3_exec() returns non-zero, then sqlite3_exec() will
          ** return SQLITE_ABORT. */
          rc = SQLITE_ABORT;
          sqlite3VdbeFinalize((Vdbe *)pStmt);
          pStmt = 0;
          sqlite3Error(db, SQLITE_ABORT);
          goto exec_out;
        }
      }
      if(rc!=SQLITE_ROW){
        rc = sqlite3VdbeFinalize((Vdbe *)pStmt);
        pStmt = 0;
        zSql = zLeftover;
        while(sqlite3Isspace(zSql[0])) zSql++;
        break;
      }
    }
    sqlite3DbFree(db, azCols);
    azCols = 0;
  }
exec_out:
  if(pStmt) sqlite3VdbeFinalize((Vdbe *)pStmt);
  sqlite3DbFree(db, azCols);
  rc = sqlite3ApiExit(db, rc);
  if(rc!=SQLITE_OK && pzErrMsg){
    int nErrMsg = 1 + sqlite3Strlen30(sqlite3_errmsg(
      db));
    *pzErrMsg = sqlite3Malloc(nErrMsg);
    if(*pzErrMsg){
      memcpy(*pzErrMsg, sqlite3_errmsg(db), nErrMsg);
    }else{
      rc = SQLITE_NOMEM;
      sqlite3Error(db, SQLITE_NOMEM);
    }
  }else if(pzErrMsg){
    *pzErrMsg = 0;
  }
  assert((rc&db->errMask)==rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API SQLITE_DEPRECATED int SQLITE_STDCALL sqlite3_expired (sqlite3_stmt *)
Definition at line 69034 of file sqlite3.c.
References Vdbe::expired.
                                                                  {
  Vdbe *p = (Vdbe*)pStmt;
  return p==0 || p->expired;
}
SQLITE_API int SQLITE_STDCALL sqlite3_extended_errcode (sqlite3 * db)
Definition at line 130160 of file sqlite3.c.
References sqlite3::errCode, sqlite3::mallocFailed, and sqlite3SafetyCheckSickOrOk().
                                                                   {
  if(db && !sqlite3SafetyCheckSickOrOk(db)){
    return SQLITE_MISUSE_BKPT;
  }
  if(!db || db->mallocFailed){
    return SQLITE_NOMEM;
  }
  return db->errCode;
}
SQLITE_API int SQLITE_STDCALL sqlite3_extended_result_codes (sqlite3 * , int onoff)
Definition at line 131283 of file sqlite3.c.
References sqlite3::errMask, sqlite3::mutex, sqlite3_mutex_enter(), and sqlite3_mutex_leave().
                                                                                   {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return
      SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  db->errMask = onoff ? 0xffffffff : 0xff;
  sqlite3_mutex_leave(db->mutex);
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_file_control (sqlite3 * , const char * zDbName, int op, void *)
Definition at line 131296 of file sqlite3.c.
References sqlite3::mutex, sqlite3_file::pMethods, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3BtreeEnter(), sqlite3BtreeLeave(), sqlite3BtreePager(), sqlite3DbNameToBtree(), sqlite3OsFileControl(), and sqlite3PagerFile().
Referenced by sqlite3Pragma().
                                                                                                        {
  int rc = SQLITE_ERROR;
  Btree *pBtree;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return
      SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  pBtree = sqlite3DbNameToBtree(db, zDbName);
  if(pBtree){
    Pager *pPager;
    sqlite3_file *fd;
    sqlite3BtreeEnter(pBtree);
    pPager = sqlite3BtreePager(pBtree);
    assert(pPager!=0);
    fd = sqlite3PagerFile(pPager);
    assert(fd!=0);
    if(op==SQLITE_FCNTL_FILE_POINTER){
      *(sqlite3_file**)pArg = fd;
      rc = SQLITE_OK;
    }else if(fd->pMethods){
      rc = sqlite3OsFileControl(fd, op, pArg);
    }else{
      rc = SQLITE_NOTFOUND;
    }
    sqlite3BtreeLeave(pBtree);
  }
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_finalize (sqlite3_stmt * pStmt)
Definition at line 69071 of file sqlite3.c.
References Vdbe::db, sqlite3::mutex, sqlite3_mutex_enter(), sqlite3ApiExit(), sqlite3LeaveMutexAndCloseZombie(), and sqlite3VdbeFinalize().
Referenced by sqlite3_blob_close(), and sqlite3InitCallback().
                                                                   {
  int rc;
  if(pStmt==0){
    /* IMPLEMENTATION-OF: R-57228-12904 Invoking sqlite3_finalize() on a NULL
    ** pointer is a harmless no-op. */
    rc = SQLITE_OK;
  }else{
    Vdbe *v = (Vdbe*)pStmt;
    sqlite3 *db = v->db;
    if(vdbeSafety(v)) return SQLITE_MISUSE_BKPT;
    sqlite3_mutex_enter(db->mutex);
    rc = sqlite3VdbeFinalize(v);
    rc = sqlite3ApiExit(db, rc);
    sqlite3LeaveMutexAndCloseZombie(db);
  }
  return rc;
}
SQLITE_API void SQLITE_STDCALL sqlite3_free (void *)
Definition at line 21010 of file sqlite3.c.
References Sqlite3Config::bMemstat, Sqlite3Config::m, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3MallocSize(), sqlite3StatusDown(), and sqlite3_mem_methods::xFree.
Referenced by sqlite3_backup_finish(), sqlite3_backup_init(), sqlite3_free_table(), sqlite3_get_table(), sqlite3_reset_auto_extension(), sqlite3AutoLoadExtensions(), sqlite3BitvecBuiltinTest(), sqlite3BitvecDestroy(), sqlite3BtreeClearCursor(), sqlite3BtreeClose(), sqlite3BtreeCloseCursor(), sqlite3BtreeIntegrityCheck(), sqlite3BtreeMovetoUnpacked(), sqlite3BtreeOpen(), sqlite3DbFree(), sqlite3HashClear(), sqlite3InvalidFunction(), sqlite3LeaveMutexAndCloseZombie(), sqlite3OsCloseFree(), sqlite3OsInit(), sqlite3OsOpenMalloc(), sqlite3PagerClose(), sqlite3PagerOpen(), sqlite3ParseUri(), sqlite3Pragma(), sqlite3Realloc(), sqlite3RunParser(), sqlite3StrAccumReset(), sqlite3ThreadJoin(), sqlite3VdbeExec(), sqlite3VdbeSorterClose(), sqlite3VtabImportErrmsg(), sqlite3VXPrintf(), sqlite3WalClose(), and sqlite3WalOpen().
                                                    {
  if(p==0) return; /* IMP: R-49053-54554 */
  assert(sqlite3MemdebugHasType(p, MEMTYPE_HEAP));
  assert(sqlite3MemdebugNoType(p, (u8)~MEMTYPE_HEAP));
  if(sqlite3GlobalConfig.bMemstat){
    sqlite3_mutex_enter(mem0.mutex);
    sqlite3StatusDown(SQLITE_STATUS_MEMORY_USED,
      sqlite3MallocSize(p));
    sqlite3StatusDown(SQLITE_STATUS_MALLOC_COUNT, 1);
    sqlite3GlobalConfig.m.xFree(p);
    sqlite3_mutex_leave(mem0.mutex);
  }else{
    sqlite3GlobalConfig.m.xFree(p);
  }
}
SQLITE_API void SQLITE_STDCALL sqlite3_free_table (char ** result)
Definition at line 112272 of file sqlite3.c.
References sqlite3_free().
Referenced by sqlite3_get_table().
 {
  if(azResult){
    int i, n;
    azResult--;
    assert(azResult!=0);
    n = SQLITE_PTR_TO_INT(azResult[0]);
    for(i=1; i<n; i++){ if(azResult[i]) sqlite3_free(azResult[i]); }
    sqlite3_free(azResult);
  }
}
SQLITE_API int SQLITE_STDCALL sqlite3_get_autocommit (sqlite3 *)
Definition at line 131089 of file sqlite3.c.
References sqlite3::autoCommit.
                                                                 {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  return db->autoCommit;
}
SQLITE_API void* SQLITE_STDCALL sqlite3_get_auxdata (sqlite3_context * , int N)
Definition at line 69727 of file sqlite3.c.
References AuxData::iArg, AuxData::iOp, sqlite3_context::iOp, AuxData::pAux, Vdbe::pAuxData, AuxData::pNext, and sqlite3_context::pVdbe.
                                                                                    {
  AuxData *pAuxData;
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
#if SQLITE_ENABLE_STAT3_OR_STAT4
  if(pCtx->pVdbe==0) return 0;
#else
  assert(pCtx->pVdbe!=0);
#endif
  for(pAuxData=pCtx->pVdbe->pAuxData; pAuxData; pAuxData=pAuxData->pNext){
    if(pAuxData->iOp==pCtx->iOp && pAuxData->iArg==iArg) break;
  }
  return (pAuxData ? pAuxData->pAux : 0);
}
SQLITE_API int SQLITE_STDCALL sqlite3_get_table (sqlite3 * db, const char * zSql, char *** pazResult, int * pnRow, int * pnColumn, char ** pzErrmsg)
Definition at line 112203 of file sqlite3.c.
References TabResult::azResult, sqlite3::errCode, TabResult::nAlloc, TabResult::nColumn, TabResult::nData, TabResult::nRow, TabResult::rc, sqlite3_exec(), sqlite3_free(), sqlite3_free_table(), sqlite3_mprintf(), and TabResult::zErrMsg.
 {
  int rc;
  TabResult res;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || pazResult==0) return
      SQLITE_MISUSE_BKPT;
#endif
  *pazResult = 0;
  if(pnColumn) *pnColumn = 0;
  if(pnRow) *pnRow = 0;
  if(pzErrMsg) *pzErrMsg = 0;
  res.zErrMsg = 0;
  res.nRow = 0;
  res.nColumn = 0;
  res.nData = 1;
  res.nAlloc = 20;
  res.rc = SQLITE_OK;
  res.azResult = sqlite3_malloc(sizeof(char*)*res.nAlloc);
  if(res.azResult==0){
     db->errCode = SQLITE_NOMEM;
     return SQLITE_NOMEM;
  }
  res.azResult[0] = 0;
  rc = sqlite3_exec(db, zSql, sqlite3_get_table_cb, &res, pzErrMsg);
  assert(sizeof(res.azResult[0])>= sizeof(res.nData));
  res.azResult[0] = SQLITE_INT_TO_PTR(res.nData);
  if((rc&0xff)==SQLITE_ABORT){
    sqlite3_free_table(&res.azResult[1]);
    if(res.zErrMsg){
      if(pzErrMsg){
        sqlite3_free(*pzErrMsg);
        *pzErrMsg = sqlite3_mprintf("%s",res.zErrMsg);
      }
      sqlite3_free(res.zErrMsg);
    }
    db->errCode = res.rc; /* Assume 32-bit assignment is atomic */
    return res.rc;
  }
  sqlite3_free(res.zErrMsg);
  if(rc!=SQLITE_OK){
    sqlite3_free_table(&res.azResult[1]);
    return rc;
  }
  if(res.nAlloc>res.nData){
    char **azNew;
    azNew = sqlite3_realloc(res.azResult, sizeof(char*)*res.
      nData);
    if(azNew==0){
      sqlite3_free_table(&res.azResult[1]);
      db->errCode = SQLITE_NOMEM;
      return SQLITE_NOMEM;
    }
    res.azResult = azNew;
  }
  *pazResult = &res.azResult[1];
  if(pnColumn) *pnColumn = res.nColumn;
  if(pnRow) *pnRow = res.nRow;
  return rc;
}
SQLITE_API SQLITE_DEPRECATED int SQLITE_STDCALL sqlite3_global_recover (void)
Definition at line 131078 of file sqlite3.c.
                                                          {
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_initialize (void)
Definition at line 128111 of file sqlite3.c.
References Sqlite3Config::bCoreMutex, Sqlite3Config::inProgress, Sqlite3Config::isInit, Sqlite3Config::isMallocInit, Sqlite3Config::isMutexInit, Sqlite3Config::isPCacheInit, Sqlite3Config::nPage, Sqlite3Config::nRefInitMutex, Sqlite3Config::pInitMutex, Sqlite3Config::pPage, sqlite3_mutex_enter(), sqlite3_mutex_free(), sqlite3_mutex_leave(), sqlite3GlobalFunctions, sqlite3MallocInit(), sqlite3MutexAlloc(), sqlite3MutexInit(), sqlite3OsInit(), sqlite3PCacheBufferSetup(), sqlite3PcacheInitialize(), sqlite3RegisterGlobalFunctions(), and Sqlite3Config::szPage.
Referenced by sqlite3_auto_extension(), sqlite3_complete16(), sqlite3_malloc(), sqlite3_malloc64(), sqlite3_mprintf(), sqlite3_mutex_alloc(), sqlite3_open16(), sqlite3_randomness(), sqlite3_realloc(), sqlite3_realloc64(), sqlite3_reset_auto_extension(), sqlite3_soft_heap_limit64(), sqlite3_vfs_find(), sqlite3_vfs_register(), and sqlite3_vmprintf().
                                                      {
  MUTEX_LOGIC(sqlite3_mutex *pMaster;) /* The main static mutex */
  int rc; /* Result code */
#ifdef SQLITE_EXTRA_INIT
  int bRunExtraInit = 0; /* Extra initialization needed */
#endif
#ifdef SQLITE_OMIT_WSD
  rc = sqlite3_wsd_init(4096, 24);
  if(rc!=SQLITE_OK){
    return rc;
  }
#endif
  /* If the following assert() fails on some obscure processor/compiler
  ** combination, the work-around is to set the correct pointer
  ** size at compile-time using -DSQLITE_PTRSIZE=n compile-time option */
  assert(SQLITE_PTRSIZE==sizeof(char*));
  /* If SQLite is already completely initialized, then this call
  ** to sqlite3_initialize() should be a no-op. But the initialization
  ** must be complete. So isInit must not be set until the very end
  ** of this routine.
  */
  if(sqlite3GlobalConfig.isInit) return SQLITE_OK;
  /* Make sure the mutex subsystem is initialized. If unable to
  ** initialize the mutex subsystem, return early with the error.
  ** If the system is so sick that we are unable to allocate a mutex,
  ** there is not much SQLite is going to be able to do.
  **
  ** The mutex subsystem must take care of serializing its own
  ** initialization.
  */
  rc = sqlite3MutexInit();
  if(rc) return rc;
  /* Initialize the malloc() system and the recursive pInitMutex mutex.
  ** This operation is protected by the STATIC_MASTER mutex. Note that
  ** MutexAlloc() is called for a static mutex prior to initializing the
  ** malloc subsystem - this implies that the allocation of a static
  ** mutex must not require support from the malloc subsystem.
  */
  MUTEX_LOGIC(pMaster = sqlite3MutexAlloc(
      SQLITE_MUTEX_STATIC_MASTER);)
  sqlite3_mutex_enter(pMaster);
  sqlite3GlobalConfig.isMutexInit = 1;
  if(!sqlite3GlobalConfig.isMallocInit){
    rc = sqlite3MallocInit();
  }
  if(rc==SQLITE_OK){
    sqlite3GlobalConfig.isMallocInit = 1;
    if(!sqlite3GlobalConfig.pInitMutex){
      sqlite3GlobalConfig.pInitMutex =
           sqlite3MutexAlloc(SQLITE_MUTEX_RECURSIVE);
      if(sqlite3GlobalConfig.bCoreMutex && !
      sqlite3GlobalConfig.pInitMutex){
        rc = SQLITE_NOMEM;
      }
    }
  }
  if(rc==SQLITE_OK){
    sqlite3GlobalConfig.nRefInitMutex++;
  }
  sqlite3_mutex_leave(pMaster);
  /* If rc is not SQLITE_OK at this point, then either the malloc
  ** subsystem could not be initialized or the system failed to allocate
  ** the pInitMutex mutex. Return an error in either case. */
  if(rc!=SQLITE_OK){
    return rc;
  }
  /* Do the rest of the initialization under the recursive mutex so
  ** that we will be able to handle recursive calls into
  ** sqlite3_initialize(). The recursive calls normally come through
  ** sqlite3_os_init() when it invokes sqlite3_vfs_register(), but other
  ** recursive calls might also be possible.
  **
  ** IMPLEMENTATION-OF: R-00140-37445 SQLite automatically serializes calls
  ** to the xInit method, so the xInit method need not be threadsafe.
  **
  ** The following mutex is what serializes access to the appdef pcache xInit
  ** methods. The sqlite3_pcache_methods.xInit() all is embedded in the
  ** call to sqlite3PcacheInitialize().
  */
  sqlite3_mutex_enter(sqlite3GlobalConfig.pInitMutex);
  if(sqlite3GlobalConfig.isInit==0 && sqlite3GlobalConfig.inProgress
      ==0){
    FuncDefHash *pHash = &GLOBAL(FuncDefHash,
      sqlite3GlobalFunctions);
    sqlite3GlobalConfig.inProgress = 1;
    memset(pHash, 0, sizeof(sqlite3GlobalFunctions));
    sqlite3RegisterGlobalFunctions();
    if(sqlite3GlobalConfig.isPCacheInit==0){
      rc = sqlite3PcacheInitialize();
    }
    if(rc==SQLITE_OK){
      sqlite3GlobalConfig.isPCacheInit = 1;
      rc = sqlite3OsInit();
    }
    if(rc==SQLITE_OK){
      sqlite3PCacheBufferSetup(sqlite3GlobalConfig.pPage,
          sqlite3GlobalConfig.szPage, sqlite3GlobalConfig.nPage);
      sqlite3GlobalConfig.isInit = 1;
#ifdef SQLITE_EXTRA_INIT
      bRunExtraInit = 1;
#endif
    }
    sqlite3GlobalConfig.inProgress = 0;
  }
  sqlite3_mutex_leave(sqlite3GlobalConfig.pInitMutex);
  /* Go back under the static mutex and clean up the recursive
  ** mutex to prevent a resource leak.
  */
  sqlite3_mutex_enter(pMaster);
  sqlite3GlobalConfig.nRefInitMutex--;
  if(sqlite3GlobalConfig.nRefInitMutex<=0){
    assert(sqlite3GlobalConfig.nRefInitMutex==0);
    sqlite3_mutex_free(sqlite3GlobalConfig.pInitMutex);
    sqlite3GlobalConfig.pInitMutex = 0;
  }
  sqlite3_mutex_leave(pMaster);
  /* The following is just a sanity check to make sure SQLite has
  ** been compiled correctly. It is important to run this code, but
  ** we don't want to run it too often and soak up CPU cycles for no
  ** reason. So we run it once during initialization.
  */
#ifndef NDEBUG
#ifndef SQLITE_OMIT_FLOATING_POINT
  /* This section of code's only "output" is via assert() statements. */
  if (rc==SQLITE_OK){
    u64 x = (((u64)1)<<63)-1;
    double y;
    assert(sizeof(x)==8);
    assert(sizeof(x)==sizeof(y));
    memcpy(&y, &x, 8);
    assert(sqlite3IsNaN(y));
  }
#endif
#endif
  /* Do extra initialization steps requested by the SQLITE_EXTRA_INIT
  ** compile-time option.
  */
#ifdef SQLITE_EXTRA_INIT
  if(bRunExtraInit){
    int SQLITE_EXTRA_INIT(const char*);
    rc = SQLITE_EXTRA_INIT(0);
  }
#endif
  return rc;
}
SQLITE_API void SQLITE_STDCALL sqlite3_interrupt (sqlite3 *)
Definition at line 129485 of file sqlite3.c.
                                                             {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return;
  }
#endif
  db->u1.isInterrupted = 1;
}
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_last_insert_rowid (sqlite3 *)
Definition at line 128839 of file sqlite3.c.
References sqlite3::lastRowid.
                                                                             {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  return db->lastRowid;
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_libversion (void)
Definition at line 128033 of file sqlite3.c.
References sqlite3_version.
{ return sqlite3_version; }
SQLITE_API int SQLITE_STDCALL sqlite3_libversion_number (void)
Definition at line 128044 of file sqlite3.c.
{ return SQLITE_VERSION_NUMBER; }
SQLITE_API int SQLITE_STDCALL sqlite3_limit (sqlite3 * , int id, int newVal)
Definition at line 130323 of file sqlite3.c.
References sqlite3::aLimit.
Referenced by sqlite3Pragma().
                                                                                   {
  int oldLimit;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return -1;
  }
#endif
  /* EVIDENCE-OF: R-30189-54097 For each limit category SQLITE_LIMIT_NAME
  ** there is a hard upper bound set at compile-time by a C preprocessor
  ** macro called SQLITE_MAX_NAME. (The "_LIMIT_" in the name is changed to
  ** "_MAX_".)
  */
  assert(aHardLimit[SQLITE_LIMIT_LENGTH]==SQLITE_MAX_LENGTH);
  assert(aHardLimit[SQLITE_LIMIT_SQL_LENGTH]==
      SQLITE_MAX_SQL_LENGTH);
  assert(aHardLimit[SQLITE_LIMIT_COLUMN]==SQLITE_MAX_COLUMN);
  assert(aHardLimit[SQLITE_LIMIT_EXPR_DEPTH]==
      SQLITE_MAX_EXPR_DEPTH);
  assert(aHardLimit[SQLITE_LIMIT_COMPOUND_SELECT]==
      SQLITE_MAX_COMPOUND_SELECT);
  assert(aHardLimit[SQLITE_LIMIT_VDBE_OP]==
      SQLITE_MAX_VDBE_OP);
  assert(aHardLimit[SQLITE_LIMIT_FUNCTION_ARG]==
      SQLITE_MAX_FUNCTION_ARG);
  assert(aHardLimit[SQLITE_LIMIT_ATTACHED]==
      SQLITE_MAX_ATTACHED);
  assert(aHardLimit[SQLITE_LIMIT_LIKE_PATTERN_LENGTH]==
                                               SQLITE_MAX_LIKE_PATTERN_LENGTH
       );
  assert(aHardLimit[SQLITE_LIMIT_VARIABLE_NUMBER]==
      SQLITE_MAX_VARIABLE_NUMBER);
  assert(aHardLimit[SQLITE_LIMIT_TRIGGER_DEPTH]==
      SQLITE_MAX_TRIGGER_DEPTH);
  assert(aHardLimit[SQLITE_LIMIT_WORKER_THREADS]==
      SQLITE_MAX_WORKER_THREADS);
  assert(SQLITE_LIMIT_WORKER_THREADS==(
      SQLITE_N_LIMIT-1));
  if(limitId<0 || limitId>=SQLITE_N_LIMIT){
    return -1;
  }
  oldLimit = db->aLimit[limitId];
  if(newLimit>=0){ /* IMP: R-52476-28732 */
    if(newLimit>aHardLimit[limitId]){
      newLimit = aHardLimit[limitId]; /* IMP: R-51463-25634 */
    }
    db->aLimit[limitId] = newLimit;
  }
  return oldLimit; /* IMP: R-53341-35419 */
}
SQLITE_API int SQLITE_STDCALL sqlite3_load_extension (sqlite3 * db, const char * zFile, const char * zProc, char ** pzErrMsg)
Definition at line 102923 of file sqlite3.c.
References sqlite3::mutex, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3ApiExit().
 {
  int rc;
  sqlite3_mutex_enter(db->mutex);
  rc = sqlite3LoadExtension(db, zFile, zProc, pzErrMsg);
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API void SQLITE_CDECL sqlite3_log (int iErrCode, const char * zFormat, ...)
Definition at line 22403 of file sqlite3.c.
References Sqlite3Config::xLog.
Referenced by sqlite3CantopenError(), sqlite3CorruptError(), sqlite3MisuseError(), sqlite3RunParser(), and sqlite3VdbeExec().
                                                                                {
  va_list ap; /* Vararg list */
  if(sqlite3GlobalConfig.xLog){
    va_start(ap, zFormat);
    renderLogMsg(iErrCode, zFormat, ap);
    va_end(ap);
  }
}
SQLITE_API void* SQLITE_STDCALL sqlite3_malloc (int)
Definition at line 20854 of file sqlite3.c.
References sqlite3_initialize(), and sqlite3Malloc().
Referenced by sqlite3BitvecBuiltinTest(), and sqlite3OsInit().
                                                     {
#ifndef SQLITE_OMIT_AUTOINIT
  if(sqlite3_initialize()) return 0;
#endif
  return n<=0 ? 0 : sqlite3Malloc(n);
}
SQLITE_API void* SQLITE_STDCALL sqlite3_malloc64 (sqlite3_uint64)
Definition at line 20860 of file sqlite3.c.
References sqlite3_initialize(), and sqlite3Malloc().
                                                                  {
#ifndef SQLITE_OMIT_AUTOINIT
  if(sqlite3_initialize()) return 0;
#endif
  return sqlite3Malloc(n);
}
SQLITE_API SQLITE_DEPRECATED int SQLITE_STDCALL sqlite3_memory_alarm (void(*)(void *, sqlite3_int64, int) , void * , sqlite3_int64)
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_memory_highwater (int resetFlag)
Definition at line 20763 of file sqlite3.c.
References sqlite3_status().
                                                                               {
  int n, mx;
  sqlite3_int64 res;
  sqlite3_status(SQLITE_STATUS_MEMORY_USED, &n, &mx, resetFlag);
  res = (sqlite3_int64)mx; /* Work around bug in Borland C. Ticket #3216 */
  return res;
}
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_memory_used (void)
Definition at line 20750 of file sqlite3.c.
References sqlite3_status().
Referenced by sqlite3_soft_heap_limit64().
                                                                 {
  int n, mx;
  sqlite3_int64 res;
  sqlite3_status(SQLITE_STATUS_MEMORY_USED, &n, &mx, 0);
  res = (sqlite3_int64)n; /* Work around bug in Borland C. Ticket #3216 */
  return res;
}
SQLITE_API char* SQLITE_CDECL sqlite3_mprintf (const char * , ...)
Definition at line 22331 of file sqlite3.c.
References sqlite3_initialize().
Referenced by sqlite3_get_table(), sqlite3InvalidFunction(), sqlite3ParseUri(), and sqlite3Pragma().
                                                                       {
  va_list ap;
  char *z;
#ifndef SQLITE_OMIT_AUTOINIT
  if(sqlite3_initialize()) return 0;
#endif
  va_start(ap, zFormat);
  z = sqlite3_vmprintf(zFormat, ap);
  va_end(ap);
  return z;
}
SQLITE_API sqlite3_uint64 SQLITE_STDCALL sqlite3_msize (void *)
Definition at line 21001 of file sqlite3.c.
References Sqlite3Config::m, and sqlite3_mem_methods::xSize.
                                                               {
  assert(sqlite3MemdebugNoType(p, (u8)~MEMTYPE_HEAP));
  assert(sqlite3MemdebugHasType(p, MEMTYPE_HEAP));
  return (sqlite3_uint64)sqlite3GlobalConfig.m.xSize(p);
}
SQLITE_API sqlite3_mutex* SQLITE_STDCALL sqlite3_mutex_alloc (int)
Definition at line 19185 of file sqlite3.c.
References Sqlite3Config::mutex, sqlite3_initialize(), and sqlite3MutexInit().
                                                                    {
#ifndef SQLITE_OMIT_AUTOINIT
  if(id<=SQLITE_MUTEX_RECURSIVE && sqlite3_initialize()) return 0
      ;
  if(id>SQLITE_MUTEX_RECURSIVE && sqlite3MutexInit()) return 0;
#endif
  return sqlite3GlobalConfig.mutex.xMutexAlloc(id);
}
SQLITE_API void SQLITE_STDCALL sqlite3_mutex_enter (sqlite3_mutex *)
Definition at line 19214 of file sqlite3.c.
References Sqlite3Config::mutex, and sqlite3_mutex_methods::xMutexEnter.
Referenced by sqlite3_auto_extension(), sqlite3_backup_finish(), sqlite3_backup_init(), sqlite3_backup_step(), sqlite3_blob_close(), sqlite3_blob_open(), sqlite3_blob_reopen(), sqlite3_busy_handler(), sqlite3_cancel_auto_extension(), sqlite3_clear_bindings(), sqlite3_collation_needed(), sqlite3_collation_needed16(), sqlite3_commit_hook(), sqlite3_create_collation16(), sqlite3_create_collation_v2(), sqlite3_create_function16(), sqlite3_create_function_v2(), sqlite3_db_release_memory(), sqlite3_db_status(), sqlite3_declare_vtab(), sqlite3_enable_load_extension(), sqlite3_errmsg(), sqlite3_errmsg16(), sqlite3_exec(), sqlite3_extended_result_codes(), sqlite3_file_control(), sqlite3_finalize(), sqlite3_free(), sqlite3_initialize(), sqlite3_load_extension(), sqlite3_next_stmt(), sqlite3_overload_function(), sqlite3_profile(), sqlite3_progress_handler(), sqlite3_randomness(), sqlite3_reset(), sqlite3_reset_auto_extension(), sqlite3_rollback_hook(), sqlite3_set_authorizer(), sqlite3_soft_heap_limit64(), sqlite3_status64(), sqlite3_step(), sqlite3_table_column_metadata(), sqlite3_test_control(), sqlite3_trace(), sqlite3_update_hook(), sqlite3_vfs_find(), sqlite3_vfs_register(), sqlite3_vfs_unregister(), sqlite3_vtab_config(), sqlite3_wal_checkpoint_v2(), sqlite3_wal_hook(), sqlite3AutoLoadExtensions(), sqlite3BackupUpdate(), sqlite3BtreeOpen(), sqlite3Malloc(), sqlite3Realloc(), sqlite3ScratchFree(), sqlite3ScratchMalloc(), and sqlite3TransferBindings().
                                                                    {
  if(p){
    sqlite3GlobalConfig.mutex.xMutexEnter(p);
  }
}
SQLITE_API void SQLITE_STDCALL sqlite3_mutex_free (sqlite3_mutex *)
Definition at line 19204 of file sqlite3.c.
References Sqlite3Config::mutex, and sqlite3_mutex_methods::xMutexFree.
Referenced by sqlite3_initialize(), and sqlite3LeaveMutexAndCloseZombie().
                                                                   {
  if(p){
    sqlite3GlobalConfig.mutex.xMutexFree(p);
  }
}
SQLITE_API int SQLITE_STDCALL sqlite3_mutex_held (sqlite3_mutex *)
SQLITE_API void SQLITE_STDCALL sqlite3_mutex_leave (sqlite3_mutex *)
Definition at line 19238 of file sqlite3.c.
References Sqlite3Config::mutex, and sqlite3_mutex_methods::xMutexLeave.
Referenced by sqlite3_auto_extension(), sqlite3_backup_init(), sqlite3_backup_step(), sqlite3_bind_double(), sqlite3_bind_int64(), sqlite3_bind_null(), sqlite3_bind_zeroblob(), sqlite3_blob_close(), sqlite3_blob_open(), sqlite3_blob_reopen(), sqlite3_busy_handler(), sqlite3_cancel_auto_extension(), sqlite3_clear_bindings(), sqlite3_collation_needed(), sqlite3_collation_needed16(), sqlite3_commit_hook(), sqlite3_create_collation16(), sqlite3_create_collation_v2(), sqlite3_create_function16(), sqlite3_create_function_v2(), sqlite3_db_release_memory(), sqlite3_db_status(), sqlite3_declare_vtab(), sqlite3_enable_load_extension(), sqlite3_errmsg(), sqlite3_errmsg16(), sqlite3_exec(), sqlite3_extended_result_codes(), sqlite3_file_control(), sqlite3_free(), sqlite3_initialize(), sqlite3_load_extension(), sqlite3_next_stmt(), sqlite3_overload_function(), sqlite3_profile(), sqlite3_progress_handler(), sqlite3_randomness(), sqlite3_reset(), sqlite3_reset_auto_extension(), sqlite3_rollback_hook(), sqlite3_set_authorizer(), sqlite3_soft_heap_limit64(), sqlite3_status64(), sqlite3_step(), sqlite3_table_column_metadata(), sqlite3_test_control(), sqlite3_trace(), sqlite3_update_hook(), sqlite3_vfs_find(), sqlite3_vfs_register(), sqlite3_vfs_unregister(), sqlite3_vtab_config(), sqlite3_wal_checkpoint_v2(), sqlite3_wal_hook(), sqlite3AutoLoadExtensions(), sqlite3BackupUpdate(), sqlite3BtreeOpen(), sqlite3LeaveMutexAndCloseZombie(), sqlite3Malloc(), sqlite3Realloc(), sqlite3ScratchFree(), sqlite3ScratchMalloc(), and sqlite3TransferBindings().
                                                                    {
  if(p){
    sqlite3GlobalConfig.mutex.xMutexLeave(p);
  }
}
SQLITE_API int SQLITE_STDCALL sqlite3_mutex_notheld (sqlite3_mutex *)
SQLITE_API int SQLITE_STDCALL sqlite3_mutex_try (sqlite3_mutex *)
Definition at line 19224 of file sqlite3.c.
References Sqlite3Config::mutex, and sqlite3_mutex_methods::xMutexTry.
                                                                 {
  int rc = SQLITE_OK;
  if(p){
    return sqlite3GlobalConfig.mutex.xMutexTry(p);
  }
  return rc;
}
SQLITE_API sqlite3_stmt* SQLITE_STDCALL sqlite3_next_stmt (sqlite3 * pDb, sqlite3_stmt * pStmt)
Definition at line 70482 of file sqlite3.c.
References sqlite3::mutex, Vdbe::pNext, sqlite3::pVdbe, sqlite3_mutex_enter(), and sqlite3_mutex_leave().
                                                                                            {
  sqlite3_stmt *pNext;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(pDb)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  sqlite3_mutex_enter(pDb->mutex);
  if(pStmt==0){
    pNext = (sqlite3_stmt*)pDb->pVdbe;
  }else{
    pNext = (sqlite3_stmt*)((Vdbe*)pStmt)->pNext;
  }
  sqlite3_mutex_leave(pDb->mutex);
  return pNext;
}
SQLITE_API int SQLITE_STDCALL sqlite3_open (const char * filename, sqlite3 ** ppDb)
Definition at line 130908 of file sqlite3.c.
 {
  return openDatabase(zFilename, ppDb,
                      SQLITE_OPEN_READWRITE |
      SQLITE_OPEN_CREATE, 0);
}
SQLITE_API int SQLITE_STDCALL sqlite3_open16 (const void * filename, sqlite3 ** ppDb)
Definition at line 130928 of file sqlite3.c.
References Db::pSchema, sqlite3_initialize(), sqlite3ApiExit(), sqlite3ValueFree(), sqlite3ValueNew(), and sqlite3ValueSetStr().
 {
  char const *zFilename8; /* zFilename encoded in UTF-8 instead of UTF-16 */
  sqlite3_value *pVal;
  int rc;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(ppDb==0) return SQLITE_MISUSE_BKPT;
#endif
  *ppDb = 0;
#ifndef SQLITE_OMIT_AUTOINIT
  rc = sqlite3_initialize();
  if(rc) return rc;
#endif
  if(zFilename==0) zFilename = "\000\000";
  pVal = sqlite3ValueNew(0);
  sqlite3ValueSetStr(pVal, -1, zFilename, SQLITE_UTF16NATIVE,
      SQLITE_STATIC);
  zFilename8 = sqlite3ValueText(pVal, SQLITE_UTF8);
  if(zFilename8){
    rc = openDatabase(zFilename8, ppDb,
                      SQLITE_OPEN_READWRITE |
      SQLITE_OPEN_CREATE, 0);
    assert(*ppDb || rc==SQLITE_NOMEM);
    if(rc==SQLITE_OK && !DbHasProperty(*ppDb, 0,
      DB_SchemaLoaded)){
      SCHEMA_ENC(*ppDb) = ENC(*ppDb) = SQLITE_UTF16NATIVE;
    }
  }else{
    rc = SQLITE_NOMEM;
  }
  sqlite3ValueFree(pVal);
  return sqlite3ApiExit(0, rc);
}
SQLITE_API int SQLITE_STDCALL sqlite3_open_v2 (const char * filename, sqlite3 ** ppDb, int flags, const char * zVfs)
Definition at line 130915 of file sqlite3.c.
 {
  return openDatabase(filename, ppDb, (unsigned int)flags, zVfs);
}
SQLITE_API int SQLITE_STDCALL sqlite3_os_end (void)
Definition at line 33028 of file sqlite3.c.
Referenced by sqlite3_shutdown().
                                                  {
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_os_init (void)
Definition at line 32929 of file sqlite3.c.
References sqlite3_vfs_register().
Referenced by sqlite3OsInit().
                                                   {
  /*
  ** The following macro defines an initializer for an sqlite3_vfs object.
  ** The name of the VFS is NAME. The pAppData is a pointer to a pointer
  ** to the "finder" function. (pAppData is a pointer to a pointer because
  ** silly C90 rules prohibit a void* from being cast to a function pointer
  ** and so we have to go through the intermediate pointer to avoid problems
  ** when compiling with -pedantic-errors on GCC.)
  **
  ** The FINDER parameter to this macro is the name of the pointer to the
  ** finder-function. The finder-function returns a pointer to the
  ** sqlite_io_methods object that implements the desired locking
  ** behaviors. See the division above that contains the IOMETHODS
  ** macro for addition information on finder-functions.
  **
  ** Most finders simply return a pointer to a fixed sqlite3_io_methods
  ** object. But the "autolockIoFinder" available on MacOSX does a little
  ** more than that; it looks at the filesystem type that hosts the
  ** database file and tries to choose an locking method appropriate for
  ** that filesystem time.
  */
  #define UNIXVFS(VFSNAME, FINDER) { \
    3, /* iVersion */ \
    sizeof(unixFile), /* szOsFile */ \
    MAX_PATHNAME, /* mxPathname */ \
    0, /* pNext */ \
    VFSNAME, /* zName */ \
    (void*)&FINDER, /* pAppData */ \
    unixOpen, /* xOpen */ \
    unixDelete, /* xDelete */ \
    unixAccess, /* xAccess */ \
    unixFullPathname, /* xFullPathname */ \
    unixDlOpen, /* xDlOpen */ \
    unixDlError, /* xDlError */ \
    unixDlSym, /* xDlSym */ \
    unixDlClose, /* xDlClose */ \
    unixRandomness, /* xRandomness */ \
    unixSleep, /* xSleep */ \
    unixCurrentTime, /* xCurrentTime */ \
    unixGetLastError, /* xGetLastError */ \
    unixCurrentTimeInt64, /* xCurrentTimeInt64 */ \
    unixSetSystemCall, /* xSetSystemCall */ \
    unixGetSystemCall, /* xGetSystemCall */ \
    unixNextSystemCall, /* xNextSystemCall */ \
  }
  /*
  ** All default VFSes for unix are contained in the following array.
  **
  ** Note that the sqlite3_vfs.pNext field of the VFS object is modified
  ** by the SQLite core when the VFS is registered. So the following
  ** array cannot be const.
  */
  static sqlite3_vfs aVfs[] = {
#if SQLITE_ENABLE_LOCKING_STYLE && defined(__APPLE__)
    UNIXVFS("unix", autolockIoFinder),
#elif OS_VXWORKS
    UNIXVFS("unix", vxworksIoFinder),
#else
    UNIXVFS("unix", posixIoFinder),
#endif
    UNIXVFS("unix-none", nolockIoFinder),
    UNIXVFS("unix-dotfile", dotlockIoFinder),
    UNIXVFS("unix-excl", posixIoFinder),
#if OS_VXWORKS
    UNIXVFS("unix-namedsem", semIoFinder),
#endif
#if SQLITE_ENABLE_LOCKING_STYLE || OS_VXWORKS
    UNIXVFS("unix-posix", posixIoFinder),
#endif
#if SQLITE_ENABLE_LOCKING_STYLE
    UNIXVFS("unix-flock", flockIoFinder),
#endif
#if SQLITE_ENABLE_LOCKING_STYLE && defined(__APPLE__)
    UNIXVFS("unix-afp", afpIoFinder),
    UNIXVFS("unix-nfs", nfsIoFinder),
    UNIXVFS("unix-proxy", proxyIoFinder),
#endif
  };
  unsigned int i; /* Loop counter */
  /* Double-check that the aSyscall[] array has been constructed
  ** correctly. See ticket [bb3a86e890c8e96ab] */
  assert(ArraySize(aSyscall)==25);
  /* Register all VFSes defined in the aVfs[] array */
  for(i=0; i<(sizeof(aVfs)/sizeof(sqlite3_vfs)); i++){
    sqlite3_vfs_register(&aVfs[i], i==0);
  }
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_overload_function (sqlite3 * , const char * zFuncName, int nArg)
Definition at line 129699 of file sqlite3.c.
References sqlite3::mutex, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3CreateFunc(), sqlite3FindFunction(), sqlite3InvalidFunction(), and sqlite3Strlen30().
Referenced by sqlite3RegisterBuiltinFunctions().
 {
  int nName = sqlite3Strlen30(zName);
  int rc = SQLITE_OK;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || zName==0 || nArg<-2){
    return SQLITE_MISUSE_BKPT;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  if(sqlite3FindFunction(db, zName, nName, nArg,
      SQLITE_UTF8, 0)==0){
    rc = sqlite3CreateFunc(db, zName, nArg, SQLITE_UTF8,
                           0, sqlite3InvalidFunction, 0, 0, 0);
  }
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_prepare (sqlite3 * db, const char * zSql, int nByte, sqlite3_stmt ** ppStmt, const char ** pzTail)
Definition at line 106361 of file sqlite3.c.
Referenced by sqlite3InitCallback().
 {
  int rc;
  rc = sqlite3LockAndPrepare(db,zSql,nBytes,0,0,ppStmt,pzTail);
  assert(rc==SQLITE_OK || ppStmt==0 || *ppStmt==0); /* VERIFY: F13021 */
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_prepare16 (sqlite3 * db, const void * zSql, int nByte, sqlite3_stmt ** ppStmt, const void ** pzTail)
Definition at line 106449 of file sqlite3.c.
 {
  int rc;
  rc = sqlite3Prepare16(db,zSql,nBytes,0,ppStmt,pzTail);
  assert(rc==SQLITE_OK || ppStmt==0 || *ppStmt==0); /* VERIFY: F13021 */
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_prepare16_v2 (sqlite3 * db, const void * zSql, int nByte, sqlite3_stmt ** ppStmt, const void ** pzTail)
Definition at line 106461 of file sqlite3.c.
 {
  int rc;
  rc = sqlite3Prepare16(db,zSql,nBytes,1,ppStmt,pzTail);
  assert(rc==SQLITE_OK || ppStmt==0 || *ppStmt==0); /* VERIFY: F13021 */
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_prepare_v2 (sqlite3 * db, const char * zSql, int nByte, sqlite3_stmt ** ppStmt, const char ** pzTail)
Definition at line 106373 of file sqlite3.c.
Referenced by sqlite3_exec().
 {
  int rc;
  rc = sqlite3LockAndPrepare(db,zSql,nBytes,1,0,ppStmt,pzTail);
  assert(rc==SQLITE_OK || ppStmt==0 || *ppStmt==0); /* VERIFY: F13021 */
  return rc;
}
SQLITE_API SQLITE_EXPERIMENTAL void* SQLITE_STDCALL sqlite3_profile (sqlite3 * , void(*)(void *, const char *, sqlite3_uint64) xProfile, void *)
Definition at line 129755 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pProfileArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3::xProfile.
 {
  void *pOld;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  pOld = db->pProfileArg;
  db->xProfile = xProfile;
  db->pProfileArg = pArg;
  sqlite3_mutex_leave(db->mutex);
  return pOld;
}
SQLITE_API void SQLITE_STDCALL sqlite3_progress_handler (sqlite3 * , int , int(*)(void *) , void *)
Definition at line 129438 of file sqlite3.c.
References sqlite3::mutex, sqlite3::nProgressOps, sqlite3::pProgressArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3::xProgress.
 {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  if(nOps>0){
    db->xProgress = xProgress;
    db->nProgressOps = (unsigned)nOps;
    db->pProgressArg = pArg;
  }else{
    db->xProgress = 0;
    db->nProgressOps = 0;
    db->pProgressArg = 0;
  }
  sqlite3_mutex_leave(db->mutex);
}
SQLITE_API void SQLITE_STDCALL sqlite3_randomness (int N, void * P)
Definition at line 22539 of file sqlite3.c.
References sqlite3_initialize(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_vfs_find(), sqlite3MutexAlloc(), and sqlite3OsRandomness().
Referenced by sqlite3_test_control(), sqlite3BitvecBuiltinTest(), sqlite3VdbeExec(), and sqlite3WalFrames().
                                                                    {
  unsigned char t;
  unsigned char *zBuf = pBuf;
  /* The "wsdPrng" macro will resolve to the pseudo-random number generator
  ** state vector. If writable static data is unsupported on the target,
  ** we have to locate the state vector at run-time. In the more common
  ** case where writable static data is supported, wsdPrng can refer directly
  ** to the "sqlite3Prng" state vector declared above.
  */
#ifdef SQLITE_OMIT_WSD
  struct sqlite3PrngType *p = &GLOBAL(struct sqlite3PrngType, sqlite3Prng);
# define wsdPrng p[0]
#else
# define wsdPrng sqlite3Prng
#endif
#if SQLITE_THREADSAFE
  sqlite3_mutex *mutex;
#endif
#ifndef SQLITE_OMIT_AUTOINIT
  if(sqlite3_initialize()) return;
#endif
#if SQLITE_THREADSAFE
  mutex = sqlite3MutexAlloc(SQLITE_MUTEX_STATIC_PRNG);
#endif
  sqlite3_mutex_enter(mutex);
  if(N<=0 || pBuf==0){
    wsdPrng.isInit = 0;
    sqlite3_mutex_leave(mutex);
    return;
  }
  /* Initialize the state of the random number generator once,
  ** the first time this routine is called. The seed value does
  ** not need to contain a lot of randomness since we are not
  ** trying to do secure encryption or anything like that...
  **
  ** Nothing in this file or anywhere else in SQLite does any kind of
  ** encryption. The RC4 algorithm is being used as a PRNG (pseudo-random
  ** number generator) not as an encryption device.
  */
  if(!wsdPrng.isInit){
    int i;
    char k[256];
    wsdPrng.j = 0;
    wsdPrng.i = 0;
    sqlite3OsRandomness(sqlite3_vfs_find(0), 256, k);
    for(i=0; i<256; i++){
      wsdPrng.s[i] = (u8)i;
    }
    for(i=0; i<256; i++){
      wsdPrng.j += wsdPrng.s[i] + k[i];
      t = wsdPrng.s[wsdPrng.j];
      wsdPrng.s[wsdPrng.j] = wsdPrng.s[i];
      wsdPrng.s[i] = t;
    }
    wsdPrng.isInit = 1;
  }
  assert(N>0);
  do{
    wsdPrng.i++;
    t = wsdPrng.s[wsdPrng.i];
    wsdPrng.j += t;
    wsdPrng.s[wsdPrng.i] = wsdPrng.s[wsdPrng.j];
    wsdPrng.s[wsdPrng.j] = t;
    t += wsdPrng.s[wsdPrng.i];
    *(zBuf++) = wsdPrng.s[t];
  }while(--N);
  sqlite3_mutex_leave(mutex);
}
SQLITE_API void* SQLITE_STDCALL sqlite3_realloc (void * , int)
Definition at line 21119 of file sqlite3.c.
References sqlite3_initialize(), and sqlite3Realloc().
                                                                  {
#ifndef SQLITE_OMIT_AUTOINIT
  if(sqlite3_initialize()) return 0;
#endif
  if(n<0) n = 0; /* IMP: R-26507-47431 */
  return sqlite3Realloc(pOld, n);
}
SQLITE_API void* SQLITE_STDCALL sqlite3_realloc64 (void * , sqlite3_uint64)
Definition at line 21126 of file sqlite3.c.
References sqlite3_initialize(), and sqlite3Realloc().
Referenced by sqlite3DbRealloc().
                                                                               {
#ifndef SQLITE_OMIT_AUTOINIT
  if(sqlite3_initialize()) return 0;
#endif
  return sqlite3Realloc(pOld, n);
}
SQLITE_API int SQLITE_STDCALL sqlite3_release_memory (int)
Definition at line 20545 of file sqlite3.c.
Referenced by sqlite3_soft_heap_limit64().
                                                           {
#ifdef SQLITE_ENABLE_MEMORY_MANAGEMENT
  return sqlite3PcacheReleaseMemory(n);
#else
  /* IMPLEMENTATION-OF: R-34391-24921 The sqlite3_release_memory() routine
  ** is a no-op returning zero if SQLite is not compiled with
  ** SQLITE_ENABLE_MEMORY_MANAGEMENT. */
  UNUSED_PARAMETER(n);
  return 0;
#endif
}
SQLITE_API int SQLITE_STDCALL sqlite3_reset (sqlite3_stmt * pStmt)
Definition at line 69097 of file sqlite3.c.
References Vdbe::db, sqlite3::mutex, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3VdbeReset(), and sqlite3VdbeRewind().
Referenced by sqlite3_step().
                                                                {
  int rc;
  if(pStmt==0){
    rc = SQLITE_OK;
  }else{
    Vdbe *v = (Vdbe*)pStmt;
    sqlite3_mutex_enter(v->db->mutex);
    rc = sqlite3VdbeReset(v);
    sqlite3VdbeRewind(v);
    assert((rc & (v->db->errMask))==rc);
    rc = sqlite3ApiExit(v->db, rc);
    sqlite3_mutex_leave(v->db->mutex);
  }
  return rc;
}
SQLITE_API void SQLITE_STDCALL sqlite3_reset_auto_extension (void)
Definition at line 103079 of file sqlite3.c.
References sqlite3_free(), sqlite3_initialize(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3MutexAlloc().
Referenced by sqlite3_shutdown().
                                                                 {
#ifndef SQLITE_OMIT_AUTOINIT
  if(sqlite3_initialize()==SQLITE_OK)
#endif
  {
#if SQLITE_THREADSAFE
    sqlite3_mutex *mutex = sqlite3MutexAlloc(
      SQLITE_MUTEX_STATIC_MASTER);
#endif
    wsdAutoextInit;
    sqlite3_mutex_enter(mutex);
    sqlite3_free(wsdAutoext.aExt);
    wsdAutoext.aExt = 0;
    wsdAutoext.nExt = 0;
    sqlite3_mutex_leave(mutex);
  }
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_blob (sqlite3_context * , const void * , int , void(*)(void *))
Definition at line 69259 of file sqlite3.c.
 {
  assert(n>=0);
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  setResultStrOrError(pCtx, z, n, 0, xDel);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_blob64 (sqlite3_context * , const void * , sqlite3_uint64 , void(*)(void *))
Definition at line 69269 of file sqlite3.c.
 {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  assert(xDel!=SQLITE_DYNAMIC);
  if(n>0x7fffffff){
    (void)invokeValueDestructor(z, xDel, pCtx);
  }else{
    setResultStrOrError(pCtx, z, (int)n, 0, xDel);
  }
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_double (sqlite3_context * , double)
Definition at line 69283 of file sqlite3.c.
References sqlite3_context::pOut, and sqlite3VdbeMemSetDouble().
                                                                                        {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  sqlite3VdbeMemSetDouble(pCtx->pOut, rVal);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_error (sqlite3_context * , const char * , int)
Definition at line 69287 of file sqlite3.c.
References sqlite3_context::fErrorOrAux, sqlite3_context::isError, sqlite3_context::pOut, and sqlite3VdbeMemSetStr().
Referenced by sqlite3InvalidFunction().
                                                                                                {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  pCtx->isError = SQLITE_ERROR;
  pCtx->fErrorOrAux = 1;
  sqlite3VdbeMemSetStr(pCtx->pOut, z, n, SQLITE_UTF8,
      SQLITE_TRANSIENT);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_error16 (sqlite3_context * , const void * , int)
Definition at line 69294 of file sqlite3.c.
References sqlite3_context::fErrorOrAux, and sqlite3_context::isError.
                                                                                                  {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  pCtx->isError = SQLITE_ERROR;
  pCtx->fErrorOrAux = 1;
  sqlite3VdbeMemSetStr(pCtx->pOut, z, n, SQLITE_UTF16NATIVE,
      SQLITE_TRANSIENT);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_error_code (sqlite3_context * , int)
Definition at line 69375 of file sqlite3.c.
References sqlite3_context::fErrorOrAux, sqlite3_value::flags, sqlite3_context::isError, sqlite3_context::pOut, sqlite3ErrStr(), and sqlite3VdbeMemSetStr().
                                                                                            {
  pCtx->isError = errCode;
  pCtx->fErrorOrAux = 1;
#ifdef SQLITE_DEBUG
  if(pCtx->pVdbe) pCtx->pVdbe->rcApp = errCode;
#endif
  if(pCtx->pOut->flags & MEM_Null){
    sqlite3VdbeMemSetStr(pCtx->pOut, sqlite3ErrStr(errCode), -1,
                         SQLITE_UTF8, SQLITE_STATIC);
  }
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_error_nomem (sqlite3_context *)
Definition at line 69397 of file sqlite3.c.
References sqlite3_value::db, sqlite3_context::fErrorOrAux, sqlite3_context::isError, sqlite3::mallocFailed, sqlite3_context::pOut, and sqlite3VdbeMemSetNull().
                                                                                {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  sqlite3VdbeMemSetNull(pCtx->pOut);
  pCtx->isError = SQLITE_NOMEM;
  pCtx->fErrorOrAux = 1;
  pCtx->pOut->db->mallocFailed = 1;
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_error_toobig (sqlite3_context *)
Definition at line 69388 of file sqlite3.c.
References sqlite3_context::fErrorOrAux, sqlite3_context::isError, sqlite3_context::pOut, and sqlite3VdbeMemSetStr().
                                                                                 {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  pCtx->isError = SQLITE_TOOBIG;
  pCtx->fErrorOrAux = 1;
  sqlite3VdbeMemSetStr(pCtx->pOut, "string or blob too big", -1,
                       SQLITE_UTF8, SQLITE_STATIC);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_int (sqlite3_context * , int)
Definition at line 69301 of file sqlite3.c.
References sqlite3_context::pOut, and sqlite3VdbeMemSetInt64().
                                                                                  {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  sqlite3VdbeMemSetInt64(pCtx->pOut, (i64)iVal);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_int64 (sqlite3_context * , sqlite3_int64)
Definition at line 69305 of file sqlite3.c.
References sqlite3_context::pOut, and sqlite3VdbeMemSetInt64().
                                                                                    {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  sqlite3VdbeMemSetInt64(pCtx->pOut, iVal);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_null (sqlite3_context *)
Definition at line 69309 of file sqlite3.c.
References sqlite3_context::pOut, and sqlite3VdbeMemSetNull().
                                                                         {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  sqlite3VdbeMemSetNull(pCtx->pOut);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_text (sqlite3_context * , const char * , int , void(*)(void *))
Definition at line 69313 of file sqlite3.c.
 {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  setResultStrOrError(pCtx, z, n, SQLITE_UTF8, xDel);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_text16 (sqlite3_context * , const void * , int , void(*)(void *))
Definition at line 69339 of file sqlite3.c.
 {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  setResultStrOrError(pCtx, z, n, SQLITE_UTF16NATIVE, xDel);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_text16be (sqlite3_context * , const void * , int , void(*)(void *))
Definition at line 69348 of file sqlite3.c.
 {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  setResultStrOrError(pCtx, z, n, SQLITE_UTF16BE, xDel);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_text16le (sqlite3_context * , const void * , int , void(*)(void *))
Definition at line 69357 of file sqlite3.c.
 {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  setResultStrOrError(pCtx, z, n, SQLITE_UTF16LE, xDel);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_text64 (sqlite3_context * , const char * , sqlite3_uint64 , void(*)(void *) , unsigned char encoding)
Definition at line 69322 of file sqlite3.c.
 {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  assert(xDel!=SQLITE_DYNAMIC);
  if(enc==SQLITE_UTF16) enc = SQLITE_UTF16NATIVE;
  if(n>0x7fffffff){
    (void)invokeValueDestructor(z, xDel, pCtx);
  }else{
    setResultStrOrError(pCtx, z, (int)n, enc, xDel);
  }
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_value (sqlite3_context * , sqlite3_value *)
Definition at line 69367 of file sqlite3.c.
References sqlite3_context::pOut, and sqlite3VdbeMemCopy().
                                                                                                 {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  sqlite3VdbeMemCopy(pCtx->pOut, pValue);
}
SQLITE_API void SQLITE_STDCALL sqlite3_result_zeroblob (sqlite3_context * , int n)
Definition at line 69371 of file sqlite3.c.
References sqlite3_context::pOut, and sqlite3VdbeMemSetZeroBlob().
                                                                                    {
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  sqlite3VdbeMemSetZeroBlob(pCtx->pOut, n);
}
SQLITE_API void* SQLITE_STDCALL sqlite3_rollback_hook (sqlite3 * , void(*)(void *) , void *)
Definition at line 129832 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pRollbackArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3::xRollbackCallback.
 {
  void *pRet;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  pRet = db->pRollbackArg;
  db->xRollbackCallback = xCallback;
  db->pRollbackArg = pArg;
  sqlite3_mutex_leave(db->mutex);
  return pRet;
}
SQLITE_API int SQLITE_STDCALL sqlite3_rtree_geometry_callback (sqlite3 * db, const char * zGeom, int(*)(sqlite3_rtree_geometry *, int, sqlite3_rtree_dbl *, int *) xGeom, void * pContext)
SQLITE_API int SQLITE_STDCALL sqlite3_rtree_query_callback (sqlite3 * db, const char * zQueryFunc, int(*)(sqlite3_rtree_query_info *) xQueryFunc, void * pContext, void(*)(void *) xDestructor)
SQLITE_API int SQLITE_STDCALL sqlite3_set_authorizer (sqlite3 * , int(*)(void *, int, const char *, const char *, const char *, const char *) xAuth, void * pUserData)
Definition at line 90618 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pAuthArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ExpirePreparedStatements(), and sqlite3::xAuth.
 {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  db->xAuth = (sqlite3_xauth)xAuth;
  db->pAuthArg = pArg;
  sqlite3ExpirePreparedStatements(db);
  sqlite3_mutex_leave(db->mutex);
  return SQLITE_OK;
}
SQLITE_API void SQLITE_STDCALL sqlite3_set_auxdata (sqlite3_context * , int N, void * , void(*)(void *))
Definition at line 69748 of file sqlite3.c.
References sqlite3_context::fErrorOrAux, AuxData::iArg, AuxData::iOp, sqlite3_context::iOp, sqlite3_context::isError, AuxData::pAux, Vdbe::pAuxData, AuxData::pNext, sqlite3_context::pVdbe, and AuxData::xDelete.
 {
  AuxData *pAuxData;
  Vdbe *pVdbe = pCtx->pVdbe;
  assert(sqlite3_mutex_held(pCtx->pOut->db->mutex));
  if(iArg<0) goto failed;
#ifdef SQLITE_ENABLE_STAT3_OR_STAT4
  if(pVdbe==0) goto failed;
#else
  assert(pVdbe!=0);
#endif
  for(pAuxData=pVdbe->pAuxData; pAuxData; pAuxData=pAuxData->pNext){
    if(pAuxData->iOp==pCtx->iOp && pAuxData->iArg==iArg) break;
  }
  if(pAuxData==0){
    pAuxData = sqlite3DbMallocZero(pVdbe->db, sizeof(
      AuxData));
    if(!pAuxData) goto failed;
    pAuxData->iOp = pCtx->iOp;
    pAuxData->iArg = iArg;
    pAuxData->pNext = pVdbe->pAuxData;
    pVdbe->pAuxData = pAuxData;
    if(pCtx->fErrorOrAux==0){
      pCtx->isError = 0;
      pCtx->fErrorOrAux = 1;
    }
  }else if(pAuxData->xDelete){
    pAuxData->xDelete(pAuxData->pAux);
  }
  pAuxData->pAux = pAux;
  pAuxData->xDelete = xDelete;
  return;
failed:
  if(xDelete){
    xDelete(pAux);
  }
}
SQLITE_API int SQLITE_STDCALL sqlite3_shutdown (void)
Definition at line 128272 of file sqlite3.c.
References Sqlite3Config::isInit, Sqlite3Config::isMallocInit, Sqlite3Config::isMutexInit, Sqlite3Config::isPCacheInit, sqlite3_data_directory, sqlite3_os_end(), sqlite3_reset_auto_extension(), sqlite3_temp_directory, sqlite3MallocEnd(), sqlite3MutexEnd(), and sqlite3PcacheShutdown().
                                                    {
#ifdef SQLITE_OMIT_WSD
  int rc = sqlite3_wsd_init(4096, 24);
  if(rc!=SQLITE_OK){
    return rc;
  }
#endif
  if(sqlite3GlobalConfig.isInit){
#ifdef SQLITE_EXTRA_SHUTDOWN
    void SQLITE_EXTRA_SHUTDOWN(void);
    SQLITE_EXTRA_SHUTDOWN();
#endif
    sqlite3_os_end();
    sqlite3_reset_auto_extension();
    sqlite3GlobalConfig.isInit = 0;
  }
  if(sqlite3GlobalConfig.isPCacheInit){
    sqlite3PcacheShutdown();
    sqlite3GlobalConfig.isPCacheInit = 0;
  }
  if(sqlite3GlobalConfig.isMallocInit){
    sqlite3MallocEnd();
    sqlite3GlobalConfig.isMallocInit = 0;
#ifndef SQLITE_OMIT_SHUTDOWN_DIRECTORIES
    /* The heap subsystem has now been shutdown and these values are supposed
    ** to be NULL or point to memory that was obtained from sqlite3_malloc(),
    ** which would rely on that heap subsystem; therefore, make sure these
    ** values cannot refer to heap memory that was just invalidated when the
    ** heap subsystem was shutdown. This is only done if the current call to
    ** this function resulted in the heap subsystem actually being shutdown.
    */
    sqlite3_data_directory = 0;
    sqlite3_temp_directory = 0;
#endif
  }
  if(sqlite3GlobalConfig.isMutexInit){
    sqlite3MutexEnd();
    sqlite3GlobalConfig.isMutexInit = 0;
  }
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_sleep (int)
Definition at line 131267 of file sqlite3.c.
References sqlite3_vfs_find(), and sqlite3OsSleep().
                                                   {
  sqlite3_vfs *pVfs;
  int rc;
  pVfs = sqlite3_vfs_find(0);
  if(pVfs==0) return 0;
  /* This function works in milliseconds, but the underlying OsSleep()
  ** API uses microseconds. Hence the 1000's.
  */
  rc = (sqlite3OsSleep(pVfs, 1000*ms)/1000);
  return rc;
}
SQLITE_API char* SQLITE_CDECL sqlite3_snprintf (int , char * , const char * , ...)
Definition at line 22371 of file sqlite3.c.
Referenced by sqlite3VdbeList(), and sqlite3VdbeMemStringify().
                                                                                           {
  char *z;
  va_list ap;
  va_start(ap,zFormat);
  z = sqlite3_vsnprintf(n, zBuf, zFormat, ap);
  va_end(ap);
  return z;
}
SQLITE_API SQLITE_DEPRECATED void SQLITE_STDCALL sqlite3_soft_heap_limit (int N)
Definition at line 20678 of file sqlite3.c.
References sqlite3_soft_heap_limit64().
                                                             {
  if(n<0) n = 0;
  sqlite3_soft_heap_limit64(n);
}
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_soft_heap_limit64 (sqlite3_int64 N)
Definition at line 20658 of file sqlite3.c.
References sqlite3_initialize(), sqlite3_memory_used(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3_release_memory().
Referenced by sqlite3_soft_heap_limit(), and sqlite3Pragma().
                                                                                  {
  sqlite3_int64 priorLimit;
  sqlite3_int64 excess;
#ifndef SQLITE_OMIT_AUTOINIT
  int rc = sqlite3_initialize();
  if(rc) return -1;
#endif
  sqlite3_mutex_enter(mem0.mutex);
  priorLimit = mem0.alarmThreshold;
  sqlite3_mutex_leave(mem0.mutex);
  if(n<0) return priorLimit;
  if(n>0){
    sqlite3MemoryAlarm(softHeapLimitEnforcer, 0, n);
  }else{
    sqlite3MemoryAlarm(0, 0, 0);
  }
  excess = sqlite3_memory_used() - n;
  if(excess>0) sqlite3_release_memory((int)(excess & 0x7fffffff));
  return priorLimit;
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_sourceid (void)
Definition at line 128039 of file sqlite3.c.
Referenced by sqlite3CantopenError(), sqlite3CorruptError(), and sqlite3MisuseError().
{ return SQLITE_SOURCE_ID; }
SQLITE_API const char* SQLITE_STDCALL sqlite3_sql (sqlite3_stmt * pStmt)
Definition at line 64871 of file sqlite3.c.
References Vdbe::isPrepareV2, and Vdbe::zSql.
Referenced by sqlite3Reprepare().
                                                                      {
  Vdbe *p = (Vdbe *)pStmt;
  return (p && p->isPrepareV2) ? p->zSql : 0;
}
SQLITE_API int SQLITE_STDCALL sqlite3_status (int op, int * pCurrent, int * pHighwater, int resetFlag)
Definition at line 15134 of file sqlite3.c.
References sqlite3_status64().
Referenced by sqlite3_memory_highwater(), and sqlite3_memory_used().
                                                                                                   {
  sqlite3_int64 iCur, iHwtr;
  int rc;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(pCurrent==0 || pHighwater==0) return SQLITE_MISUSE_BKPT;
#endif
  rc = sqlite3_status64(op, &iCur, &iHwtr, resetFlag);
  if(rc==0){
    *pCurrent = (int)iCur;
    *pHighwater = (int)iHwtr;
  }
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_status64 (int op, sqlite3_int64 * pCurrent, sqlite3_int64 * pHighwater, int resetFlag)
Definition at line 15109 of file sqlite3.c.
References sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3MallocMutex(), and sqlite3Pcache1Mutex().
Referenced by sqlite3_status().
 {
  sqlite3_mutex *pMutex;
  wsdStatInit;
  if(op<0 || op>=ArraySize(wsdStat.nowValue)){
    return SQLITE_MISUSE_BKPT;
  }
#ifdef SQLITE_ENABLE_API_ARMOR
  if(pCurrent==0 || pHighwater==0) return SQLITE_MISUSE_BKPT;
#endif
  pMutex = statMutex[op] ? sqlite3Pcache1Mutex() :
      sqlite3MallocMutex();
  sqlite3_mutex_enter(pMutex);
  *pCurrent = wsdStat.nowValue[op];
  *pHighwater = wsdStat.mxValue[op];
  if(resetFlag){
    wsdStat.mxValue[op] = wsdStat.nowValue[op];
  }
  sqlite3_mutex_leave(pMutex);
  (void)pMutex; /* Prevent warning when SQLITE_THREADSAFE=0 */
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_step (sqlite3_stmt *)
Definition at line 69570 of file sqlite3.c.
References Vdbe::db, Vdbe::doingRerun, sqlite3::mallocFailed, sqlite3::mutex, Vdbe::pc, sqlite3::pErr, Vdbe::rc, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_reset(), sqlite3_value_text(), sqlite3ApiExit(), sqlite3DbFree(), sqlite3DbStrDup(), sqlite3Reprepare(), and Vdbe::zErrMsg.
Referenced by sqlite3_exec().
                                                               {
  int rc = SQLITE_OK; /* Result from sqlite3Step() */
  int rc2 = SQLITE_OK; /* Result from sqlite3Reprepare() */
  Vdbe *v = (Vdbe*)pStmt; /* the prepared statement */
  int cnt = 0; /* Counter to prevent infinite loop of reprepares */
  sqlite3 *db; /* The database connection */
  if(vdbeSafetyNotNull(v)){
    return SQLITE_MISUSE_BKPT;
  }
  db = v->db;
  sqlite3_mutex_enter(db->mutex);
  v->doingRerun = 0;
  while((rc = sqlite3Step(v))==SQLITE_SCHEMA
         && cnt++ < SQLITE_MAX_SCHEMA_RETRY){
    int savedPc = v->pc;
    rc2 = rc = sqlite3Reprepare(v);
    if(rc!=SQLITE_OK) break;
    sqlite3_reset(pStmt);
    if(savedPc>=0) v->doingRerun = 1;
    assert(v->expired==0);
  }
  if(rc2!=SQLITE_OK){
    /* This case occurs after failing to recompile an sql statement.
    ** The error message from the SQL compiler has already been loaded
    ** into the database handle. This block copies the error message
    ** from the database handle into the statement and sets the statement
    ** program counter to 0 to ensure that when the statement is
    ** finalized or reset the parser error message is available via
    ** sqlite3_errmsg() and sqlite3_errcode().
    */
    const char *zErr = (const char *)sqlite3_value_text(db->
      pErr);
    sqlite3DbFree(db, v->zErrMsg);
    if(!db->mallocFailed){
      v->zErrMsg = sqlite3DbStrDup(db, zErr);
      v->rc = rc2;
    } else {
      v->zErrMsg = 0;
      v->rc = rc = SQLITE_NOMEM;
    }
  }
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_stmt_busy (sqlite3_stmt *)
Definition at line 70471 of file sqlite3.c.
References Vdbe::magic, and Vdbe::pc.
                                                                    {
  Vdbe *v = (Vdbe*)pStmt;
  return v!=0 && v->pc>=0 && v->magic==VDBE_MAGIC_RUN;
}
SQLITE_API int SQLITE_STDCALL sqlite3_stmt_readonly (sqlite3_stmt * pStmt)
Definition at line 70464 of file sqlite3.c.
References Vdbe::readOnly.
                                                                        {
  return pStmt ? ((Vdbe*)pStmt)->readOnly : 1;
}
SQLITE_API SQLITE_EXPERIMENTAL int SQLITE_STDCALL sqlite3_stmt_scanstatus (sqlite3_stmt * pStmt, int idx, int iScanStatusOp, void * pOut)
SQLITE_API SQLITE_EXPERIMENTAL void SQLITE_STDCALL sqlite3_stmt_scanstatus_reset (sqlite3_stmt *)
SQLITE_API int SQLITE_STDCALL sqlite3_stmt_status (sqlite3_stmt * , int op, int resetFlg)
Definition at line 70503 of file sqlite3.c.
References Vdbe::aCounter.
                                                                                             {
  Vdbe *pVdbe = (Vdbe*)pStmt;
  u32 v;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!pStmt){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  v = pVdbe->aCounter[op];
  if(resetFlag) pVdbe->aCounter[op] = 0;
  return (int)v;
}
SQLITE_API int SQLITE_STDCALL sqlite3_strglob (const char * zGlob, const char * zStr)
Definition at line 97197 of file sqlite3.c.
                                                                                            {
  return patternCompare((u8*)zGlobPattern, (u8*)zString, &globInfo, 0)==0;
}
SQLITE_API int SQLITE_STDCALL sqlite3_stricmp (const char * , const char *)
Definition at line 23691 of file sqlite3.c.
Referenced by sqlite3_blob_open(), sqlite3_table_column_metadata(), sqlite3AddPrimaryKey(), sqlite3CodeVerifyNamedSchema(), sqlite3CreateForeignKey(), sqlite3CreateIndex(), sqlite3DbNameToBtree(), sqlite3DropTrigger(), sqlite3FindDbName(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3FkCheck(), sqlite3FkLocateIndex(), sqlite3IdListIndex(), sqlite3Insert(), sqlite3IsRowid(), sqlite3MatchSpanName(), sqlite3Pragma(), sqlite3TriggerList(), sqlite3Update(), sqlite3VdbeExec(), and sqlite3WithAdd().
                                                                                    {
  register unsigned char *a, *b;
  if(zLeft==0){
    return zRight ? -1 : 0;
  }else if(zRight==0){
    return 1;
  }
  a = (unsigned char *)zLeft;
  b = (unsigned char *)zRight;
  while(*a!=0 && UpperToLower[*a]==UpperToLower[*b]){ a++; b++; }
  return UpperToLower[*a] - UpperToLower[*b];
}
SQLITE_API int SQLITE_STDCALL sqlite3_strnicmp (const char * , const char * , int)
Definition at line 23703 of file sqlite3.c.
Referenced by sqlite3_compileoption_used(), sqlite3_complete(), sqlite3BeginTrigger(), sqlite3CheckObjectName(), sqlite3CreateIndex(), sqlite3DropTable(), sqlite3InitCallback(), sqlite3JoinType(), sqlite3MatchSpanName(), and sqlite3Pragma().
                                                                                            {
  register unsigned char *a, *b;
  if(zLeft==0){
    return zRight ? -1 : 0;
  }else if(zRight==0){
    return 1;
  }
  a = (unsigned char *)zLeft;
  b = (unsigned char *)zRight;
  while(N-- > 0 && *a!=0 && UpperToLower[*a]==UpperToLower[*b]){ a++; b++; }
  return N<0 ? 0 : UpperToLower[*a] - UpperToLower[*b];
}
SQLITE_API int SQLITE_STDCALL sqlite3_table_column_metadata (sqlite3 * db, const char * zDbName, const char * zTableName, const char * zColumnName, char const ** pzDataType, char const ** pzCollSeq, int * pNotNull, int * pPrimaryKey, int * pAutoinc)
Definition at line 131149 of file sqlite3.c.
References Table::aCol, Column::colFlags, Table::iPKey, sqlite3::mutex, Table::nCol, Column::notNull, Table::pSelect, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_stricmp(), sqlite3ApiExit(), sqlite3BtreeEnterAll(), sqlite3BtreeLeaveAll(), sqlite3DbFree(), sqlite3ErrorWithMsg(), sqlite3FindTable(), sqlite3Init(), sqlite3IsRowid(), sqlite3MPrintf(), Table::tabFlags, Column::zColl, Column::zName, and Column::zType.
 {
  int rc;
  char *zErrMsg = 0;
  Table *pTab = 0;
  Column *pCol = 0;
  int iCol = 0;
  char const *zDataType = 0;
  char const *zCollSeq = 0;
  int notnull = 0;
  int primarykey = 0;
  int autoinc = 0;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db) || zTableName==0){
    return SQLITE_MISUSE_BKPT;
  }
#endif
  /* Ensure the database schema has been loaded */
  sqlite3_mutex_enter(db->mutex);
  sqlite3BtreeEnterAll(db);
  rc = sqlite3Init(db, &zErrMsg);
  if(SQLITE_OK!=rc){
    goto error_out;
  }
  /* Locate the table in question */
  pTab = sqlite3FindTable(db, zTableName, zDbName);
  if(!pTab || pTab->pSelect){
    pTab = 0;
    goto error_out;
  }
  /* Find the column for which info is requested */
  if(zColumnName==0){
    /* Query for existance of table only */
  }else{
    for(iCol=0; iCol<pTab->nCol; iCol++){
      pCol = &pTab->aCol[iCol];
      if(0==sqlite3StrICmp(pCol->zName, zColumnName)){
        break;
      }
    }
    if(iCol==pTab->nCol){
      if(HasRowid(pTab) && sqlite3IsRowid(zColumnName)){
        iCol = pTab->iPKey;
        pCol = iCol>=0 ? &pTab->aCol[iCol] : 0;
      }else{
        pTab = 0;
        goto error_out;
      }
    }
  }
  /* The following block stores the meta information that will be returned
  ** to the caller in local variables zDataType, zCollSeq, notnull, primarykey
  ** and autoinc. At this point there are two possibilities:
  **
  ** 1. The specified column name was rowid", "oid" or "_rowid_"
  ** and there is no explicitly declared IPK column.
  **
  ** 2. The table is not a view and the column name identified an
  ** explicitly declared column. Copy meta information from *pCol.
  */
  if(pCol){
    zDataType = pCol->zType;
    zCollSeq = pCol->zColl;
    notnull = pCol->notNull!=0;
    primarykey = (pCol->colFlags & COLFLAG_PRIMKEY)!=0;
    autoinc = pTab->iPKey==iCol && (pTab->tabFlags &
      TF_Autoincrement)!=0;
  }else{
    zDataType = "INTEGER";
    primarykey = 1;
  }
  if(!zCollSeq){
    zCollSeq = "BINARY";
  }
error_out:
  sqlite3BtreeLeaveAll(db);
  /* Whether the function call succeeded or failed, set the output parameters
  ** to whatever their local counterparts contain. If an error did occur,
  ** this has the effect of zeroing all output parameters.
  */
  if(pzDataType) *pzDataType = zDataType;
  if(pzCollSeq) *pzCollSeq = zCollSeq;
  if(pNotNull) *pNotNull = notnull;
  if(pPrimaryKey) *pPrimaryKey = primarykey;
  if(pAutoinc) *pAutoinc = autoinc;
  if(SQLITE_OK==rc && !pTab){
    sqlite3DbFree(db, zErrMsg);
    zErrMsg = sqlite3MPrintf(db, "no such table column: %s.%s", zTableName,
        zColumnName);
    rc = SQLITE_ERROR;
  }
  sqlite3ErrorWithMsg(db, rc, (zErrMsg?"%s":0), zErrMsg);
  sqlite3DbFree(db, zErrMsg);
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_CDECL sqlite3_test_control (int op, ...)
Definition at line 131330 of file sqlite3.c.
References sqlite3::aDb, sqlite3::sqlite3InitInfo::busy, Sqlite3Config::isInit, sqlite3::mutex, sqlite3::sqlite3InitInfo::newTnum, Db::pBt, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3_randomness(), sqlite3BenignMallocHooks(), sqlite3BitvecBuiltinTest(), sqlite3BtreeSetPageSize(), sqlite3FaultSim(), sqlite3KeywordCode(), sqlite3PendingByte, sqlite3PrngRestoreState(), sqlite3PrngSaveState(), sqlite3ResetAllSchemasOfConnection(), sqlite3ScratchFree(), sqlite3ScratchMalloc(), and sqlite3Strlen30().
                                                             {
  int rc = 0;
#ifndef SQLITE_OMIT_BUILTIN_TEST
  va_list ap;
  va_start(ap, op);
  switch(op){
    /*
    ** Save the current state of the PRNG.
    */
    case SQLITE_TESTCTRL_PRNG_SAVE: {
      sqlite3PrngSaveState();
      break;
    }
    /*
    ** Restore the state of the PRNG to the last state saved using
    ** PRNG_SAVE. If PRNG_SAVE has never before been called, then
    ** this verb acts like PRNG_RESET.
    */
    case SQLITE_TESTCTRL_PRNG_RESTORE: {
      sqlite3PrngRestoreState();
      break;
    }
    /*
    ** Reset the PRNG back to its uninitialized state. The next call
    ** to sqlite3_randomness() will reseed the PRNG using a single call
    ** to the xRandomness method of the default VFS.
    */
    case SQLITE_TESTCTRL_PRNG_RESET: {
      sqlite3_randomness(0,0);
      break;
    }
    /*
    ** sqlite3_test_control(BITVEC_TEST, size, program)
    **
    ** Run a test against a Bitvec object of size. The program argument
    ** is an array of integers that defines the test. Return -1 on a
    ** memory allocation error, 0 on success, or non-zero for an error.
    ** See the sqlite3BitvecBuiltinTest() for additional information.
    */
    case SQLITE_TESTCTRL_BITVEC_TEST: {
      int sz = va_arg(ap, int);
      int *aProg = va_arg(ap, int*);
      rc = sqlite3BitvecBuiltinTest(sz, aProg);
      break;
    }
    /*
    ** sqlite3_test_control(FAULT_INSTALL, xCallback)
    **
    ** Arrange to invoke xCallback() whenever sqlite3FaultSim() is called,
    ** if xCallback is not NULL.
    **
    ** As a test of the fault simulator mechanism itself, sqlite3FaultSim(0)
    ** is called immediately after installing the new callback and the return
    ** value from sqlite3FaultSim(0) becomes the return from
    ** sqlite3_test_control().
    */
    case SQLITE_TESTCTRL_FAULT_INSTALL: {
      /* MSVC is picky about pulling func ptrs from va lists.
      ** http://support.microsoft.com/kb/47961
      ** sqlite3GlobalConfig.xTestCallback = va_arg(ap, int(*)(int));
      */
      typedef int(*TESTCALLBACKFUNC_t)(int);
      sqlite3GlobalConfig.xTestCallback = va_arg(ap, TESTCALLBACKFUNC_t);
      rc = sqlite3FaultSim(0);
      break;
    }
    /*
    ** sqlite3_test_control(BENIGN_MALLOC_HOOKS, xBegin, xEnd)
    **
    ** Register hooks to call to indicate which malloc() failures
    ** are benign.
    */
    case SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS: {
      typedef void (*void_function)(void);
      void_function xBenignBegin;
      void_function xBenignEnd;
      xBenignBegin = va_arg(ap, void_function);
      xBenignEnd = va_arg(ap, void_function);
      sqlite3BenignMallocHooks(xBenignBegin, xBenignEnd);
      break;
    }
    /*
    ** sqlite3_test_control(SQLITE_TESTCTRL_PENDING_BYTE, unsigned int X)
    **
    ** Set the PENDING byte to the value in the argument, if X>0.
    ** Make no changes if X==0. Return the value of the pending byte
    ** as it existing before this routine was called.
    **
    ** IMPORTANT: Changing the PENDING byte from 0x40000000 results in
    ** an incompatible database file format. Changing the PENDING byte
    ** while any database connection is open results in undefined and
    ** deleterious behavior.
    */
    case SQLITE_TESTCTRL_PENDING_BYTE: {
      rc = PENDING_BYTE;
#ifndef SQLITE_OMIT_WSD
      {
        unsigned int newVal = va_arg(ap, unsigned int);
        if(newVal) sqlite3PendingByte = newVal;
      }
#endif
      break;
    }
    /*
    ** sqlite3_test_control(SQLITE_TESTCTRL_ASSERT, int X)
    **
    ** This action provides a run-time test to see whether or not
    ** assert() was enabled at compile-time. If X is true and assert()
    ** is enabled, then the return value is true. If X is true and
    ** assert() is disabled, then the return value is zero. If X is
    ** false and assert() is enabled, then the assertion fires and the
    ** process aborts. If X is false and assert() is disabled, then the
    ** return value is zero.
    */
    case SQLITE_TESTCTRL_ASSERT: {
      volatile int x = 0;
      assert((x = va_arg(ap,int))!=0);
      rc = x;
      break;
    }
    /*
    ** sqlite3_test_control(SQLITE_TESTCTRL_ALWAYS, int X)
    **
    ** This action provides a run-time test to see how the ALWAYS and
    ** NEVER macros were defined at compile-time.
    **
    ** The return value is ALWAYS(X).
    **
    ** The recommended test is X==2. If the return value is 2, that means
    ** ALWAYS() and NEVER() are both no-op pass-through macros, which is the
    ** default setting. If the return value is 1, then ALWAYS() is either
    ** hard-coded to true or else it asserts if its argument is false.
    ** The first behavior (hard-coded to true) is the case if
    ** SQLITE_TESTCTRL_ASSERT shows that assert() is disabled and the second
    ** behavior (assert if the argument to ALWAYS() is false) is the case if
    ** SQLITE_TESTCTRL_ASSERT shows that assert() is enabled.
    **
    ** The run-time test procedure might look something like this:
    **
    ** if(sqlite3_test_control(SQLITE_TESTCTRL_ALWAYS, 2)==2){
    ** // ALWAYS() and NEVER() are no-op pass-through macros
    ** }else if(sqlite3_test_control(SQLITE_TESTCTRL_ASSERT, 1)){
    ** // ALWAYS(x) asserts that x is true. NEVER(x) asserts x is false.
    ** }else{
    ** // ALWAYS(x) is a constant 1. NEVER(x) is a constant 0.
    ** }
    */
    case SQLITE_TESTCTRL_ALWAYS: {
      int x = va_arg(ap,int);
      rc = ALWAYS(x);
      break;
    }
    /*
    ** sqlite3_test_control(SQLITE_TESTCTRL_BYTEORDER);
    **
    ** The integer returned reveals the byte-order of the computer on which
    ** SQLite is running:
    **
    ** 1 big-endian, determined at run-time
    ** 10 little-endian, determined at run-time
    ** 432101 big-endian, determined at compile-time
    ** 123410 little-endian, determined at compile-time
    */
    case SQLITE_TESTCTRL_BYTEORDER: {
      rc = SQLITE_BYTEORDER*100 + SQLITE_LITTLEENDIAN*10 +
      SQLITE_BIGENDIAN;
      break;
    }
    /* sqlite3_test_control(SQLITE_TESTCTRL_RESERVE, sqlite3 *db, int N)
    **
    ** Set the nReserve size to N for the main database on the database
    ** connection db.
    */
    case SQLITE_TESTCTRL_RESERVE: {
      sqlite3 *db = va_arg(ap, sqlite3*);
      int x = va_arg(ap,int);
      sqlite3_mutex_enter(db->mutex);
      sqlite3BtreeSetPageSize(db->aDb[0].pBt, 0, x, 0);
      sqlite3_mutex_leave(db->mutex);
      break;
    }
    /* sqlite3_test_control(SQLITE_TESTCTRL_OPTIMIZATIONS, sqlite3 *db, int N)
    **
    ** Enable or disable various optimizations for testing purposes. The
    ** argument N is a bitmask of optimizations to be disabled. For normal
    ** operation N should be 0. The idea is that a test program (like the
    ** SQL Logic Test or SLT test module) can run the same SQL multiple times
    ** with various optimizations disabled to verify that the same answer
    ** is obtained in every case.
    */
    case SQLITE_TESTCTRL_OPTIMIZATIONS: {
      sqlite3 *db = va_arg(ap, sqlite3*);
      db->dbOptFlags = (u16)(va_arg(ap, int) & 0xffff);
      break;
    }
#ifdef SQLITE_N_KEYWORD
    /* sqlite3_test_control(SQLITE_TESTCTRL_ISKEYWORD, const char *zWord)
    **
    ** If zWord is a keyword recognized by the parser, then return the
    ** number of keywords. Or if zWord is not a keyword, return 0.
    **
    ** This test feature is only available in the amalgamation since
    ** the SQLITE_N_KEYWORD macro is not defined in this file if SQLite
    ** is built using separate source files.
    */
    case SQLITE_TESTCTRL_ISKEYWORD: {
      const char *zWord = va_arg(ap, const char*);
      int n = sqlite3Strlen30(zWord);
      rc = (sqlite3KeywordCode((u8*)zWord, n)!=TK_ID) ?
      SQLITE_N_KEYWORD : 0;
      break;
    }
#endif
    /* sqlite3_test_control(SQLITE_TESTCTRL_SCRATCHMALLOC, sz, &pNew, pFree);
    **
    ** Pass pFree into sqlite3ScratchFree().
    ** If sz>0 then allocate a scratch buffer into pNew.
    */
    case SQLITE_TESTCTRL_SCRATCHMALLOC: {
      void *pFree, **ppNew;
      int sz;
      sz = va_arg(ap, int);
      ppNew = va_arg(ap, void**);
      pFree = va_arg(ap, void*);
      if(sz) *ppNew = sqlite3ScratchMalloc(sz);
      sqlite3ScratchFree(pFree);
      break;
    }
    /* sqlite3_test_control(SQLITE_TESTCTRL_LOCALTIME_FAULT, int onoff);
    **
    ** If parameter onoff is non-zero, configure the wrappers so that all
    ** subsequent calls to localtime() and variants fail. If onoff is zero,
    ** undo this setting.
    */
    case SQLITE_TESTCTRL_LOCALTIME_FAULT: {
      sqlite3GlobalConfig.bLocaltimeFault = va_arg(ap, int);
      break;
    }
    /* sqlite3_test_control(SQLITE_TESTCTRL_NEVER_CORRUPT, int);
    **
    ** Set or clear a flag that indicates that the database file is always well-
    ** formed and never corrupt. This flag is clear by default, indicating that
    ** database files might have arbitrary corruption. Setting the flag during
    ** testing causes certain assert() statements in the code to be activated
    ** that demonstrat invariants on well-formed database files.
    */
    case SQLITE_TESTCTRL_NEVER_CORRUPT: {
      sqlite3GlobalConfig.neverCorrupt = va_arg(ap, int);
      break;
    }
    /* sqlite3_test_control(SQLITE_TESTCTRL_VDBE_COVERAGE, xCallback, ptr);
    **
    ** Set the VDBE coverage callback function to xCallback with context
    ** pointer ptr.
    */
    case SQLITE_TESTCTRL_VDBE_COVERAGE: {
#ifdef SQLITE_VDBE_COVERAGE
      typedef void (*branch_callback)(void*,int,u8,u8);
      sqlite3GlobalConfig.xVdbeBranch = va_arg(ap,branch_callback);
      sqlite3GlobalConfig.pVdbeBranchArg = va_arg(ap,void*);
#endif
      break;
    }
    /* sqlite3_test_control(SQLITE_TESTCTRL_SORTER_MMAP, db, nMax); */
    case SQLITE_TESTCTRL_SORTER_MMAP: {
      sqlite3 *db = va_arg(ap, sqlite3*);
      db->nMaxSorterMmap = va_arg(ap, int);
      break;
    }
    /* sqlite3_test_control(SQLITE_TESTCTRL_ISINIT);
    **
    ** Return SQLITE_OK if SQLite has been initialized and SQLITE_ERROR if
    ** not.
    */
    case SQLITE_TESTCTRL_ISINIT: {
      if(sqlite3GlobalConfig.isInit==0) rc = SQLITE_ERROR;
      break;
    }
    /* sqlite3_test_control(SQLITE_TESTCTRL_IMPOSTER, db, dbName, onOff, tnum);
    **
    ** This test control is used to create imposter tables. "db" is a pointer
    ** to the database connection. dbName is the database name (ex: "main" or
    ** "temp") which will receive the imposter. "onOff" turns imposter mode on
    ** or off. "tnum" is the root page of the b-tree to which the imposter
    ** table should connect.
    **
    ** Enable imposter mode only when the schema has already been parsed. Then
    ** run a single CREATE TABLE statement to construct the imposter table in
    ** the parsed schema. Then turn imposter mode back off again.
    **
    ** If onOff==0 and tnum>0 then reset the schema for all databases, causing
    ** the schema to be reparsed the next time it is needed. This has the
    ** effect of erasing all imposter tables.
    */
    case SQLITE_TESTCTRL_IMPOSTER: {
      sqlite3 *db = va_arg(ap, sqlite3*);
      sqlite3_mutex_enter(db->mutex);
      db->init.iDb = sqlite3FindDbName(db, va_arg(ap,const char*));
      db->init.busy = db->init.imposterTable = va_arg(ap,int);
      db->init.newTnum = va_arg(ap,int);
      if(db->init.busy==0 && db->init.newTnum>0){
        sqlite3ResetAllSchemasOfConnection(db);
      }
      sqlite3_mutex_leave(db->mutex);
      break;
    }
  }
  va_end(ap);
#endif /* SQLITE_OMIT_BUILTIN_TEST */
  return rc;
}
SQLITE_API SQLITE_DEPRECATED void SQLITE_STDCALL sqlite3_thread_cleanup (void)
Definition at line 131141 of file sqlite3.c.
                                                           {
}
SQLITE_API int SQLITE_STDCALL sqlite3_threadsafe (void)
Definition at line 128050 of file sqlite3.c.
{ return SQLITE_THREADSAFE; }
SQLITE_API int SQLITE_STDCALL sqlite3_total_changes (sqlite3 *)
Definition at line 128865 of file sqlite3.c.
References sqlite3::nTotalChange.
                                                                {
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  return db->nTotalChange;
}
SQLITE_API void* SQLITE_STDCALL sqlite3_trace (sqlite3 * , void(*)(void *, const char *) xTrace, void *)
Definition at line 129731 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pTraceArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3::xTrace.
                                                                                                         {
  void *pOld;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  pOld = db->pTraceArg;
  db->xTrace = xTrace;
  db->pTraceArg = pArg;
  sqlite3_mutex_leave(db->mutex);
  return pOld;
}
SQLITE_API SQLITE_DEPRECATED int SQLITE_STDCALL sqlite3_transfer_bindings (sqlite3_stmt * , sqlite3_stmt *)
Definition at line 70434 of file sqlite3.c.
References Vdbe::expired, Vdbe::expmask, Vdbe::isPrepareV2, Vdbe::nVar, and sqlite3TransferBindings().
                                                                                                       {
  Vdbe *pFrom = (Vdbe*)pFromStmt;
  Vdbe *pTo = (Vdbe*)pToStmt;
  if(pFrom->nVar!=pTo->nVar){
    return SQLITE_ERROR;
  }
  if(pTo->isPrepareV2 && pTo->expmask){
    pTo->expired = 1;
  }
  if(pFrom->isPrepareV2 && pFrom->expmask){
    pFrom->expired = 1;
  }
  return sqlite3TransferBindings(pFromStmt, pToStmt);
}
SQLITE_API int SQLITE_STDCALL sqlite3_unlock_notify (sqlite3 * pBlocked, void(*)(void **apArg, int nArg) xNotify, void * pNotifyArg)
SQLITE_API void* SQLITE_STDCALL sqlite3_update_hook (sqlite3 * , void(*)(void *, int, char const *, char const *, sqlite3_int64) , void *)
Definition at line 129807 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pUpdateArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3::xUpdateCallback.
 {
  void *pRet;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  pRet = db->pUpdateArg;
  db->xUpdateCallback = xCallback;
  db->pUpdateArg = pArg;
  sqlite3_mutex_leave(db->mutex);
  return pRet;
}
SQLITE_API int SQLITE_STDCALL sqlite3_uri_boolean (const char * zFile, const char * zParam, int bDefault)
Definition at line 131688 of file sqlite3.c.
References sqlite3_uri_parameter(), and sqlite3GetBoolean().
Referenced by sqlite3PagerOpen().
                                                                                                       {
  const char *z = sqlite3_uri_parameter(zFilename, zParam);
  bDflt = bDflt!=0;
  return z ? sqlite3GetBoolean(z, bDflt) : bDflt;
}
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_uri_int64 (const char * , const char * , sqlite3_int64)
Definition at line 131697 of file sqlite3.c.
References sqlite3_uri_parameter(), and sqlite3DecOrHexToI64().
 {
  const char *z = sqlite3_uri_parameter(zFilename, zParam);
  sqlite3_int64 v;
  if(z && sqlite3DecOrHexToI64(z, &v)==SQLITE_OK){
    bDflt = v;
  }
  return bDflt;
}
SQLITE_API const char* SQLITE_STDCALL sqlite3_uri_parameter (const char * zFilename, const char * zParam)
Definition at line 131673 of file sqlite3.c.
References sqlite3Strlen30().
Referenced by sqlite3_uri_boolean(), and sqlite3_uri_int64().
                                                                                                      {
  if(zFilename==0 || zParam==0) return 0;
  zFilename += sqlite3Strlen30(zFilename) + 1;
  while(zFilename[0]){
    int x = strcmp(zFilename, zParam);
    zFilename += sqlite3Strlen30(zFilename) + 1;
    if(x==0) return zFilename;
    zFilename += sqlite3Strlen30(zFilename) + 1;
  }
  return 0;
}
SQLITE_API void* SQLITE_STDCALL sqlite3_user_data (sqlite3_context *)
Definition at line 69621 of file sqlite3.c.
References sqlite3_context::pFunc, and FuncDef::pUserData.
                                                                     {
  assert(p && p->pFunc);
  return p->pFunc->pUserData;
}
SQLITE_API const void* SQLITE_STDCALL sqlite3_value_blob (sqlite3_value *)
Definition at line 69140 of file sqlite3.c.
References sqlite3_value::flags, sqlite3_value::n, sqlite3_value_text(), sqlite3VdbeMemExpandBlob(), and sqlite3_value::z.
Referenced by sqlite3_column_blob().
                                                                             {
  Mem *p = (Mem*)pVal;
  if(p->flags & (MEM_Blob|MEM_Str)){
    sqlite3VdbeMemExpandBlob(p);
    p->flags |= MEM_Blob;
    return p->n ? p->z : 0;
  }else{
    return sqlite3_value_text(pVal);
  }
}
SQLITE_API int SQLITE_STDCALL sqlite3_value_bytes (sqlite3_value *)
Definition at line 69150 of file sqlite3.c.
References sqlite3ValueBytes().
Referenced by sqlite3_column_bytes().
                                                                      {
  return sqlite3ValueBytes(pVal, SQLITE_UTF8);
}
SQLITE_API int SQLITE_STDCALL sqlite3_value_bytes16 (sqlite3_value *)
Definition at line 69153 of file sqlite3.c.
References sqlite3ValueBytes().
Referenced by sqlite3_column_bytes16().
                                                                        {
  return sqlite3ValueBytes(pVal, SQLITE_UTF16NATIVE);
}
SQLITE_API double SQLITE_STDCALL sqlite3_value_double (sqlite3_value *)
Definition at line 69156 of file sqlite3.c.
References sqlite3VdbeRealValue().
Referenced by sqlite3_column_double().
                                                                          {
  return sqlite3VdbeRealValue((Mem*)pVal);
}
SQLITE_API int SQLITE_STDCALL sqlite3_value_int (sqlite3_value *)
Definition at line 69159 of file sqlite3.c.
References sqlite3VdbeIntValue().
Referenced by sqlite3_column_int().
                                                                    {
  return (int)sqlite3VdbeIntValue((Mem*)pVal);
}
SQLITE_API sqlite3_int64 SQLITE_STDCALL sqlite3_value_int64 (sqlite3_value *)
Definition at line 69162 of file sqlite3.c.
References sqlite3VdbeIntValue().
Referenced by sqlite3_column_int64().
                                                                               {
  return sqlite3VdbeIntValue((Mem*)pVal);
}
SQLITE_API int SQLITE_STDCALL sqlite3_value_numeric_type (sqlite3_value *)
Definition at line 71083 of file sqlite3.c.
References sqlite3_value_type().
                                                                             {
  int eType = sqlite3_value_type(pVal);
  if(eType==SQLITE_TEXT){
    Mem *pMem = (Mem*)pVal;
    applyNumericAffinity(pMem, 0);
    eType = sqlite3_value_type(pVal);
  }
  return eType;
}
SQLITE_API const unsigned char* SQLITE_STDCALL sqlite3_value_text (sqlite3_value *)
Definition at line 69165 of file sqlite3.c.
References sqlite3ValueText().
Referenced by sqlite3_column_text(), sqlite3_errmsg(), sqlite3_step(), sqlite3_value_blob(), and sqlite3VdbeExec().
                                                                                      {
  return (const unsigned char *)sqlite3ValueText(pVal,
      SQLITE_UTF8);
}
SQLITE_API const void* SQLITE_STDCALL sqlite3_value_text16 (sqlite3_value *)
Definition at line 69169 of file sqlite3.c.
References sqlite3ValueText().
Referenced by sqlite3_column_decltype16(), sqlite3_column_name16(), sqlite3_column_text16(), and sqlite3_errmsg16().
                                                                               {
  return sqlite3ValueText(pVal, SQLITE_UTF16NATIVE);
}
SQLITE_API const void* SQLITE_STDCALL sqlite3_value_text16be (sqlite3_value *)
Definition at line 69172 of file sqlite3.c.
References sqlite3ValueText().
                                                                                 {
  return sqlite3ValueText(pVal, SQLITE_UTF16BE);
}
SQLITE_API const void* SQLITE_STDCALL sqlite3_value_text16le (sqlite3_value *)
Definition at line 69175 of file sqlite3.c.
References sqlite3ValueText().
                                                                                 {
  return sqlite3ValueText(pVal, SQLITE_UTF16LE);
}
SQLITE_API int SQLITE_STDCALL sqlite3_value_type (sqlite3_value *)
Definition at line 69183 of file sqlite3.c.
References sqlite3_value::flags.
Referenced by sqlite3_bind_value(), sqlite3_column_type(), and sqlite3_value_numeric_type().
                                                                     {
  static const u8 aType[] = {
     SQLITE_BLOB, /* 0x00 */
     SQLITE_NULL, /* 0x01 */
     SQLITE_TEXT, /* 0x02 */
     SQLITE_NULL, /* 0x03 */
     SQLITE_INTEGER, /* 0x04 */
     SQLITE_NULL, /* 0x05 */
     SQLITE_INTEGER, /* 0x06 */
     SQLITE_NULL, /* 0x07 */
     SQLITE_FLOAT, /* 0x08 */
     SQLITE_NULL, /* 0x09 */
     SQLITE_FLOAT, /* 0x0a */
     SQLITE_NULL, /* 0x0b */
     SQLITE_INTEGER, /* 0x0c */
     SQLITE_NULL, /* 0x0d */
     SQLITE_INTEGER, /* 0x0e */
     SQLITE_NULL, /* 0x0f */
     SQLITE_BLOB, /* 0x10 */
     SQLITE_NULL, /* 0x11 */
     SQLITE_TEXT, /* 0x12 */
     SQLITE_NULL, /* 0x13 */
     SQLITE_INTEGER, /* 0x14 */
     SQLITE_NULL, /* 0x15 */
     SQLITE_INTEGER, /* 0x16 */
     SQLITE_NULL, /* 0x17 */
     SQLITE_FLOAT, /* 0x18 */
     SQLITE_NULL, /* 0x19 */
     SQLITE_FLOAT, /* 0x1a */
     SQLITE_NULL, /* 0x1b */
     SQLITE_INTEGER, /* 0x1c */
     SQLITE_NULL, /* 0x1d */
     SQLITE_INTEGER, /* 0x1e */
     SQLITE_NULL, /* 0x1f */
  };
  return aType[pVal->flags&MEM_AffMask];
}
SQLITE_API sqlite3_vfs* SQLITE_STDCALL sqlite3_vfs_find (const char * zVfsName)
Definition at line 16775 of file sqlite3.c.
References sqlite3_vfs::pNext, sqlite3_initialize(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3MutexAlloc(), and sqlite3_vfs::zName.
Referenced by sqlite3_randomness(), sqlite3_sleep(), and sqlite3ParseUri().
                                                                         {
  sqlite3_vfs *pVfs = 0;
#if SQLITE_THREADSAFE
  sqlite3_mutex *mutex;
#endif
#ifndef SQLITE_OMIT_AUTOINIT
  int rc = sqlite3_initialize();
  if(rc) return 0;
#endif
#if SQLITE_THREADSAFE
  mutex = sqlite3MutexAlloc(SQLITE_MUTEX_STATIC_MASTER);
#endif
  sqlite3_mutex_enter(mutex);
  for(pVfs = vfsList; pVfs; pVfs=pVfs->pNext){
    if(zVfs==0) break;
    if(strcmp(zVfs, pVfs->zName)==0) break;
  }
  sqlite3_mutex_leave(mutex);
  return pVfs;
}
SQLITE_API int SQLITE_STDCALL sqlite3_vfs_register (sqlite3_vfs * , int makeDflt)
Definition at line 16821 of file sqlite3.c.
References sqlite3_vfs::pNext, sqlite3_initialize(), sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3MutexAlloc().
Referenced by sqlite3_os_init().
                                                                                   {
  MUTEX_LOGIC(sqlite3_mutex *mutex;)
#ifndef SQLITE_OMIT_AUTOINIT
  int rc = sqlite3_initialize();
  if(rc) return rc;
#endif
#ifdef SQLITE_ENABLE_API_ARMOR
  if(pVfs==0) return SQLITE_MISUSE_BKPT;
#endif
  MUTEX_LOGIC(mutex = sqlite3MutexAlloc(
      SQLITE_MUTEX_STATIC_MASTER);)
  sqlite3_mutex_enter(mutex);
  vfsUnlink(pVfs);
  if(makeDflt || vfsList==0){
    pVfs->pNext = vfsList;
    vfsList = pVfs;
  }else{
    pVfs->pNext = vfsList->pNext;
    vfsList->pNext = pVfs;
  }
  assert(vfsList);
  sqlite3_mutex_leave(mutex);
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_vfs_unregister (sqlite3_vfs *)
Definition at line 16849 of file sqlite3.c.
References sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3MutexAlloc().
                                                                       {
#if SQLITE_THREADSAFE
  sqlite3_mutex *mutex = sqlite3MutexAlloc(
      SQLITE_MUTEX_STATIC_MASTER);
#endif
  sqlite3_mutex_enter(mutex);
  vfsUnlink(pVfs);
  sqlite3_mutex_leave(mutex);
  return SQLITE_OK;
}
SQLITE_API char* SQLITE_STDCALL sqlite3_vmprintf (const char * , va_list)
Definition at line 22306 of file sqlite3.c.
References sqlite3_initialize(), sqlite3StrAccumFinish(), sqlite3StrAccumInit(), sqlite3VXPrintf(), and StrAccum::useMalloc.
                                                                                 {
  char *z;
  char zBase[SQLITE_PRINT_BUF_SIZE];
  StrAccum acc;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(zFormat==0){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
#ifndef SQLITE_OMIT_AUTOINIT
  if(sqlite3_initialize()) return 0;
#endif
  sqlite3StrAccumInit(&acc, zBase, sizeof(zBase),
      SQLITE_MAX_LENGTH);
  acc.useMalloc = 2;
  sqlite3VXPrintf(&acc, 0, zFormat, ap);
  z = sqlite3StrAccumFinish(&acc);
  return z;
}
SQLITE_API char* SQLITE_STDCALL sqlite3_vsnprintf (int , char * , const char * , va_list)
Definition at line 22356 of file sqlite3.c.
References sqlite3StrAccumFinish(), sqlite3StrAccumInit(), sqlite3VXPrintf(), and StrAccum::useMalloc.
                                                                                                     {
  StrAccum acc;
  if(n<=0) return zBuf;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(zBuf==0 || zFormat==0) {
    (void)SQLITE_MISUSE_BKPT;
    if(zBuf) zBuf[0] = 0;
    return zBuf;
  }
#endif
  sqlite3StrAccumInit(&acc, zBuf, n, 0);
  acc.useMalloc = 0;
  sqlite3VXPrintf(&acc, 0, zFormat, ap);
  return sqlite3StrAccumFinish(&acc);
}
SQLITE_API int SQLITE_CDECL sqlite3_vtab_config (sqlite3 * , int op, ...)
Definition at line 115677 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pVtabCtx, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3Error().
                                                                         {
  va_list ap;
  int rc = SQLITE_OK;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return SQLITE_MISUSE_BKPT;
#endif
  sqlite3_mutex_enter(db->mutex);
  va_start(ap, op);
  switch(op){
    case SQLITE_VTAB_CONSTRAINT_SUPPORT: {
      VtabCtx *p = db->pVtabCtx;
      if(!p){
        rc = SQLITE_MISUSE_BKPT;
      }else{
        assert(p->pTab==0 || (p->pTab->tabFlags & TF_Virtual)!=0);
        p->pVTable->bConstraint = (u8)va_arg(ap, int);
      }
      break;
    }
    default:
      rc = SQLITE_MISUSE_BKPT;
      break;
  }
  va_end(ap);
  if(rc!=SQLITE_OK) sqlite3Error(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
}
SQLITE_API int SQLITE_STDCALL sqlite3_vtab_on_conflict (sqlite3 *)
Definition at line 115659 of file sqlite3.c.
References sqlite3::vtabOnConflict.
                                                                   {
  static const unsigned char aMap[] = {
    SQLITE_ROLLBACK, SQLITE_ABORT, SQLITE_FAIL,
      SQLITE_IGNORE, SQLITE_REPLACE
  };
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return SQLITE_MISUSE_BKPT;
#endif
  assert(OE_Rollback==1 && OE_Abort==2 && OE_Fail==3);
  assert(OE_Ignore==4 && OE_Replace==5);
  assert(db->vtabOnConflict>=1 && db->vtabOnConflict<=5);
  return (int)aMap[db->vtabOnConflict-1];
}
SQLITE_API int SQLITE_STDCALL sqlite3_wal_autocheckpoint (sqlite3 * db, int N)
Definition at line 129886 of file sqlite3.c.
References sqlite3_wal_hook(), and sqlite3WalDefaultHook().
Referenced by sqlite3Pragma().
                                                                                 {
#ifdef SQLITE_OMIT_WAL
  UNUSED_PARAMETER(db);
  UNUSED_PARAMETER(nFrame);
#else
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return SQLITE_MISUSE_BKPT;
#endif
  if(nFrame>0){
    sqlite3_wal_hook(db, sqlite3WalDefaultHook,
      SQLITE_INT_TO_PTR(nFrame));
  }else{
    sqlite3_wal_hook(db, 0, 0);
  }
#endif
  return SQLITE_OK;
}
SQLITE_API int SQLITE_STDCALL sqlite3_wal_checkpoint (sqlite3 * db, const char * zDb)
Definition at line 129989 of file sqlite3.c.
References sqlite3_wal_checkpoint_v2().
Referenced by sqlite3WalDefaultHook().
                                                                                  {
  /* EVIDENCE-OF: R-41613-20553 The sqlite3_wal_checkpoint(D,X) is equivalent to
  ** sqlite3_wal_checkpoint_v2(D,X,SQLITE_CHECKPOINT_PASSIVE,0,0). */
  return sqlite3_wal_checkpoint_v2(db,zDb,
      SQLITE_CHECKPOINT_PASSIVE,0,0);
}
SQLITE_API int SQLITE_STDCALL sqlite3_wal_checkpoint_v2 (sqlite3 * db, const char * zDb, int eMode, int * pnLog, int * pnCkpt)
Definition at line 129934 of file sqlite3.c.
References sqlite3::busyHandler, sqlite3::mutex, BusyHandler::nBusy, sqlite3_mutex_enter(), sqlite3_mutex_leave(), sqlite3ApiExit(), sqlite3Checkpoint(), sqlite3Error(), sqlite3ErrorWithMsg(), and sqlite3FindDbName().
Referenced by sqlite3_wal_checkpoint().
 {
#ifdef SQLITE_OMIT_WAL
  return SQLITE_OK;
#else
  int rc; /* Return code */
  int iDb = SQLITE_MAX_ATTACHED; /* sqlite3.aDb[] index of db to checkpoint */
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)) return SQLITE_MISUSE_BKPT;
#endif
  /* Initialize the output variables to -1 in case an error occurs. */
  if(pnLog) *pnLog = -1;
  if(pnCkpt) *pnCkpt = -1;
  assert(SQLITE_CHECKPOINT_PASSIVE==0);
  assert(SQLITE_CHECKPOINT_FULL==1);
  assert(SQLITE_CHECKPOINT_RESTART==2);
  assert(SQLITE_CHECKPOINT_TRUNCATE==3);
  if(eMode<SQLITE_CHECKPOINT_PASSIVE || eMode>SQLITE_CHECKPOINT_TRUNCATE){
    /* EVIDENCE-OF: R-03996-12088 The M parameter must be a valid checkpoint
    ** mode: */
    return SQLITE_MISUSE;
  }
  sqlite3_mutex_enter(db->mutex);
  if(zDb && zDb[0]){
    iDb = sqlite3FindDbName(db, zDb);
  }
  if(iDb<0){
    rc = SQLITE_ERROR;
    sqlite3ErrorWithMsg(db, SQLITE_ERROR, "unknown database: %s", zDb);
  }else{
    db->busyHandler.nBusy = 0;
    rc = sqlite3Checkpoint(db, iDb, eMode, pnLog, pnCkpt);
    sqlite3Error(db, rc);
  }
  rc = sqlite3ApiExit(db, rc);
  sqlite3_mutex_leave(db->mutex);
  return rc;
#endif
}
SQLITE_API void* SQLITE_STDCALL sqlite3_wal_hook (sqlite3 * , int(*)(void *, sqlite3 *, const char *, int) , void *)
Definition at line 129907 of file sqlite3.c.
References sqlite3::mutex, sqlite3::pWalArg, sqlite3_mutex_enter(), sqlite3_mutex_leave(), and sqlite3::xWalCallback.
Referenced by sqlite3_wal_autocheckpoint().
 {
#ifndef SQLITE_OMIT_WAL
  void *pRet;
#ifdef SQLITE_ENABLE_API_ARMOR
  if(!sqlite3SafetyCheckOk(db)){
    (void)SQLITE_MISUSE_BKPT;
    return 0;
  }
#endif
  sqlite3_mutex_enter(db->mutex);
  pRet = db->pWalArg;
  db->xWalCallback = xCallback;
  db->pWalArg = pArg;
  sqlite3_mutex_leave(db->mutex);
  return pRet;
#else
  return 0;
#endif
}
Variable Documentation
SQLITE_API SQLITE_EXTERN char* sqlite3_data_directory
Definition at line 4941 of file sqlite3.h.
Referenced by sqlite3_shutdown().
SQLITE_API SQLITE_EXTERN char* sqlite3_temp_directory
Definition at line 4904 of file sqlite3.h.
Referenced by sqlite3_shutdown(), and sqlite3Pragma().
SQLITE_API SQLITE_EXTERN const char sqlite3_version[]
Definition at line 148 of file sqlite3.h.