sqlite3_mem_methods Struct Reference
#include <sqlite3.h>
Data Fields
void *(* xMalloc)(int)
void(* xFree)(void *)
void *(* xRealloc)(void *, int)
int(* xSize)(void *)
int(* xRoundup)(int)
int(* xInit)(void *)
void(* xShutdown)(void *)
void * pAppData
Detailed Description
Definition at line 1671 of file sqlite3.c.
Field Documentation
void * pAppData
Definition at line 1679 of file sqlite3.c.
Referenced by sqlite3MallocEnd(), and sqlite3MallocInit().
void(* xFree)(void *)
Definition at line 1673 of file sqlite3.c.
Referenced by sqlite3_free(), and sqlite3ScratchFree().
int(* xInit)(void *)
Definition at line 1677 of file sqlite3.c.
Referenced by sqlite3MallocInit().
void *(* xMalloc)(int)
Definition at line 1672 of file sqlite3.c.
Referenced by sqlite3_config(), sqlite3Malloc(), and sqlite3MallocInit().
void *(* xRealloc)(void *, int)
Definition at line 1674 of file sqlite3.c.
Referenced by sqlite3Realloc().
int(* xRoundup)(int)
Definition at line 1676 of file sqlite3.c.
Referenced by sqlite3_db_status(), and sqlite3Realloc().
void(* xShutdown)(void *)
Definition at line 1678 of file sqlite3.c.
Referenced by sqlite3MallocEnd().
int(* xSize)(void *)
Definition at line 1675 of file sqlite3.c.
Referenced by sqlite3_msize(), sqlite3DbMallocSize(), and sqlite3MallocSize().
The documentation for this struct was generated from the following files:
libs/sqlite3.c
libs/sqlite3.h