sqlite3_vfs Struct Reference
#include <sqlite3.h>
Data Fields
int iVersion
int szOsFile
int mxPathname
sqlite3_vfs * pNext
const char * zName
void * pAppData
int(* xOpen)(sqlite3_vfs *, const char *zName, sqlite3_file *, int flags, int *pOutFlags)
int(* xDelete)(sqlite3_vfs *, const char *zName, int syncDir)
int(* xAccess)(sqlite3_vfs *, const char *zName, int flags, int *pResOut)
int(* xFullPathname)(sqlite3_vfs *, const char *zName, int nOut, char *zOut)
void *(* xDlOpen)(sqlite3_vfs *, const char *zFilename)
void(* xDlError)(sqlite3_vfs *, int nByte, char *zErrMsg)
void(*(* xDlSym)(sqlite3_vfs *, void *, const char *zSymbol))(void)
void(* xDlClose)(sqlite3_vfs *, void *)
int(* xRandomness)(sqlite3_vfs *, int nByte, char *zOut)
int(* xSleep)(sqlite3_vfs *, int microseconds)
int(* xCurrentTime)(sqlite3_vfs *, double *)
int(* xGetLastError)(sqlite3_vfs *, int, char *)
int(* xCurrentTimeInt64)(sqlite3_vfs *, sqlite3_int64 *)
int(* xSetSystemCall)(sqlite3_vfs *, const char *zName, sqlite3_syscall_ptr)
sqlite3_syscall_ptr(* xGetSystemCall)(sqlite3_vfs *, const char *zName)
const char *(* xNextSystemCall)(sqlite3_vfs *, const char *zName)
Detailed Description
Definition at line 1376 of file sqlite3.c.
Field Documentation
int iVersion
Definition at line 1377 of file sqlite3.c.
Referenced by sqlite3OsCurrentTimeInt64().
int mxPathname
Definition at line 1379 of file sqlite3.c.
Referenced by sqlite3BtreeOpen(), and sqlite3PagerOpen().
void * pAppData
Definition at line 1382 of file sqlite3.c.
sqlite3_vfs * pNext
Definition at line 1380 of file sqlite3.c.
Referenced by sqlite3_vfs_find(), and sqlite3_vfs_register().
int szOsFile
Definition at line 1378 of file sqlite3.c.
Referenced by sqlite3OsOpenMalloc(), sqlite3PagerOpen(), and sqlite3WalOpen().
int(* xAccess)(sqlite3_vfs *, const char *zName, int flags, int *pResOut)
Definition at line 1386 of file sqlite3.c.
Referenced by sqlite3OsAccess().
int(* xCurrentTime)(sqlite3_vfs *, double *)
Definition at line 1394 of file sqlite3.c.
Referenced by sqlite3OsCurrentTimeInt64().
int(* xCurrentTimeInt64)(sqlite3_vfs *, sqlite3_int64 *)
Definition at line 1400 of file sqlite3.c.
Referenced by sqlite3OsCurrentTimeInt64().
int(* xDelete)(sqlite3_vfs *, const char *zName, int syncDir)
Definition at line 1385 of file sqlite3.c.
Referenced by sqlite3OsDelete().
void(* xDlClose)(sqlite3_vfs *, void *)
Definition at line 1391 of file sqlite3.c.
Referenced by sqlite3OsDlClose().
void(* xDlError)(sqlite3_vfs *, int nByte, char *zErrMsg)
Definition at line 1389 of file sqlite3.c.
Referenced by sqlite3OsDlError().
void *(* xDlOpen)(sqlite3_vfs *, const char *zFilename)
Definition at line 1388 of file sqlite3.c.
Referenced by sqlite3OsDlOpen().
void(*(* xDlSym)(sqlite3_vfs *, void *, const char *zSymbol))(void)
Definition at line 1390 of file sqlite3.c.
int(* xFullPathname)(sqlite3_vfs *, const char *zName, int nOut, char *zOut)
Definition at line 1387 of file sqlite3.c.
Referenced by sqlite3OsFullPathname().
int(* xGetLastError)(sqlite3_vfs *, int, char *)
Definition at line 1395 of file sqlite3.c.
sqlite3_syscall_ptr(* xGetSystemCall)(sqlite3_vfs *, const char *zName)
Definition at line 1406 of file sqlite3.c.
const char *(* xNextSystemCall)(sqlite3_vfs *, const char *zName)
Definition at line 1407 of file sqlite3.c.
int(* xOpen)(sqlite3_vfs *, const char *zName, sqlite3_file *, int flags, int *pOutFlags)
Definition at line 1383 of file sqlite3.c.
Referenced by sqlite3OsOpen().
int(* xRandomness)(sqlite3_vfs *, int nByte, char *zOut)
Definition at line 1392 of file sqlite3.c.
Referenced by sqlite3OsRandomness().
int(* xSetSystemCall)(sqlite3_vfs *, const char *zName, sqlite3_syscall_ptr)
Definition at line 1405 of file sqlite3.c.
int(* xSleep)(sqlite3_vfs *, int microseconds)
Definition at line 1393 of file sqlite3.c.
Referenced by sqlite3OsSleep().
const char * zName
Definition at line 1381 of file sqlite3.c.
Referenced by sqlite3_vfs_find().
The documentation for this struct was generated from the following files:
libs/sqlite3.c
libs/sqlite3.h