sqlite3_io_methods Struct Reference
#include <sqlite3.h>
Data Fields
int iVersion
int(* xClose)(sqlite3_file *)
int(* xRead)(sqlite3_file *, void *, int iAmt, sqlite3_int64 iOfst)
int(* xWrite)(sqlite3_file *, const void *, int iAmt, sqlite3_int64 iOfst)
int(* xTruncate)(sqlite3_file *, sqlite3_int64 size)
int(* xSync)(sqlite3_file *, int flags)
int(* xFileSize)(sqlite3_file *, sqlite3_int64 *pSize)
int(* xLock)(sqlite3_file *, int)
int(* xUnlock)(sqlite3_file *, int)
int(* xCheckReservedLock)(sqlite3_file *, int *pResOut)
int(* xFileControl)(sqlite3_file *, int op, void *pArg)
int(* xSectorSize)(sqlite3_file *)
int(* xDeviceCharacteristics)(sqlite3_file *)
int(* xShmMap)(sqlite3_file *, int iPg, int pgsz, int, void volatile **)
int(* xShmLock)(sqlite3_file *, int offset, int n, int flags)
void(* xShmBarrier)(sqlite3_file *)
int(* xShmUnmap)(sqlite3_file *, int deleteFlag)
int(* xFetch)(sqlite3_file *, sqlite3_int64 iOfst, int iAmt, void **pp)
int(* xUnfetch)(sqlite3_file *, sqlite3_int64 iOfst, void *p)
Detailed Description
Definition at line 938 of file sqlite3.c.
Field Documentation
int iVersion
Definition at line 939 of file sqlite3.c.
Referenced by sqlite3PagerWalSupported(), and sqlite3WalCheckpoint().
int(* xCheckReservedLock)(sqlite3_file *, int *pResOut)
Definition at line 948 of file sqlite3.c.
Referenced by sqlite3OsCheckReservedLock().
int(* xClose)(sqlite3_file *)
Definition at line 940 of file sqlite3.c.
Referenced by sqlite3OsClose().
int(* xDeviceCharacteristics)(sqlite3_file *)
Definition at line 951 of file sqlite3.c.
Referenced by sqlite3OsDeviceCharacteristics().
int(* xFetch)(sqlite3_file *, sqlite3_int64 iOfst, int iAmt, void **pp)
Definition at line 958 of file sqlite3.c.
int(* xFileControl)(sqlite3_file *, int op, void *pArg)
Definition at line 949 of file sqlite3.c.
Referenced by sqlite3OsFileControl(), and sqlite3OsFileControlHint().
int(* xFileSize)(sqlite3_file *, sqlite3_int64 *pSize)
Definition at line 945 of file sqlite3.c.
Referenced by sqlite3OsFileSize().
int(* xLock)(sqlite3_file *, int)
Definition at line 946 of file sqlite3.c.
Referenced by sqlite3OsLock().
int(* xRead)(sqlite3_file *, void *, int iAmt, sqlite3_int64 iOfst)
Definition at line 941 of file sqlite3.c.
Referenced by sqlite3OsRead().
int(* xSectorSize)(sqlite3_file *)
Definition at line 950 of file sqlite3.c.
Referenced by sqlite3OsSectorSize().
void(* xShmBarrier)(sqlite3_file *)
Definition at line 955 of file sqlite3.c.
Referenced by sqlite3OsShmBarrier().
int(* xShmLock)(sqlite3_file *, int offset, int n, int flags)
Definition at line 954 of file sqlite3.c.
Referenced by sqlite3OsShmLock().
int(* xShmMap)(sqlite3_file *, int iPg, int pgsz, int, void volatile **)
Definition at line 953 of file sqlite3.c.
Referenced by sqlite3OsShmMap(), and sqlite3PagerWalSupported().
int(* xShmUnmap)(sqlite3_file *, int deleteFlag)
Definition at line 956 of file sqlite3.c.
Referenced by sqlite3OsShmUnmap().
int(* xSync)(sqlite3_file *, int flags)
Definition at line 944 of file sqlite3.c.
Referenced by sqlite3OsSync().
int(* xTruncate)(sqlite3_file *, sqlite3_int64 size)
Definition at line 943 of file sqlite3.c.
Referenced by sqlite3OsTruncate().
int(* xUnfetch)(sqlite3_file *, sqlite3_int64 iOfst, void *p)
Definition at line 959 of file sqlite3.c.
int(* xUnlock)(sqlite3_file *, int)
Definition at line 947 of file sqlite3.c.
Referenced by sqlite3OsUnlock().
int(* xWrite)(sqlite3_file *, const void *, int iAmt, sqlite3_int64 iOfst)
Definition at line 942 of file sqlite3.c.
Referenced by sqlite3OsWrite().
The documentation for this struct was generated from the following files:
libs/sqlite3.c
libs/sqlite3.h