Walker Struct Reference
Data Fields
int(* xExprCallback)(Walker *, Expr *)
int(* xSelectCallback)(Walker *, Select *)
void(* xSelectCallback2)(Walker *, Select *)
Parse * pParse
int walkerDepth
u8 eCode
xx xx xx xx xx xx xx xx xx
union {
 NameContext * pNC
 int n
 int iCur
 SrcList * pSrcList
 struct SrcCount * pSrcCount
} u
Detailed Description
Definition at line 12853 of file sqlite3.c.
Field Documentation
u8 eCode
Definition at line 12859 of file sqlite3.c.
int iCur
Definition at line 12863 of file sqlite3.c.
int n
Definition at line 12862 of file sqlite3.c.
NameContext* pNC
Definition at line 12861 of file sqlite3.c.
Parse* pParse
Definition at line 12857 of file sqlite3.c.
Referenced by sqlite3ResolveExprNames(), and sqlite3ResolveSelectNames().
struct SrcCount* pSrcCount
Definition at line 12865 of file sqlite3.c.
SrcList* pSrcList
Definition at line 12864 of file sqlite3.c.
union { ... } u
int walkerDepth
Definition at line 12858 of file sqlite3.c.
Referenced by sqlite3WalkSelect().
int(* xExprCallback) (Walker *, Expr *)
Definition at line 12854 of file sqlite3.c.
Referenced by sqlite3ExprAnalyzeAggregates(), sqlite3FunctionUsesThisSrc(), sqlite3ResolveExprNames(), sqlite3ResolveSelectNames(), and sqlite3WalkExpr().
int(* xSelectCallback) (Walker *, Select *)
Definition at line 12855 of file sqlite3.c.
Referenced by sqlite3ExprAnalyzeAggregates(), sqlite3ResolveExprNames(), sqlite3ResolveSelectNames(), and sqlite3WalkSelect().
void(* xSelectCallback2) (Walker *, Select *)
Definition at line 12856 of file sqlite3.c.
Referenced by sqlite3WalkSelect().
The documentation for this struct was generated from the following file:
libs/sqlite3.c