sqlite3_pcache_methods2 Struct Reference
#include <sqlite3.h>
Data Fields
int iVersion
void * pArg
int(* xInit)(void *)
void(* xShutdown)(void *)
sqlite3_pcache *(* xCreate)(int szPage, int szExtra, int bPurgeable)
void(* xCachesize)(sqlite3_pcache *, int nCachesize)
int(* xPagecount)(sqlite3_pcache *)
sqlite3_pcache_page *(* xFetch)(sqlite3_pcache *, unsigned key, int createFlag)
void(* xUnpin)(sqlite3_pcache *, sqlite3_pcache_page *, int discard)
void(* xRekey)(sqlite3_pcache *, sqlite3_pcache_page *, unsigned oldKey, unsigned newKey)
void(* xTruncate)(sqlite3_pcache *, unsigned iLimit)
void(* xDestroy)(sqlite3_pcache *)
void(* xShrink)(sqlite3_pcache *)
Detailed Description
Definition at line 7095 of file sqlite3.c.
Field Documentation
int iVersion
Definition at line 7096 of file sqlite3.c.
void * pArg
Definition at line 7097 of file sqlite3.c.
Referenced by sqlite3PcacheInitialize(), and sqlite3PcacheShutdown().
void(* xCachesize)(sqlite3_pcache *, int nCachesize)
Definition at line 7101 of file sqlite3.c.
Referenced by sqlite3PcacheSetCachesize(), and sqlite3PcacheSetPageSize().
sqlite3_pcache *(* xCreate)(int szPage, int szExtra, int bPurgeable)
Definition at line 7100 of file sqlite3.c.
void(* xDestroy)(sqlite3_pcache *)
Definition at line 7108 of file sqlite3.c.
Referenced by sqlite3PcacheClose(), and sqlite3PcacheSetPageSize().
sqlite3_pcache_page *(* xFetch)(sqlite3_pcache *, unsigned key, int createFlag)
Definition at line 7103 of file sqlite3.c.
int(* xInit)(void *)
Definition at line 7098 of file sqlite3.c.
Referenced by sqlite3_config(), and sqlite3PcacheInitialize().
int(* xPagecount)(sqlite3_pcache *)
Definition at line 7102 of file sqlite3.c.
Referenced by sqlite3PcachePagecount().
void(* xRekey)(sqlite3_pcache *, sqlite3_pcache_page *, unsigned oldKey, unsigned newKey)
Definition at line 7105 of file sqlite3.c.
Referenced by sqlite3PcacheMove().
void(* xShrink)(sqlite3_pcache *)
Definition at line 7109 of file sqlite3.c.
Referenced by sqlite3PcacheShrink().
void(* xShutdown)(void *)
Definition at line 7099 of file sqlite3.c.
Referenced by sqlite3PcacheShutdown().
void(* xTruncate)(sqlite3_pcache *, unsigned iLimit)
Definition at line 7107 of file sqlite3.c.
Referenced by sqlite3PcacheTruncate().
void(* xUnpin)(sqlite3_pcache *, sqlite3_pcache_page *, int discard)
Definition at line 7104 of file sqlite3.c.
Referenced by sqlite3PcacheDrop().
The documentation for this struct was generated from the following files:
libs/sqlite3.c
libs/sqlite3.h