FuncDef Struct Reference
Data Fields
i16 nArg
u16 funcFlags
void * pUserData
FuncDef * pNext
void(* xFunc)(sqlite3_context *, int, sqlite3_value **)
void(* xStep)(sqlite3_context *, int, sqlite3_value **)
void(* xFinalize)(sqlite3_context *)
char * zName
FuncDef * pHash
FuncDestructor * pDestructor
Detailed Description
Definition at line 11202 of file sqlite3.c.
Field Documentation
u16 funcFlags
Definition at line 11204 of file sqlite3.c.
Referenced by sqlite3CreateFunc(), sqlite3ExprCodeTarget(), sqlite3IsLikeFunction(), and sqlite3VtabOverloadFunction().
i16 nArg
Definition at line 11203 of file sqlite3.c.
Referenced by sqlite3CreateFunc().
FuncDestructor* pDestructor
Definition at line 11212 of file sqlite3.c.
Referenced by sqlite3CreateFunc().
FuncDef* pHash
Definition at line 11211 of file sqlite3.c.
Referenced by sqlite3FuncDefInsert(), and sqlite3LeaveMutexAndCloseZombie().
FuncDef* pNext
Definition at line 11206 of file sqlite3.c.
Referenced by sqlite3FindFunction(), sqlite3FuncDefInsert(), and sqlite3LeaveMutexAndCloseZombie().
void* pUserData
Definition at line 11205 of file sqlite3.c.
Referenced by sqlite3_user_data(), sqlite3CreateFunc(), sqlite3IsLikeFunction(), and sqlite3VtabOverloadFunction().
void(* xFinalize) (sqlite3_context *)
Definition at line 11209 of file sqlite3.c.
Referenced by sqlite3CreateFunc(), and sqlite3VdbeMemFinalize().
void(* xFunc) (sqlite3_context *, int, sqlite3_value **)
Definition at line 11207 of file sqlite3.c.
Referenced by sqlite3CreateFunc(), sqlite3ExprCodeTarget(), sqlite3FindFunction(), sqlite3VdbeExec(), and sqlite3VtabOverloadFunction().
void(* xStep) (sqlite3_context *, int, sqlite3_value **)
Definition at line 11208 of file sqlite3.c.
Referenced by sqlite3CreateFunc(), sqlite3FindFunction(), and sqlite3VdbeExec().
char* zName
Definition at line 11210 of file sqlite3.c.
Referenced by sqlite3FuncDefInsert(), sqlite3InvalidFunction(), and sqlite3VtabOverloadFunction().
The documentation for this struct was generated from the following file:
libs/sqlite3.c