sqlite3_mutex_methods Struct Reference
#include <sqlite3.h>
Data Fields
int(* xMutexInit)(void)
int(* xMutexEnd)(void)
sqlite3_mutex *(* xMutexAlloc)(int)
void(* xMutexFree)(sqlite3_mutex *)
void(* xMutexEnter)(sqlite3_mutex *)
int(* xMutexTry)(sqlite3_mutex *)
void(* xMutexLeave)(sqlite3_mutex *)
int(* xMutexHeld)(sqlite3_mutex *)
int(* xMutexNotheld)(sqlite3_mutex *)
Detailed Description
Definition at line 6410 of file sqlite3.c.
Field Documentation
sqlite3_mutex *(* xMutexAlloc)(int)
Definition at line 6413 of file sqlite3.c.
int(* xMutexEnd)(void)
Definition at line 6412 of file sqlite3.c.
Referenced by sqlite3MutexEnd().
void(* xMutexEnter)(sqlite3_mutex *)
Definition at line 6415 of file sqlite3.c.
Referenced by sqlite3_mutex_enter().
void(* xMutexFree)(sqlite3_mutex *)
Definition at line 6414 of file sqlite3.c.
Referenced by sqlite3_mutex_free(), and sqlite3MutexInit().
int(* xMutexHeld)(sqlite3_mutex *)
Definition at line 6418 of file sqlite3.c.
int(* xMutexInit)(void)
Definition at line 6411 of file sqlite3.c.
Referenced by sqlite3MutexInit().
void(* xMutexLeave)(sqlite3_mutex *)
Definition at line 6417 of file sqlite3.c.
Referenced by sqlite3_mutex_leave().
int(* xMutexNotheld)(sqlite3_mutex *)
Definition at line 6419 of file sqlite3.c.
int(* xMutexTry)(sqlite3_mutex *)
Definition at line 6416 of file sqlite3.c.
Referenced by sqlite3_mutex_try().
The documentation for this struct was generated from the following files:
libs/sqlite3.c
libs/sqlite3.h