CollSeq Struct Reference
Data Fields
char * zName
u8 enc
void * pUser
int(* xCmp)(void *, int, const void *, int, const void *)
void(* xDel)(void *)
Detailed Description
Definition at line 11367 of file sqlite3.c.
Field Documentation
u8 enc
Definition at line 11369 of file sqlite3.c.
void* pUser
Definition at line 11370 of file sqlite3.c.
Referenced by sqlite3LeaveMutexAndCloseZombie().
int(* xCmp) (void *, int, const void *, int, const void *)
Definition at line 11371 of file sqlite3.c.
Referenced by sqlite3GetCollSeq(), and sqlite3LocateCollSeq().
void(* xDel) (void *)
Definition at line 11372 of file sqlite3.c.
Referenced by sqlite3LeaveMutexAndCloseZombie().
char* zName
Definition at line 11368 of file sqlite3.c.
Referenced by sqlite3CheckCollSeq(), and sqlite3Pragma().
The documentation for this struct was generated from the following file:
libs/sqlite3.c