sqlite3_module Struct Reference
#include <sqlite3.h>
Data Fields
int iVersion
int(* xCreate)(sqlite3 *, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVTab, char **)
int(* xConnect)(sqlite3 *, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVTab, char **)
int(* xBestIndex)(sqlite3_vtab *pVTab, sqlite3_index_info *)
int(* xDisconnect)(sqlite3_vtab *pVTab)
int(* xDestroy)(sqlite3_vtab *pVTab)
int(* xOpen)(sqlite3_vtab *pVTab, sqlite3_vtab_cursor **ppCursor)
int(* xClose)(sqlite3_vtab_cursor *)
int(* xFilter)(sqlite3_vtab_cursor *, int idxNum, const char *idxStr, int argc, sqlite3_value **argv)
int(* xNext)(sqlite3_vtab_cursor *)
int(* xEof)(sqlite3_vtab_cursor *)
int(* xColumn)(sqlite3_vtab_cursor *, sqlite3_context *, int)
int(* xRowid)(sqlite3_vtab_cursor *, sqlite3_int64 *pRowid)
int(* xUpdate)(sqlite3_vtab *, int, sqlite3_value **, sqlite3_int64 *)
int(* xBegin)(sqlite3_vtab *pVTab)
int(* xSync)(sqlite3_vtab *pVTab)
int(* xCommit)(sqlite3_vtab *pVTab)
int(* xRollback)(sqlite3_vtab *pVTab)
int(* xFindFunction)(sqlite3_vtab *pVtab, int nArg, const char *zName, void(**pxFunc)(sqlite3_context *, int, sqlite3_value **), void **ppArg)
int(* xRename)(sqlite3_vtab *pVtab, const char *zNew)
int(* xSavepoint)(sqlite3_vtab *pVTab, int)
int(* xRelease)(sqlite3_vtab *pVTab, int)
int(* xRollbackTo)(sqlite3_vtab *pVTab, int)
Detailed Description
Definition at line 5693 of file sqlite3.c.
Field Documentation
int iVersion
Definition at line 5694 of file sqlite3.c.
Referenced by sqlite3VtabSavepoint().
int(* xBegin)(sqlite3_vtab *pVTab)
Definition at line 5713 of file sqlite3.c.
Referenced by sqlite3VtabBegin().
int(* xBestIndex)(sqlite3_vtab *pVTab, sqlite3_index_info *)
Definition at line 5701 of file sqlite3.c.
int(* xClose)(sqlite3_vtab_cursor *)
Definition at line 5705 of file sqlite3.c.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeFreeCursor().
int(* xColumn)(sqlite3_vtab_cursor *, sqlite3_context *, int)
Definition at line 5710 of file sqlite3.c.
Referenced by sqlite3VdbeExec().
int(* xCommit)(sqlite3_vtab *pVTab)
Definition at line 5715 of file sqlite3.c.
Referenced by sqlite3VtabCommit().
int(* xConnect)(sqlite3 *, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVTab, char **)
Definition at line 5698 of file sqlite3.c.
Referenced by sqlite3VtabCallConnect().
int(* xCreate)(sqlite3 *, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVTab, char **)
Definition at line 5695 of file sqlite3.c.
Referenced by sqlite3VtabCallCreate().
int(* xDestroy)(sqlite3_vtab *pVTab)
Definition at line 5703 of file sqlite3.c.
Referenced by sqlite3VtabCallDestroy().
int(* xDisconnect)(sqlite3_vtab *pVTab)
Definition at line 5702 of file sqlite3.c.
Referenced by sqlite3VtabUnlock().
int(* xEof)(sqlite3_vtab_cursor *)
Definition at line 5709 of file sqlite3.c.
Referenced by sqlite3VdbeExec().
int(* xFilter)(sqlite3_vtab_cursor *, int idxNum, const char *idxStr, int argc, sqlite3_value **argv)
Definition at line 5706 of file sqlite3.c.
Referenced by sqlite3VdbeExec().
int(* xFindFunction)(sqlite3_vtab *pVtab, int nArg, const char *zName, void(**pxFunc)(sqlite3_context *, int, sqlite3_value **), void **ppArg)
Definition at line 5717 of file sqlite3.c.
Referenced by sqlite3VtabOverloadFunction().
int(* xNext)(sqlite3_vtab_cursor *)
Definition at line 5708 of file sqlite3.c.
Referenced by sqlite3VdbeExec().
int(* xOpen)(sqlite3_vtab *pVTab, sqlite3_vtab_cursor **ppCursor)
Definition at line 5704 of file sqlite3.c.
Referenced by sqlite3VdbeExec().
int(* xRelease)(sqlite3_vtab *pVTab, int)
Definition at line 5724 of file sqlite3.c.
Referenced by sqlite3VtabSavepoint().
int(* xRename)(sqlite3_vtab *pVtab, const char *zNew)
Definition at line 5720 of file sqlite3.c.
Referenced by sqlite3AlterRenameTable(), and sqlite3VdbeExec().
int(* xRollback)(sqlite3_vtab *pVTab)
Definition at line 5716 of file sqlite3.c.
Referenced by sqlite3VtabRollback().
int(* xRollbackTo)(sqlite3_vtab *pVTab, int)
Definition at line 5725 of file sqlite3.c.
Referenced by sqlite3VtabSavepoint().
int(* xRowid)(sqlite3_vtab_cursor *, sqlite3_int64 *pRowid)
Definition at line 5711 of file sqlite3.c.
Referenced by sqlite3VdbeExec().
int(* xSavepoint)(sqlite3_vtab *pVTab, int)
Definition at line 5723 of file sqlite3.c.
Referenced by sqlite3VtabSavepoint().
int(* xSync)(sqlite3_vtab *pVTab)
Definition at line 5714 of file sqlite3.c.
Referenced by sqlite3VtabSync().
int(* xUpdate)(sqlite3_vtab *, int, sqlite3_value **, sqlite3_int64 *)
Definition at line 5712 of file sqlite3.c.
Referenced by sqlite3IsReadOnly(), and sqlite3VdbeExec().
The documentation for this struct was generated from the following files:
libs/sqlite3.c
libs/sqlite3.h