membranePotential  = ""
posThreshold  = "alpha"
negThreshold  = "beta"
 myCoreID  = "coreID"
 myLocalID  = "localID"
 lambda  = "lmbda"
 resetMode  = "gamma"
 sigmaVR  = "sigmaVR"
 encodedResetVoltage  = "VR"
 sigma_l  = "sigma_lmbda"
 delayVal  = ""
 
 
 isSelfFiring  = "selfFiring"
 isOutputNeuron  = "outputNeuron"
 epsilon  = "epsilon"
 c  = "c"
 kappa  = "kappa"
 canGenerateSpontaniousSpikes  = ""
 axonTypes  = "g_i"
 synapticWeight  = "S"
 synapticConnectivity  = "synapticConnectivity"
 weightSelection  = ""
sigma = "sigmaG"