//
//  synapse.h
//  ROSS_TOP
//
//  Created by Mark Plagge on 6/18/15.
//
//

#ifndef __ROSS_TOP__synapse__
#define __ROSS_TOP__synapse__

#include <stdio.h>
#include "../assist.h"
/**Synapse state structure. Synapses have a destination GID, calculated on creation from the current core and the mapping table. Each synapse talks to its connected neuron, sending messages to the neuron at a TS of ε, generated by the function in assist.h getNextEventTS. @see getNextEventTS(tw_lp* lp). Synapses within the core, I.E., neuron nums < j-1, send a message at ε to the next synapse in the core. This simulates the "synaptic crossbar" found in the TrueNorth architecture.
 Synapses also have stats on sent neuron messages, and sent synapse messages. */

typedef struct SynapseState {
	tw_lpid destSynapse;
	tw_lpid destNeuron;
	id_t mySynapseNum;
	_statT msgSent;
	

}synapseState;

void synapseReceiveMessage(synapseState *st, Msg_Data *M, tw_lp *lp);
void synapseReverseState(synapseState *st, Msg_Data *M, tw_lp *lp);
#endif /* defined(__ROSS_TOP__synapse__) */
